export const MENU_ID_COMPAT_ALIASES: Record<string, string> = {
  "admin-overview": "MNU_ADMIN_DASH",
  "client-dashboard": "MNU_CUSTOMER_DASH",
  "tenant-control": "MNU_ADMIN_TENANT",
  "tenant-list": "MNU_ADMIN_TENANT_LIST",
  "tenant-settings": "MNU_ADMIN_TENANT_SETTINGS",
  "company-profile": "MNU_ADMIN_COMPANY_PROFILE",
  "workspace-policy": "MNU_ADMIN_WORKSPACE_POLICY",
  "menu-policy": "MNU_ADMIN_MENU_POLICY",
  authorization: "MNU_ADMIN_AUTH",
  "role-policy": "MNU_ADMIN_ROLE_POLICY",
  "menu-management": "MNU_ADMIN_MENU",
  "menu-tree": "MNU_ADMIN_MENU_TREE",
  "tab-policy": "MNU_ADMIN_TAB_POLICY",
  "depth-policy": "MNU_ADMIN_DEPTH_POLICY",
  "depth-editor": "MNU_ADMIN_DEPTH_EDITOR",
  "billing-ops": "MNU_ADMIN_BILL",
  "plan-catalog": "MNU_ADMIN_PLAN_CATALOG",
  "payment-gates": "MNU_ADMIN_PAYMENT_GATES",
  "upgrade-queue": "MNU_ADMIN_UPGRADE_QUEUE",
  "audit-center": "MNU_ADMIN_AUDIT",
  "change-history": "MNU_ADMIN_CHANGE_HISTORY",
  "access-logs": "MNU_ADMIN_ACCESS_LOGS",
  compliance: "MNU_ADMIN_COMPLIANCE",
  "billing-center": "MNU_CUSTOMER_WORK_TIME",
  workspace: "MNU_CUSTOMER_MY_TIME",
  documents: "MNU_CUSTOMER_MY_TIME",
  "ocr-inbox": "MNU_CUSTOMER_MY_TIME",
  "expense-review": "MNU_CUSTOMER_MY_TIME",
  archive: "MNU_CUSTOMER_MY_TIME",
  attendance: "MNU_CUSTOMER_MY_TIME",
  "my-time": "MNU_CUSTOMER_MY_TIME",
  "team-time": "MNU_CUSTOMER_TEAM_TIME",
  leave: "MNU_CUSTOMER_LEAVE",
  people: "MNU_CUSTOMER_MY_TIME",
  employees: "MNU_CUSTOMER_MY_TIME",
  organization: "MNU_CUSTOMER_MY_TIME",
  departments: "MNU_CUSTOMER_MY_TIME",
  roles: "MNU_CUSTOMER_MY_TIME",
  subscription: "MNU_CUSTOMER_WORK_TIME",
  payments: "MNU_CUSTOMER_WORK_TIME",
};

export const REVERSE_MENU_ID_COMPAT_ALIASES = Object.fromEntries(
  Object.entries(MENU_ID_COMPAT_ALIASES).map(([legacyId, dbId]) => [dbId, legacyId])
) as Record<string, string>;

// Developer note:
// Removed client-side runtime menus are redirected to the new simplified
// top-level client pages so old persisted tabs still open a valid screen.
export const CLIENT_MENU_RUNTIME_REDIRECTS: Record<string, string> = {
  "client-dashboard": "MNU_CUSTOMER_DASH",
  workspace: "MNU_CUSTOMER_MY_TIME",
  documents: "MNU_CUSTOMER_MY_TIME",
  "ocr-inbox": "MNU_CUSTOMER_MY_TIME",
  "expense-review": "MNU_CUSTOMER_MY_TIME",
  archive: "MNU_CUSTOMER_MY_TIME",
  people: "MNU_CUSTOMER_MY_TIME",
  employees: "MNU_CUSTOMER_MY_TIME",
  organization: "MNU_CUSTOMER_MY_TIME",
  departments: "MNU_CUSTOMER_MY_TIME",
  roles: "MNU_CUSTOMER_MY_TIME",
  "billing-center": "MNU_CUSTOMER_WORK_TIME",
  subscription: "MNU_CUSTOMER_WORK_TIME",
  payments: "MNU_CUSTOMER_WORK_TIME",
  MNU_CUSTOMER_WORKSPACE: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_DOC: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_OCR_INBOX: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_EXPENSE_REVIEW: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_ARCHIVE: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_PEOPLE: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_EMPLOYEES: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_ORG: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_DEPARTMENTS: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_ROLES: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_PAY: "MNU_CUSTOMER_WORK_TIME",
  MNU_CUSTOMER_SUBSCRIPTION: "MNU_CUSTOMER_WORK_TIME",
  MNU_CUSTOMER_PAYMENTS: "MNU_CUSTOMER_WORK_TIME",
  attendance: "MNU_CUSTOMER_MY_TIME",
  "my-time": "MNU_CUSTOMER_MY_TIME",
  "team-time": "MNU_CUSTOMER_TEAM_TIME",
  leave: "MNU_CUSTOMER_LEAVE",
  MNU_CUSTOMER_DASH: "MNU_CUSTOMER_DASH",
  MNU_CUSTOMER_ATTENDANCE: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_MY_TIME: "MNU_CUSTOMER_MY_TIME",
  MNU_CUSTOMER_TEAM_TIME: "MNU_CUSTOMER_TEAM_TIME",
  MNU_CUSTOMER_LEAVE: "MNU_CUSTOMER_LEAVE",
  MNU_CUSTOMER_REPORTS: "MNU_CUSTOMER_WORK_TIME",
  MNU_CUSTOMER_WORK_TIME: "MNU_CUSTOMER_WORK_TIME",
  MNU_CUSTOMER_WORK_TIME_HISTORY: "MNU_CUSTOMER_WORK_TIME",
  MNU_CUSTOMER_ADMIN: "MNU_CUSTOMER_ADMIN_HOME",
};
