ALTER TABLE TB_MNU
    ADD COLUMN BILL_GATE_CD VARCHAR(30) NULL COMMENT 'Billing gate code' AFTER DSP_ORD;

ALTER TABLE TB_MNU_HIST
    ADD COLUMN BILL_GATE_CD VARCHAR(30) NULL COMMENT 'Billing gate code' AFTER DSP_ORD;

DROP TRIGGER IF EXISTS TR_TB_MNU_AI;
DROP TRIGGER IF EXISTS TR_TB_MNU_AU;
DROP TRIGGER IF EXISTS TR_TB_MNU_BD;

CREATE TRIGGER TR_TB_MNU_AI
AFTER INSERT ON TB_MNU
FOR EACH ROW
INSERT INTO TB_MNU_HIST (
    HIST_TP, HIST_BY, ID, MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.MNU_CD, NEW.MNU_NM, NEW.MNU_SCOPE_CD, NEW.UP_MNU_ID, NEW.PATH_URI, NEW.ICON_NM, NEW.DSP_ORD, NEW.BILL_GATE_CD, NEW.USE_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_MNU_AU
AFTER UPDATE ON TB_MNU
FOR EACH ROW
INSERT INTO TB_MNU_HIST (
    HIST_TP, HIST_BY, ID, MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.MNU_CD, NEW.MNU_NM, NEW.MNU_SCOPE_CD, NEW.UP_MNU_ID, NEW.PATH_URI, NEW.ICON_NM, NEW.DSP_ORD, NEW.BILL_GATE_CD, NEW.USE_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_MNU_BD
BEFORE DELETE ON TB_MNU
FOR EACH ROW
INSERT INTO TB_MNU_HIST (
    HIST_TP, HIST_BY, ID, MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.MNU_CD, OLD.MNU_NM, OLD.MNU_SCOPE_CD, OLD.UP_MNU_ID, OLD.PATH_URI, OLD.ICON_NM, OLD.DSP_ORD, OLD.BILL_GATE_CD, OLD.USE_YN, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

UPDATE TB_MNU
SET BILL_GATE_CD = NULL
WHERE MNU_CD IN ('MNU_ADMIN_DASH', 'MNU_ADMIN_TENANT', 'MNU_ADMIN_AUTH', 'MNU_ADMIN_BILL', 'MNU_ADMIN_MENU', 'MNU_CUSTOMER_DASH', 'MNU_CUSTOMER_PAY');

UPDATE TB_MNU
SET BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN'
WHERE MNU_CD IN ('MNU_CUSTOMER_TEAM', 'MNU_CUSTOMER_HR', 'MNU_CUSTOMER_FIN');

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID, m.ID, 'Y', 'N', 'N', 'N', 'N', 'N', 'SYSTEM', 'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_CD = 'MNU_CUSTOMER_PAY'
WHERE r.ROLE_CD IN ('ROLE_CUSTOMER_USER_MEMBER', 'ROLE_CUSTOMER_USER_LEADER')
  AND NOT EXISTS (
      SELECT 1
      FROM TB_ROLE_MNU_AUTH a
      WHERE a.ROLE_ID = r.ID
        AND a.MNU_ID = m.ID
  );
