INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID, m.ID, 'Y', 'N', 'N', 'N', 'N', 'N', 'SYSTEM', 'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_CD = 'MNU_CUSTOMER_PAY'
WHERE r.ROLE_CD IN ('ROLE_CUSTOMER_HR_ADMIN_MEMBER', 'ROLE_CUSTOMER_HR_ADMIN_LEADER')
  AND NOT EXISTS (
      SELECT 1
      FROM TB_ROLE_MNU_AUTH a
      WHERE a.ROLE_ID = r.ID
        AND a.MNU_ID = m.ID
  );
