CREATE TABLE TB_CD_GRP (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Code group primary key',
    GRP_CD VARCHAR(100) NOT NULL COMMENT 'Code group code',
    GRP_NM_KO VARCHAR(255) NOT NULL COMMENT 'Code group name Korean',
    GRP_NM_EN VARCHAR(255) NOT NULL COMMENT 'Code group name English',
    GRP_NM_DE VARCHAR(255) NOT NULL COMMENT 'Code group name German',
    SYS_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'System group yes or no',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'Use yes or no',
    DSP_ORD INT NOT NULL DEFAULT 0 COMMENT 'Display order',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_CD_GRP PRIMARY KEY (ID),
    CONSTRAINT UK_TB_CD_GRP_GRP_CD UNIQUE (GRP_CD)
) COMMENT='Common code group';

CREATE TABLE TB_CD (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Common code primary key',
    GRP_ID BIGINT NOT NULL COMMENT 'Code group primary key reference',
    CD VARCHAR(100) NOT NULL COMMENT 'Common code',
    CD_NM_KO VARCHAR(255) NOT NULL COMMENT 'Code name Korean',
    CD_NM_EN VARCHAR(255) NOT NULL COMMENT 'Code name English',
    CD_NM_DE VARCHAR(255) NOT NULL COMMENT 'Code name German',
    CD_DESC_KO TEXT NULL COMMENT 'Code description Korean',
    CD_DESC_EN TEXT NULL COMMENT 'Code description English',
    CD_DESC_DE TEXT NULL COMMENT 'Code description German',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'Use yes or no',
    DSP_ORD INT NOT NULL DEFAULT 0 COMMENT 'Display order',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_CD PRIMARY KEY (ID),
    CONSTRAINT UK_TB_CD_GRP_ID_CD UNIQUE (GRP_ID, CD),
    CONSTRAINT FK_TB_CD_01 FOREIGN KEY (GRP_ID) REFERENCES TB_CD_GRP (ID)
) COMMENT='Common code';

CREATE TABLE TB_CD_GRP_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Code group primary key',
    GRP_CD VARCHAR(100) NOT NULL COMMENT 'Code group code',
    GRP_NM_KO VARCHAR(255) NOT NULL COMMENT 'Code group name Korean',
    GRP_NM_EN VARCHAR(255) NOT NULL COMMENT 'Code group name English',
    GRP_NM_DE VARCHAR(255) NOT NULL COMMENT 'Code group name German',
    SYS_YN CHAR(1) NOT NULL COMMENT 'System group yes or no',
    USE_YN CHAR(1) NOT NULL COMMENT 'Use yes or no',
    DSP_ORD INT NOT NULL COMMENT 'Display order',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_CD_GRP_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Common code group history';

CREATE TABLE TB_CD_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Common code primary key',
    GRP_ID BIGINT NOT NULL COMMENT 'Code group primary key reference',
    CD VARCHAR(100) NOT NULL COMMENT 'Common code',
    CD_NM_KO VARCHAR(255) NOT NULL COMMENT 'Code name Korean',
    CD_NM_EN VARCHAR(255) NOT NULL COMMENT 'Code name English',
    CD_NM_DE VARCHAR(255) NOT NULL COMMENT 'Code name German',
    CD_DESC_KO TEXT NULL COMMENT 'Code description Korean',
    CD_DESC_EN TEXT NULL COMMENT 'Code description English',
    CD_DESC_DE TEXT NULL COMMENT 'Code description German',
    USE_YN CHAR(1) NOT NULL COMMENT 'Use yes or no',
    DSP_ORD INT NOT NULL COMMENT 'Display order',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_CD_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Common code history';

CREATE INDEX IX_TB_CD_GRP_HIST_ID ON TB_CD_GRP_HIST (ID);
CREATE INDEX IX_TB_CD_GRP_HIST_HIST_DTM ON TB_CD_GRP_HIST (HIST_DTM);
CREATE INDEX IX_TB_CD_GRP_USE_YN ON TB_CD_GRP (USE_YN);
CREATE INDEX IX_TB_CD_GRP_DSP_ORD ON TB_CD_GRP (DSP_ORD);
CREATE INDEX IX_TB_CD_HIST_ID ON TB_CD_HIST (ID);
CREATE INDEX IX_TB_CD_HIST_HIST_DTM ON TB_CD_HIST (HIST_DTM);
CREATE INDEX IX_TB_CD_GRP_ID ON TB_CD (GRP_ID);
CREATE INDEX IX_TB_CD_USE_YN ON TB_CD (USE_YN);
CREATE INDEX IX_TB_CD_DSP_ORD ON TB_CD (DSP_ORD);

CREATE TRIGGER TR_TB_CD_GRP_AI
AFTER INSERT ON TB_CD_GRP
FOR EACH ROW
INSERT INTO TB_CD_GRP_HIST (
    HIST_TP, HIST_BY, ID, GRP_CD, GRP_NM_KO, GRP_NM_EN, GRP_NM_DE, SYS_YN, USE_YN, DSP_ORD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.GRP_CD, NEW.GRP_NM_KO, NEW.GRP_NM_EN, NEW.GRP_NM_DE, NEW.SYS_YN, NEW.USE_YN, NEW.DSP_ORD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CD_GRP_AU
AFTER UPDATE ON TB_CD_GRP
FOR EACH ROW
INSERT INTO TB_CD_GRP_HIST (
    HIST_TP, HIST_BY, ID, GRP_CD, GRP_NM_KO, GRP_NM_EN, GRP_NM_DE, SYS_YN, USE_YN, DSP_ORD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.GRP_CD, NEW.GRP_NM_KO, NEW.GRP_NM_EN, NEW.GRP_NM_DE, NEW.SYS_YN, NEW.USE_YN, NEW.DSP_ORD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CD_GRP_BD
BEFORE DELETE ON TB_CD_GRP
FOR EACH ROW
INSERT INTO TB_CD_GRP_HIST (
    HIST_TP, HIST_BY, ID, GRP_CD, GRP_NM_KO, GRP_NM_EN, GRP_NM_DE, SYS_YN, USE_YN, DSP_ORD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.GRP_CD, OLD.GRP_NM_KO, OLD.GRP_NM_EN, OLD.GRP_NM_DE, OLD.SYS_YN, OLD.USE_YN, OLD.DSP_ORD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TRIGGER TR_TB_CD_AI
AFTER INSERT ON TB_CD
FOR EACH ROW
INSERT INTO TB_CD_HIST (
    HIST_TP, HIST_BY, ID, GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, CD_DESC_KO, CD_DESC_EN, CD_DESC_DE, USE_YN, DSP_ORD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.GRP_ID, NEW.CD, NEW.CD_NM_KO, NEW.CD_NM_EN, NEW.CD_NM_DE, NEW.CD_DESC_KO, NEW.CD_DESC_EN, NEW.CD_DESC_DE, NEW.USE_YN, NEW.DSP_ORD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CD_AU
AFTER UPDATE ON TB_CD
FOR EACH ROW
INSERT INTO TB_CD_HIST (
    HIST_TP, HIST_BY, ID, GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, CD_DESC_KO, CD_DESC_EN, CD_DESC_DE, USE_YN, DSP_ORD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.GRP_ID, NEW.CD, NEW.CD_NM_KO, NEW.CD_NM_EN, NEW.CD_NM_DE, NEW.CD_DESC_KO, NEW.CD_DESC_EN, NEW.CD_DESC_DE, NEW.USE_YN, NEW.DSP_ORD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CD_BD
BEFORE DELETE ON TB_CD
FOR EACH ROW
INSERT INTO TB_CD_HIST (
    HIST_TP, HIST_BY, ID, GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, CD_DESC_KO, CD_DESC_EN, CD_DESC_DE, USE_YN, DSP_ORD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.GRP_ID, OLD.CD, OLD.CD_NM_KO, OLD.CD_NM_EN, OLD.CD_NM_DE, OLD.CD_DESC_KO, OLD.CD_DESC_EN, OLD.CD_DESC_DE, OLD.USE_YN, OLD.DSP_ORD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

ALTER TABLE TB_MNU
    ADD COLUMN MNU_NM_CD VARCHAR(100) NULL COMMENT 'Menu name common code' AFTER MNU_CD;

ALTER TABLE TB_MNU_HIST
    ADD COLUMN MNU_NM_CD VARCHAR(100) NULL COMMENT 'Menu name common code' AFTER MNU_CD;

CREATE INDEX IX_TB_MNU_MNU_NM_CD ON TB_MNU (MNU_NM_CD);

DROP TRIGGER IF EXISTS TR_TB_MNU_AI;
DROP TRIGGER IF EXISTS TR_TB_MNU_AU;
DROP TRIGGER IF EXISTS TR_TB_MNU_BD;

CREATE TRIGGER TR_TB_MNU_AI
AFTER INSERT ON TB_MNU
FOR EACH ROW
INSERT INTO TB_MNU_HIST (
    HIST_TP, HIST_BY, ID, MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.MNU_CD, NEW.MNU_NM_CD, NEW.MNU_NM, NEW.MNU_SCOPE_CD, NEW.UP_MNU_ID, NEW.PATH_URI, NEW.ICON_NM, NEW.DSP_ORD, NEW.BILL_GATE_CD, NEW.USE_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_MNU_AU
AFTER UPDATE ON TB_MNU
FOR EACH ROW
INSERT INTO TB_MNU_HIST (
    HIST_TP, HIST_BY, ID, MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.MNU_CD, NEW.MNU_NM_CD, NEW.MNU_NM, NEW.MNU_SCOPE_CD, NEW.UP_MNU_ID, NEW.PATH_URI, NEW.ICON_NM, NEW.DSP_ORD, NEW.BILL_GATE_CD, NEW.USE_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_MNU_BD
BEFORE DELETE ON TB_MNU
FOR EACH ROW
INSERT INTO TB_MNU_HIST (
    HIST_TP, HIST_BY, ID, MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.MNU_CD, OLD.MNU_NM_CD, OLD.MNU_NM, OLD.MNU_SCOPE_CD, OLD.UP_MNU_ID, OLD.PATH_URI, OLD.ICON_NM, OLD.DSP_ORD, OLD.BILL_GATE_CD, OLD.USE_YN, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

INSERT INTO TB_CD_GRP (
    GRP_CD, GRP_NM_KO, GRP_NM_EN, GRP_NM_DE, SYS_YN, USE_YN, DSP_ORD, CRT_BY, UPD_BY
) VALUES (
    'MNU_NM', '메뉴명', 'Menu Name', 'Menüname', 'Y', 'Y', 10, 'SYSTEM', 'SYSTEM'
);

SET @MNU_GRP_ID = (SELECT ID FROM TB_CD_GRP WHERE GRP_CD = 'MNU_NM' LIMIT 1);

INSERT INTO TB_CD (
    GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, CD_DESC_KO, CD_DESC_EN, CD_DESC_DE, USE_YN, DSP_ORD, CRT_BY, UPD_BY
)
SELECT
    @MNU_GRP_ID,
    MNU_CD,
    MNU_NM,
    MNU_NM,
    MNU_NM,
    NULL,
    NULL,
    NULL,
    'Y',
    DSP_ORD,
    'SYSTEM',
    'SYSTEM'
FROM TB_MNU;

UPDATE TB_MNU
SET MNU_NM_CD = MNU_CD
WHERE MNU_NM_CD IS NULL;
