CREATE TABLE TB_ATTND (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Attendance primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NOT NULL COMMENT 'Company primary key reference',
    USR_ID BIGINT NOT NULL COMMENT 'User primary key reference',
    EMP_ID BIGINT NULL COMMENT 'Employee primary key reference',
    ATTND_DT DATE NOT NULL COMMENT 'Attendance date',
    CHKIN_DTM TIMESTAMP NULL COMMENT 'Check-in datetime',
    CHKOUT_DTM TIMESTAMP NULL COMMENT 'Check-out datetime',
    ATTND_STS_CD VARCHAR(20) NOT NULL COMMENT 'Attendance status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_ATTND PRIMARY KEY (ID),
    CONSTRAINT UK_TB_ATTND_TENANT_ID_USR_ID_ATTND_DT UNIQUE (TENANT_ID, USR_ID, ATTND_DT),
    CONSTRAINT FK_TB_ATTND_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_ATTND_02 FOREIGN KEY (CO_ID) REFERENCES TB_CO (ID),
    CONSTRAINT FK_TB_ATTND_03 FOREIGN KEY (USR_ID) REFERENCES TB_USR (ID),
    CONSTRAINT FK_TB_ATTND_04 FOREIGN KEY (EMP_ID) REFERENCES TB_EMP (ID)
) COMMENT='Attendance record';

CREATE TABLE TB_ATTND_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Attendance primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NOT NULL COMMENT 'Company primary key reference',
    USR_ID BIGINT NOT NULL COMMENT 'User primary key reference',
    EMP_ID BIGINT NULL COMMENT 'Employee primary key reference',
    ATTND_DT DATE NOT NULL COMMENT 'Attendance date',
    CHKIN_DTM TIMESTAMP NULL COMMENT 'Check-in datetime',
    CHKOUT_DTM TIMESTAMP NULL COMMENT 'Check-out datetime',
    ATTND_STS_CD VARCHAR(20) NOT NULL COMMENT 'Attendance status code',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_ATTND_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Attendance history';

CREATE INDEX IX_TB_ATTND_TENANT_ID ON TB_ATTND (TENANT_ID);
CREATE INDEX IX_TB_ATTND_CO_ID ON TB_ATTND (CO_ID);
CREATE INDEX IX_TB_ATTND_USR_ID ON TB_ATTND (USR_ID);
CREATE INDEX IX_TB_ATTND_EMP_ID ON TB_ATTND (EMP_ID);
CREATE INDEX IX_TB_ATTND_ATTND_DT ON TB_ATTND (ATTND_DT);
CREATE INDEX IX_TB_ATTND_HIST_ID ON TB_ATTND_HIST (ID);
CREATE INDEX IX_TB_ATTND_HIST_HIST_DTM ON TB_ATTND_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_ATTND_AI
AFTER INSERT ON TB_ATTND
FOR EACH ROW
INSERT INTO TB_ATTND_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, EMP_ID, ATTND_DT, CHKIN_DTM, CHKOUT_DTM, ATTND_STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.USR_ID, NEW.EMP_ID, NEW.ATTND_DT, NEW.CHKIN_DTM, NEW.CHKOUT_DTM, NEW.ATTND_STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ATTND_AU
AFTER UPDATE ON TB_ATTND
FOR EACH ROW
INSERT INTO TB_ATTND_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, EMP_ID, ATTND_DT, CHKIN_DTM, CHKOUT_DTM, ATTND_STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.USR_ID, NEW.EMP_ID, NEW.ATTND_DT, NEW.CHKIN_DTM, NEW.CHKOUT_DTM, NEW.ATTND_STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ATTND_BD
BEFORE DELETE ON TB_ATTND
FOR EACH ROW
INSERT INTO TB_ATTND_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, EMP_ID, ATTND_DT, CHKIN_DTM, CHKOUT_DTM, ATTND_STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.USR_ID, OLD.EMP_ID, OLD.ATTND_DT, OLD.CHKIN_DTM, OLD.CHKOUT_DTM, OLD.ATTND_STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TABLE TB_HOLI (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Holiday primary key',
    CTRY_CD VARCHAR(10) NOT NULL COMMENT 'Country code',
    REGION_CD VARCHAR(20) NOT NULL COMMENT 'Region code',
    HOLI_DT DATE NOT NULL COMMENT 'Holiday date',
    HOLI_NM_LOC VARCHAR(255) NOT NULL COMMENT 'Holiday local name',
    HOLI_NM_EN VARCHAR(255) NOT NULL COMMENT 'Holiday English name',
    GLOB_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Global holiday yes or no',
    SRC_NM VARCHAR(50) NOT NULL COMMENT 'Source name',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_HOLI PRIMARY KEY (ID),
    CONSTRAINT UK_TB_HOLI_CTRY_CD_REGION_CD_HOLI_DT UNIQUE (CTRY_CD, REGION_CD, HOLI_DT)
) COMMENT='Holiday cache';

CREATE TABLE TB_HOLI_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Holiday primary key',
    CTRY_CD VARCHAR(10) NOT NULL COMMENT 'Country code',
    REGION_CD VARCHAR(20) NOT NULL COMMENT 'Region code',
    HOLI_DT DATE NOT NULL COMMENT 'Holiday date',
    HOLI_NM_LOC VARCHAR(255) NOT NULL COMMENT 'Holiday local name',
    HOLI_NM_EN VARCHAR(255) NOT NULL COMMENT 'Holiday English name',
    GLOB_YN CHAR(1) NOT NULL COMMENT 'Global holiday yes or no',
    SRC_NM VARCHAR(50) NOT NULL COMMENT 'Source name',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_HOLI_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Holiday cache history';

CREATE INDEX IX_TB_HOLI_CTRY_CD ON TB_HOLI (CTRY_CD);
CREATE INDEX IX_TB_HOLI_REGION_CD ON TB_HOLI (REGION_CD);
CREATE INDEX IX_TB_HOLI_HOLI_DT ON TB_HOLI (HOLI_DT);
CREATE INDEX IX_TB_HOLI_HIST_ID ON TB_HOLI_HIST (ID);
CREATE INDEX IX_TB_HOLI_HIST_HIST_DTM ON TB_HOLI_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_HOLI_AI
AFTER INSERT ON TB_HOLI
FOR EACH ROW
INSERT INTO TB_HOLI_HIST (
    HIST_TP, HIST_BY, ID, CTRY_CD, REGION_CD, HOLI_DT, HOLI_NM_LOC, HOLI_NM_EN, GLOB_YN, SRC_NM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.CTRY_CD, NEW.REGION_CD, NEW.HOLI_DT, NEW.HOLI_NM_LOC, NEW.HOLI_NM_EN, NEW.GLOB_YN, NEW.SRC_NM, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_HOLI_AU
AFTER UPDATE ON TB_HOLI
FOR EACH ROW
INSERT INTO TB_HOLI_HIST (
    HIST_TP, HIST_BY, ID, CTRY_CD, REGION_CD, HOLI_DT, HOLI_NM_LOC, HOLI_NM_EN, GLOB_YN, SRC_NM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.CTRY_CD, NEW.REGION_CD, NEW.HOLI_DT, NEW.HOLI_NM_LOC, NEW.HOLI_NM_EN, NEW.GLOB_YN, NEW.SRC_NM, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_HOLI_BD
BEFORE DELETE ON TB_HOLI
FOR EACH ROW
INSERT INTO TB_HOLI_HIST (
    HIST_TP, HIST_BY, ID, CTRY_CD, REGION_CD, HOLI_DT, HOLI_NM_LOC, HOLI_NM_EN, GLOB_YN, SRC_NM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.CTRY_CD, OLD.REGION_CD, OLD.HOLI_DT, OLD.HOLI_NM_LOC, OLD.HOLI_NM_EN, OLD.GLOB_YN, OLD.SRC_NM, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);
