ALTER TABLE TB_CO
    ADD COLUMN HQ_CTRY_CD VARCHAR(10) NULL COMMENT 'Headquarters country code' AFTER REG_NO,
    ADD COLUMN HQ_REGION_CD VARCHAR(20) NULL COMMENT 'Headquarters region code' AFTER HQ_CTRY_CD,
    ADD COLUMN HQ_CITY_NM VARCHAR(255) NULL COMMENT 'Headquarters city name' AFTER HQ_REGION_CD,
    ADD COLUMN HQ_ADDR_1 VARCHAR(255) NULL COMMENT 'Headquarters address line 1' AFTER HQ_CITY_NM;

ALTER TABLE TB_CO_HIST
    ADD COLUMN HQ_CTRY_CD VARCHAR(10) NULL COMMENT 'Headquarters country code' AFTER REG_NO,
    ADD COLUMN HQ_REGION_CD VARCHAR(20) NULL COMMENT 'Headquarters region code' AFTER HQ_CTRY_CD,
    ADD COLUMN HQ_CITY_NM VARCHAR(255) NULL COMMENT 'Headquarters city name' AFTER HQ_REGION_CD,
    ADD COLUMN HQ_ADDR_1 VARCHAR(255) NULL COMMENT 'Headquarters address line 1' AFTER HQ_CITY_NM;

DROP TRIGGER IF EXISTS TR_TB_CO_AI;
DROP TRIGGER IF EXISTS TR_TB_CO_AU;
DROP TRIGGER IF EXISTS TR_TB_CO_BD;

CREATE TRIGGER TR_TB_CO_AI
AFTER INSERT ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_CD, CO_NM, REG_NO, HQ_CTRY_CD, HQ_REGION_CD, HQ_CITY_NM, HQ_ADDR_1, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_CD, NEW.CO_NM, NEW.REG_NO, NEW.HQ_CTRY_CD, NEW.HQ_REGION_CD, NEW.HQ_CITY_NM, NEW.HQ_ADDR_1, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CO_AU
AFTER UPDATE ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_CD, CO_NM, REG_NO, HQ_CTRY_CD, HQ_REGION_CD, HQ_CITY_NM, HQ_ADDR_1, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_CD, NEW.CO_NM, NEW.REG_NO, NEW.HQ_CTRY_CD, NEW.HQ_REGION_CD, NEW.HQ_CITY_NM, NEW.HQ_ADDR_1, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CO_BD
BEFORE DELETE ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_CD, CO_NM, REG_NO, HQ_CTRY_CD, HQ_REGION_CD, HQ_CITY_NM, HQ_ADDR_1, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_CD, OLD.CO_NM, OLD.REG_NO, OLD.HQ_CTRY_CD, OLD.HQ_REGION_CD, OLD.HQ_CITY_NM, OLD.HQ_ADDR_1, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TABLE TB_WORK_LOC (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Work location primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NOT NULL COMMENT 'Company primary key reference',
    WORK_LOC_CD VARCHAR(100) NOT NULL COMMENT 'Work location code',
    WORK_LOC_NM VARCHAR(255) NOT NULL COMMENT 'Work location name',
    CLNT_CO_NM VARCHAR(255) NULL COMMENT 'Host client company name',
    CTRY_CD VARCHAR(10) NOT NULL COMMENT 'Country code',
    REGION_CD VARCHAR(20) NOT NULL COMMENT 'Region code',
    CITY_NM VARCHAR(255) NULL COMMENT 'City name',
    ADDR_1 VARCHAR(255) NULL COMMENT 'Address line 1',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_WORK_LOC PRIMARY KEY (ID),
    CONSTRAINT UK_TB_WORK_LOC_TENANT_ID_CO_ID_WORK_LOC_CD UNIQUE (TENANT_ID, CO_ID, WORK_LOC_CD),
    CONSTRAINT FK_TB_WORK_LOC_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_WORK_LOC_02 FOREIGN KEY (CO_ID) REFERENCES TB_CO (ID)
) COMMENT='Work location master';

CREATE TABLE TB_WORK_LOC_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Work location primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NOT NULL COMMENT 'Company primary key reference',
    WORK_LOC_CD VARCHAR(100) NOT NULL COMMENT 'Work location code',
    WORK_LOC_NM VARCHAR(255) NOT NULL COMMENT 'Work location name',
    CLNT_CO_NM VARCHAR(255) NULL COMMENT 'Host client company name',
    CTRY_CD VARCHAR(10) NOT NULL COMMENT 'Country code',
    REGION_CD VARCHAR(20) NOT NULL COMMENT 'Region code',
    CITY_NM VARCHAR(255) NULL COMMENT 'City name',
    ADDR_1 VARCHAR(255) NULL COMMENT 'Address line 1',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_WORK_LOC_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Work location history';

CREATE INDEX IX_TB_WORK_LOC_TENANT_ID ON TB_WORK_LOC (TENANT_ID);
CREATE INDEX IX_TB_WORK_LOC_CO_ID ON TB_WORK_LOC (CO_ID);
CREATE INDEX IX_TB_WORK_LOC_CTRY_CD ON TB_WORK_LOC (CTRY_CD);
CREATE INDEX IX_TB_WORK_LOC_REGION_CD ON TB_WORK_LOC (REGION_CD);
CREATE INDEX IX_TB_WORK_LOC_HIST_ID ON TB_WORK_LOC_HIST (ID);
CREATE INDEX IX_TB_WORK_LOC_HIST_HIST_DTM ON TB_WORK_LOC_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_WORK_LOC_AI
AFTER INSERT ON TB_WORK_LOC
FOR EACH ROW
INSERT INTO TB_WORK_LOC_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, WORK_LOC_CD, WORK_LOC_NM, CLNT_CO_NM, CTRY_CD, REGION_CD, CITY_NM, ADDR_1, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.WORK_LOC_CD, NEW.WORK_LOC_NM, NEW.CLNT_CO_NM, NEW.CTRY_CD, NEW.REGION_CD, NEW.CITY_NM, NEW.ADDR_1, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_WORK_LOC_AU
AFTER UPDATE ON TB_WORK_LOC
FOR EACH ROW
INSERT INTO TB_WORK_LOC_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, WORK_LOC_CD, WORK_LOC_NM, CLNT_CO_NM, CTRY_CD, REGION_CD, CITY_NM, ADDR_1, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.WORK_LOC_CD, NEW.WORK_LOC_NM, NEW.CLNT_CO_NM, NEW.CTRY_CD, NEW.REGION_CD, NEW.CITY_NM, NEW.ADDR_1, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_WORK_LOC_BD
BEFORE DELETE ON TB_WORK_LOC
FOR EACH ROW
INSERT INTO TB_WORK_LOC_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, WORK_LOC_CD, WORK_LOC_NM, CLNT_CO_NM, CTRY_CD, REGION_CD, CITY_NM, ADDR_1, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.WORK_LOC_CD, OLD.WORK_LOC_NM, OLD.CLNT_CO_NM, OLD.CTRY_CD, OLD.REGION_CD, OLD.CITY_NM, OLD.ADDR_1, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

ALTER TABLE TB_EMP
    ADD COLUMN WORK_LOC_ID BIGINT NULL COMMENT 'Work location primary key reference' AFTER DEPT_ID,
    ADD CONSTRAINT FK_TB_EMP_06 FOREIGN KEY (WORK_LOC_ID) REFERENCES TB_WORK_LOC (ID);

ALTER TABLE TB_EMP_HIST
    ADD COLUMN WORK_LOC_ID BIGINT NULL COMMENT 'Work location primary key reference' AFTER DEPT_ID;

CREATE INDEX IX_TB_EMP_WORK_LOC_ID ON TB_EMP (WORK_LOC_ID);

DROP TRIGGER IF EXISTS TR_TB_EMP_AI;
DROP TRIGGER IF EXISTS TR_TB_EMP_AU;
DROP TRIGGER IF EXISTS TR_TB_EMP_BD;

CREATE TRIGGER TR_TB_EMP_AI
AFTER INSERT ON TB_EMP
FOR EACH ROW
INSERT INTO TB_EMP_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, DEPT_ID, WORK_LOC_ID, MGR_EMP_ID, EMP_NO, EMP_NM, TEAM_ROLE_CD, JOB_TTL_NM, HIRE_DT, RETR_DT, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.USR_ID, NEW.DEPT_ID, NEW.WORK_LOC_ID, NEW.MGR_EMP_ID, NEW.EMP_NO, NEW.EMP_NM, NEW.TEAM_ROLE_CD, NEW.JOB_TTL_NM, NEW.HIRE_DT, NEW.RETR_DT, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_EMP_AU
AFTER UPDATE ON TB_EMP
FOR EACH ROW
INSERT INTO TB_EMP_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, DEPT_ID, WORK_LOC_ID, MGR_EMP_ID, EMP_NO, EMP_NM, TEAM_ROLE_CD, JOB_TTL_NM, HIRE_DT, RETR_DT, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.USR_ID, NEW.DEPT_ID, NEW.WORK_LOC_ID, NEW.MGR_EMP_ID, NEW.EMP_NO, NEW.EMP_NM, NEW.TEAM_ROLE_CD, NEW.JOB_TTL_NM, NEW.HIRE_DT, NEW.RETR_DT, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_EMP_BD
BEFORE DELETE ON TB_EMP
FOR EACH ROW
INSERT INTO TB_EMP_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, DEPT_ID, WORK_LOC_ID, MGR_EMP_ID, EMP_NO, EMP_NM, TEAM_ROLE_CD, JOB_TTL_NM, HIRE_DT, RETR_DT, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.USR_ID, OLD.DEPT_ID, OLD.WORK_LOC_ID, OLD.MGR_EMP_ID, OLD.EMP_NO, OLD.EMP_NM, OLD.TEAM_ROLE_CD, OLD.JOB_TTL_NM, OLD.HIRE_DT, OLD.RETR_DT, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM_KO, GRP_NM_EN, GRP_NM_DE, SYS_YN, USE_YN, DSP_ORD, CRT_BY, UPD_BY)
VALUES ('DE_REGION', '독일 지역', 'Germany Region', 'Deutschland Region', 'Y', 'Y', 70, 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE
    GRP_NM_KO = VALUES(GRP_NM_KO),
    GRP_NM_EN = VALUES(GRP_NM_EN),
    GRP_NM_DE = VALUES(GRP_NM_DE),
    USE_YN = VALUES(USE_YN),
    DSP_ORD = VALUES(DSP_ORD),
    UPD_BY = 'SYSTEM';

SET @DE_REGION_GRP_ID = (SELECT ID FROM TB_CD_GRP WHERE GRP_CD = 'DE_REGION' LIMIT 1);
SET @MNU_GRP_ID = (SELECT ID FROM TB_CD_GRP WHERE GRP_CD = 'MNU_NM' LIMIT 1);
SET @CUSTOMER_HR_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_HR' LIMIT 1);

INSERT INTO TB_CD (GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, USE_YN, DSP_ORD, CRT_BY, UPD_BY) VALUES
    (@DE_REGION_GRP_ID, 'ALL', '전국', 'Nationwide', 'Bundesweit', 'Y', 0, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'BW', '바덴뷔르템베르크', 'Baden-Wurttemberg', 'Baden-Wurttemberg', 'Y', 10, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'BY', '바이에른', 'Bavaria', 'Bayern', 'Y', 20, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'BE', '베를린', 'Berlin', 'Berlin', 'Y', 30, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'BB', '브란덴부르크', 'Brandenburg', 'Brandenburg', 'Y', 40, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'HB', '브레멘', 'Bremen', 'Bremen', 'Y', 50, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'HH', '함부르크', 'Hamburg', 'Hamburg', 'Y', 60, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'HE', '헤센', 'Hesse', 'Hessen', 'Y', 70, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'MV', '메클렌부르크포어포메른', 'Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern', 'Y', 80, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'NI', '니더작센', 'Lower Saxony', 'Niedersachsen', 'Y', 90, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'NW', '노르트라인베스트팔렌', 'North Rhine-Westphalia', 'Nordrhein-Westfalen', 'Y', 100, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'RP', '라인란트팔츠', 'Rhineland-Palatinate', 'Rheinland-Pfalz', 'Y', 110, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'SL', '자를란트', 'Saarland', 'Saarland', 'Y', 120, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'SN', '작센', 'Saxony', 'Sachsen', 'Y', 130, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'ST', '작센안할트', 'Saxony-Anhalt', 'Sachsen-Anhalt', 'Y', 140, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'SH', '슐레스비히홀슈타인', 'Schleswig-Holstein', 'Schleswig-Holstein', 'Y', 150, 'SYSTEM', 'SYSTEM'),
    (@DE_REGION_GRP_ID, 'TH', '튀링겐', 'Thuringia', 'Thuringia', 'Y', 160, 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE
    CD_NM_KO = VALUES(CD_NM_KO),
    CD_NM_EN = VALUES(CD_NM_EN),
    CD_NM_DE = VALUES(CD_NM_DE),
    USE_YN = VALUES(USE_YN),
    DSP_ORD = VALUES(DSP_ORD),
    UPD_BY = 'SYSTEM';

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_CUSTOMER_WORK_LOCATIONS', 'MNU_CUSTOMER_WORK_LOCATIONS', 'Work Locations', 'CUSTOMER', @CUSTOMER_HR_ID, '/customer/hr/work-locations', NULL, 25, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_WORK_LOCATIONS');

INSERT INTO TB_CD (GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, USE_YN, DSP_ORD, CRT_BY, UPD_BY) VALUES
    (@MNU_GRP_ID, 'MNU_CUSTOMER_WORK_LOCATIONS', '근무지 관리', 'Work Locations', 'Einsatzorte', 'Y', 24, 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE
    CD_NM_KO = VALUES(CD_NM_KO),
    CD_NM_EN = VALUES(CD_NM_EN),
    CD_NM_DE = VALUES(CD_NM_DE),
    USE_YN = VALUES(USE_YN),
    DSP_ORD = VALUES(DSP_ORD),
    UPD_BY = 'SYSTEM';

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID,
       m.ID,
       'Y',
       'Y',
       'Y',
       'N',
       CASE WHEN r.ROLE_CD LIKE '%LEADER' THEN 'Y' ELSE 'N' END,
       'N',
       'SYSTEM',
       'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_CD = 'MNU_CUSTOMER_WORK_LOCATIONS'
WHERE r.ROLE_CD IN ('ROLE_CUSTOMER_ADMIN_MEMBER', 'ROLE_CUSTOMER_ADMIN_LEADER')
  AND NOT EXISTS (
      SELECT 1
      FROM TB_ROLE_MNU_AUTH a
      WHERE a.ROLE_ID = r.ID
        AND a.MNU_ID = m.ID
  );
