-- ============================================================
-- V18: TENANT_ID, CO_ID, EMP_ID → VARCHAR(20) 변환
-- ============================================================

-- TB_LEAVE_REQ: FK 제거 후 타입 변경
ALTER TABLE TB_LEAVE_REQ DROP FOREIGN KEY FK_TB_LEAVE_REQ_01;
ALTER TABLE TB_LEAVE_REQ DROP FOREIGN KEY FK_TB_LEAVE_REQ_02;
ALTER TABLE TB_LEAVE_REQ DROP FOREIGN KEY FK_TB_LEAVE_REQ_03;

ALTER TABLE TB_LEAVE_REQ MODIFY TENANT_ID VARCHAR(20) NOT NULL COMMENT 'Tenant code';
ALTER TABLE TB_LEAVE_REQ MODIFY CO_ID     VARCHAR(20) NOT NULL COMMENT 'Company code';
ALTER TABLE TB_LEAVE_REQ MODIFY EMP_ID    VARCHAR(20) NOT NULL COMMENT 'Applicant employee code';

-- TB_APRV_LINE: FK 제거 후 타입 변경
ALTER TABLE TB_APRV_LINE DROP FOREIGN KEY FK_TB_APRV_LINE_01;
ALTER TABLE TB_APRV_LINE DROP FOREIGN KEY FK_TB_APRV_LINE_02;
ALTER TABLE TB_APRV_LINE DROP FOREIGN KEY FK_TB_APRV_LINE_03;

ALTER TABLE TB_APRV_LINE MODIFY TENANT_ID VARCHAR(20) NOT NULL COMMENT 'Tenant code';
ALTER TABLE TB_APRV_LINE MODIFY CO_ID     VARCHAR(20) NOT NULL COMMENT 'Company code';
ALTER TABLE TB_APRV_LINE MODIFY EMP_ID    VARCHAR(20) NOT NULL COMMENT 'Approver or cc employee code';
