CREATE TABLE TB_TENANT (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Tenant primary key',
    TENANT_CD VARCHAR(100) NOT NULL COMMENT 'Tenant code',
    TENANT_NM VARCHAR(255) NOT NULL COMMENT 'Tenant name',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_TENANT PRIMARY KEY (ID),
    CONSTRAINT UK_TB_TENANT_TENANT_CD UNIQUE (TENANT_CD)
) COMMENT='Tenant master';

CREATE TABLE TB_CO (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Company primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_NM VARCHAR(255) NOT NULL COMMENT 'Company name',
    REG_NO VARCHAR(100) NULL COMMENT 'Registration number',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_CO PRIMARY KEY (ID),
    CONSTRAINT FK_TB_CO_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID)
) COMMENT='Company master';

CREATE TABLE TB_USR (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'User primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NULL COMMENT 'Company primary key reference',
    EML VARCHAR(255) NOT NULL COMMENT 'User email',
    PWD_HASH VARCHAR(255) NOT NULL COMMENT 'Password hash value',
    DSP_NM VARCHAR(255) NOT NULL COMMENT 'Display name',
    LOCL_CD VARCHAR(10) NOT NULL COMMENT 'Locale code',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_USR PRIMARY KEY (ID),
    CONSTRAINT UK_TB_USR_EML UNIQUE (EML),
    CONSTRAINT FK_TB_USR_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_USR_02 FOREIGN KEY (CO_ID) REFERENCES TB_CO (ID)
) COMMENT='User master';

CREATE TABLE TB_ROLE (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Role primary key',
    ROLE_CD VARCHAR(100) NOT NULL COMMENT 'Role code',
    ROLE_NM VARCHAR(255) NOT NULL COMMENT 'Role name',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_ROLE PRIMARY KEY (ID),
    CONSTRAINT UK_TB_ROLE_ROLE_CD UNIQUE (ROLE_CD)
) COMMENT='Role master';

CREATE TABLE TB_USR_ROLE (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'User role mapping primary key',
    USR_ID BIGINT NOT NULL COMMENT 'User primary key reference',
    ROLE_ID BIGINT NOT NULL COMMENT 'Role primary key reference',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_USR_ROLE PRIMARY KEY (ID),
    CONSTRAINT UK_TB_USR_ROLE_USR_ID_ROLE_ID UNIQUE (USR_ID, ROLE_ID),
    CONSTRAINT FK_TB_USR_ROLE_01 FOREIGN KEY (USR_ID) REFERENCES TB_USR (ID),
    CONSTRAINT FK_TB_USR_ROLE_02 FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE (ID)
) COMMENT='User role mapping';

CREATE TABLE TB_CHG_HIST (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Change history primary key',
    TBL_NM VARCHAR(100) NOT NULL COMMENT 'Changed table name',
    ENT_NM VARCHAR(100) NOT NULL COMMENT 'Changed entity name',
    ROW_ID BIGINT NOT NULL COMMENT 'Changed row primary key',
    CHG_TP VARCHAR(20) NOT NULL COMMENT 'Change type',
    TENANT_ID BIGINT NULL COMMENT 'Tenant primary key reference',
    SNAP_JSON LONGTEXT NOT NULL COMMENT 'Serialized snapshot',
    CHG_BY VARCHAR(100) NOT NULL COMMENT 'Change actor',
    CHG_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Change datetime',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_CHG_HIST PRIMARY KEY (ID)
) COMMENT='Change history';

CREATE INDEX IX_TB_CO_TENANT_ID ON TB_CO (TENANT_ID);
CREATE INDEX IX_TB_USR_TENANT_ID ON TB_USR (TENANT_ID);
CREATE INDEX IX_TB_USR_CO_ID ON TB_USR (CO_ID);
CREATE INDEX IX_TB_USR_ROLE_USR_ID ON TB_USR_ROLE (USR_ID);
CREATE INDEX IX_TB_USR_ROLE_ROLE_ID ON TB_USR_ROLE (ROLE_ID);
CREATE INDEX IX_TB_CHG_HIST_ENT_NM_ROW_ID ON TB_CHG_HIST (ENT_NM, ROW_ID);
CREATE INDEX IX_TB_CHG_HIST_TENANT_ID ON TB_CHG_HIST (TENANT_ID);
CREATE INDEX IX_TB_CHG_HIST_CHG_DTM ON TB_CHG_HIST (CHG_DTM);
