CREATE TABLE TB_TENANT (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Tenant primary key',
    TENANT_CD VARCHAR(100) NOT NULL COMMENT 'Tenant code',
    TENANT_NM VARCHAR(255) NOT NULL COMMENT 'Tenant name',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_TENANT PRIMARY KEY (ID),
    CONSTRAINT UK_TB_TENANT_TENANT_CD UNIQUE (TENANT_CD)
) COMMENT='Tenant master';

CREATE TABLE TB_CO (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Company primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_NM VARCHAR(255) NOT NULL COMMENT 'Company name',
    REG_NO VARCHAR(100) NULL COMMENT 'Registration number',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_CO PRIMARY KEY (ID),
    CONSTRAINT FK_TB_CO_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID)
) COMMENT='Company master';

CREATE TABLE TB_USR (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'User primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NULL COMMENT 'Company primary key reference',
    EML VARCHAR(255) NOT NULL COMMENT 'User email',
    PWD_HASH VARCHAR(255) NOT NULL COMMENT 'Password hash value',
    DSP_NM VARCHAR(255) NOT NULL COMMENT 'Display name',
    LOCL_CD VARCHAR(10) NOT NULL COMMENT 'Locale code',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_USR PRIMARY KEY (ID),
    CONSTRAINT UK_TB_USR_EML UNIQUE (EML),
    CONSTRAINT FK_TB_USR_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_USR_02 FOREIGN KEY (CO_ID) REFERENCES TB_CO (ID)
) COMMENT='User master';

CREATE TABLE TB_ROLE (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Role primary key',
    ROLE_CD VARCHAR(100) NOT NULL COMMENT 'Role code',
    ROLE_NM VARCHAR(255) NOT NULL COMMENT 'Role name',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_ROLE PRIMARY KEY (ID),
    CONSTRAINT UK_TB_ROLE_ROLE_CD UNIQUE (ROLE_CD)
) COMMENT='Role master';

CREATE TABLE TB_USR_ROLE (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'User role mapping primary key',
    USR_ID BIGINT NOT NULL COMMENT 'User primary key reference',
    ROLE_ID BIGINT NOT NULL COMMENT 'Role primary key reference',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_USR_ROLE PRIMARY KEY (ID),
    CONSTRAINT UK_TB_USR_ROLE_USR_ID_ROLE_ID UNIQUE (USR_ID, ROLE_ID),
    CONSTRAINT FK_TB_USR_ROLE_01 FOREIGN KEY (USR_ID) REFERENCES TB_USR (ID),
    CONSTRAINT FK_TB_USR_ROLE_02 FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE (ID)
) COMMENT='User role mapping';

CREATE TABLE TB_TENANT_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Tenant primary key',
    TENANT_CD VARCHAR(100) NOT NULL COMMENT 'Tenant code',
    TENANT_NM VARCHAR(255) NOT NULL COMMENT 'Tenant name',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_TENANT_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Tenant history';

CREATE TABLE TB_CO_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Company primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_NM VARCHAR(255) NOT NULL COMMENT 'Company name',
    REG_NO VARCHAR(100) NULL COMMENT 'Registration number',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_CO_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Company history';

CREATE TABLE TB_USR_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'User primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NULL COMMENT 'Company primary key reference',
    EML VARCHAR(255) NOT NULL COMMENT 'User email',
    PWD_HASH VARCHAR(255) NOT NULL COMMENT 'Password hash value',
    DSP_NM VARCHAR(255) NOT NULL COMMENT 'Display name',
    LOCL_CD VARCHAR(10) NOT NULL COMMENT 'Locale code',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_USR_HIST PRIMARY KEY (HIST_ID)
) COMMENT='User history';

CREATE TABLE TB_ROLE_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Role primary key',
    ROLE_CD VARCHAR(100) NOT NULL COMMENT 'Role code',
    ROLE_NM VARCHAR(255) NOT NULL COMMENT 'Role name',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_ROLE_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Role history';

CREATE TABLE TB_USR_ROLE_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'User role mapping primary key',
    USR_ID BIGINT NOT NULL COMMENT 'User primary key reference',
    ROLE_ID BIGINT NOT NULL COMMENT 'Role primary key reference',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_USR_ROLE_HIST PRIMARY KEY (HIST_ID)
) COMMENT='User role history';

CREATE INDEX IX_TB_CO_TENANT_ID ON TB_CO (TENANT_ID);
CREATE INDEX IX_TB_USR_TENANT_ID ON TB_USR (TENANT_ID);
CREATE INDEX IX_TB_USR_CO_ID ON TB_USR (CO_ID);
CREATE INDEX IX_TB_USR_ROLE_USR_ID ON TB_USR_ROLE (USR_ID);
CREATE INDEX IX_TB_USR_ROLE_ROLE_ID ON TB_USR_ROLE (ROLE_ID);
CREATE INDEX IX_TB_TENANT_HIST_ID ON TB_TENANT_HIST (ID);
CREATE INDEX IX_TB_TENANT_HIST_HIST_DTM ON TB_TENANT_HIST (HIST_DTM);
CREATE INDEX IX_TB_CO_HIST_ID ON TB_CO_HIST (ID);
CREATE INDEX IX_TB_CO_HIST_HIST_DTM ON TB_CO_HIST (HIST_DTM);
CREATE INDEX IX_TB_USR_HIST_ID ON TB_USR_HIST (ID);
CREATE INDEX IX_TB_USR_HIST_HIST_DTM ON TB_USR_HIST (HIST_DTM);
CREATE INDEX IX_TB_ROLE_HIST_ID ON TB_ROLE_HIST (ID);
CREATE INDEX IX_TB_ROLE_HIST_HIST_DTM ON TB_ROLE_HIST (HIST_DTM);
CREATE INDEX IX_TB_USR_ROLE_HIST_ID ON TB_USR_ROLE_HIST (ID);
CREATE INDEX IX_TB_USR_ROLE_HIST_HIST_DTM ON TB_USR_ROLE_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_TENANT_AI
AFTER INSERT ON TB_TENANT
FOR EACH ROW
INSERT INTO TB_TENANT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_CD, TENANT_NM, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_CD, NEW.TENANT_NM, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_TENANT_AU
AFTER UPDATE ON TB_TENANT
FOR EACH ROW
INSERT INTO TB_TENANT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_CD, TENANT_NM, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_CD, NEW.TENANT_NM, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_TENANT_BD
BEFORE DELETE ON TB_TENANT
FOR EACH ROW
INSERT INTO TB_TENANT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_CD, TENANT_NM, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_CD, OLD.TENANT_NM, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TRIGGER TR_TB_CO_AI
AFTER INSERT ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_NM, REG_NO, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_NM, NEW.REG_NO, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CO_AU
AFTER UPDATE ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_NM, REG_NO, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_NM, NEW.REG_NO, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CO_BD
BEFORE DELETE ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_NM, REG_NO, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_NM, OLD.REG_NO, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_AI
AFTER INSERT ON TB_USR
FOR EACH ROW
INSERT INTO TB_USR_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, EML, PWD_HASH, DSP_NM, LOCL_CD, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.EML, NEW.PWD_HASH, NEW.DSP_NM, NEW.LOCL_CD, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_AU
AFTER UPDATE ON TB_USR
FOR EACH ROW
INSERT INTO TB_USR_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, EML, PWD_HASH, DSP_NM, LOCL_CD, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.EML, NEW.PWD_HASH, NEW.DSP_NM, NEW.LOCL_CD, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_BD
BEFORE DELETE ON TB_USR
FOR EACH ROW
INSERT INTO TB_USR_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, EML, PWD_HASH, DSP_NM, LOCL_CD, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.EML, OLD.PWD_HASH, OLD.DSP_NM, OLD.LOCL_CD, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TRIGGER TR_TB_ROLE_AI
AFTER INSERT ON TB_ROLE
FOR EACH ROW
INSERT INTO TB_ROLE_HIST (
    HIST_TP, HIST_BY, ID, ROLE_CD, ROLE_NM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.ROLE_CD, NEW.ROLE_NM, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ROLE_AU
AFTER UPDATE ON TB_ROLE
FOR EACH ROW
INSERT INTO TB_ROLE_HIST (
    HIST_TP, HIST_BY, ID, ROLE_CD, ROLE_NM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.ROLE_CD, NEW.ROLE_NM, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ROLE_BD
BEFORE DELETE ON TB_ROLE
FOR EACH ROW
INSERT INTO TB_ROLE_HIST (
    HIST_TP, HIST_BY, ID, ROLE_CD, ROLE_NM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.ROLE_CD, OLD.ROLE_NM, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_ROLE_AI
AFTER INSERT ON TB_USR_ROLE
FOR EACH ROW
INSERT INTO TB_USR_ROLE_HIST (
    HIST_TP, HIST_BY, ID, USR_ID, ROLE_ID, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.USR_ID, NEW.ROLE_ID, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_ROLE_AU
AFTER UPDATE ON TB_USR_ROLE
FOR EACH ROW
INSERT INTO TB_USR_ROLE_HIST (
    HIST_TP, HIST_BY, ID, USR_ID, ROLE_ID, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.USR_ID, NEW.ROLE_ID, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_ROLE_BD
BEFORE DELETE ON TB_USR_ROLE
FOR EACH ROW
INSERT INTO TB_USR_ROLE_HIST (
    HIST_TP, HIST_BY, ID, USR_ID, ROLE_ID, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.USR_ID, OLD.ROLE_ID, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);
