-- ============================================================
-- V20: 휴가 정책 + 직원 부여 도메인
-- ============================================================
-- 1) TB_LEAVE_CO_POLICY — 회사별 휴가 정책 (1 row per company)
--    customer admin이 화면에서 수정. 부여 시점/방식/이월 정책/만료 처리 등 보관
-- 2) TB_LEAVE_GRANT — 직원별 연도별 휴가 부여 내역
--    매년 자동 또는 수동으로 row 생성. 이월 캐시 포함.
-- 3) DEFAULT 시드 — Sinwoo (tenantId=1, coId=1) 회사에 기본 정책 + ggamgang 2026년 부여
-- ============================================================

-- ── 1. TB_LEAVE_CO_POLICY ───────────────────────────────────
CREATE TABLE TB_LEAVE_CO_POLICY (
    ID                    BIGINT       NOT NULL AUTO_INCREMENT,
    TENANT_ID             VARCHAR(20)  NOT NULL COMMENT 'Tenant code',
    CO_ID                 VARCHAR(20)  NOT NULL COMMENT 'Company code',

    -- 부여 시점
    GRANT_TIMING_CD       VARCHAR(20)  NOT NULL DEFAULT 'FIXED_YEARLY'
        COMMENT 'FIXED_YEARLY(매년 1/1) | ANNIVERSARY(입사기념일) | FISCAL_YEAR(회계년도)',
    FISCAL_START_MM       TINYINT      NOT NULL DEFAULT 1
        COMMENT 'Fiscal year start month (1-12), used only when GRANT_TIMING_CD=FISCAL_YEAR',

    -- 부여 일수 결정
    GRANT_TYPE_CD         VARCHAR(20)  NOT NULL DEFAULT 'FLAT'
        COMMENT 'FLAT(단일값) | TENURE(근속년수별) | MANUAL(직원별 수동)',
    FLAT_DAYS             DECIMAL(4,1) NOT NULL DEFAULT 20.0
        COMMENT 'Default annual grant days when GRANT_TYPE_CD=FLAT',

    -- 이월 정책
    CARRYOVER_ENABLED_YN  CHAR(1)      NOT NULL DEFAULT 'Y' COMMENT 'Y=이월 허용, N=이월 안함',
    CARRYOVER_MAX_DAYS    DECIMAL(4,1) NULL
        COMMENT 'Max days to carry over. NULL = unlimited (잔여 전부)',
    CARRYOVER_EXPIRE_MM   TINYINT      NOT NULL DEFAULT 3
        COMMENT 'Carryover expiry month (1-12), default 3 (March)',
    CARRYOVER_EXPIRE_DD   TINYINT      NOT NULL DEFAULT 31
        COMMENT 'Carryover expiry day (1-31), default 31',

    -- 만료 처리
    EXPIRE_ACTION_CD      VARCHAR(20)  NOT NULL DEFAULT 'AUTO_ZERO'
        COMMENT 'AUTO_ZERO(기한 경과 시 자동 0) | NOTIFY_ONLY(알림만)',

    DEL_YN                CHAR(1)      NOT NULL DEFAULT 'N',
    CRT_BY                VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    CRT_DTM               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY                VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    UPD_DTM               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_LEAVE_CO_POLICY PRIMARY KEY (ID),
    CONSTRAINT UK_TB_LEAVE_CO_POLICY_TENANT_CO UNIQUE (TENANT_ID, CO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IX_TB_LEAVE_CO_POLICY_TENANT_ID ON TB_LEAVE_CO_POLICY (TENANT_ID);
CREATE INDEX IX_TB_LEAVE_CO_POLICY_CO_ID     ON TB_LEAVE_CO_POLICY (CO_ID);

-- 변경 이력 테이블
CREATE TABLE TB_LEAVE_CO_POLICY_HIST (
    HIST_ID               BIGINT       NOT NULL AUTO_INCREMENT,
    HIST_TP               CHAR(1)      NOT NULL,
    HIST_BY               VARCHAR(100) NOT NULL,
    HIST_DTM              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID                    BIGINT       NOT NULL,
    TENANT_ID             VARCHAR(20)  NOT NULL,
    CO_ID                 VARCHAR(20)  NOT NULL,
    GRANT_TIMING_CD       VARCHAR(20)  NOT NULL,
    FISCAL_START_MM       TINYINT      NOT NULL,
    GRANT_TYPE_CD         VARCHAR(20)  NOT NULL,
    FLAT_DAYS             DECIMAL(4,1) NOT NULL,
    CARRYOVER_ENABLED_YN  CHAR(1)      NOT NULL,
    CARRYOVER_MAX_DAYS    DECIMAL(4,1) NULL,
    CARRYOVER_EXPIRE_MM   TINYINT      NOT NULL,
    CARRYOVER_EXPIRE_DD   TINYINT      NOT NULL,
    EXPIRE_ACTION_CD      VARCHAR(20)  NOT NULL,
    DEL_YN                CHAR(1)      NOT NULL,
    CRT_BY                VARCHAR(100) NOT NULL,
    CRT_DTM               TIMESTAMP    NOT NULL,
    UPD_BY                VARCHAR(100) NOT NULL,
    UPD_DTM               TIMESTAMP    NOT NULL,
    CONSTRAINT PK_TB_LEAVE_CO_POLICY_HIST PRIMARY KEY (HIST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IX_TB_LEAVE_CO_POLICY_HIST_ID ON TB_LEAVE_CO_POLICY_HIST (ID);

-- ── 2. TB_LEAVE_GRANT ───────────────────────────────────────
CREATE TABLE TB_LEAVE_GRANT (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    TENANT_ID       VARCHAR(20)  NOT NULL COMMENT 'Tenant code',
    CO_ID           VARCHAR(20)  NOT NULL COMMENT 'Company code',
    EMP_ID          VARCHAR(20)  NOT NULL COMMENT 'Employee code (TB_EMP.EMP_NO)',
    GRANT_YR        SMALLINT     NOT NULL COMMENT 'Grant year (YYYY)',

    GRANT_DAYS      DECIMAL(4,1) NOT NULL COMMENT 'Days granted at start of year',
    CARRYOVER_DAYS  DECIMAL(4,1) NOT NULL DEFAULT 0
        COMMENT 'Days carried over from previous year (after expiry handling)',
    USED_DAYS       DECIMAL(4,1) NOT NULL DEFAULT 0
        COMMENT 'Cache: days used this year (computed from TB_LEAVE_REQ)',
    EXPIRED_DAYS    DECIMAL(4,1) NOT NULL DEFAULT 0
        COMMENT 'Cache: carryover days that expired without being used',

    REMARK          VARCHAR(500) NULL COMMENT 'Admin memo (manual adjustments etc.)',

    DEL_YN          CHAR(1)      NOT NULL DEFAULT 'N',
    CRT_BY          VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    CRT_DTM         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY          VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    UPD_DTM         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_LEAVE_GRANT PRIMARY KEY (ID),
    CONSTRAINT UK_TB_LEAVE_GRANT_TENANT_CO_EMP_YR UNIQUE (TENANT_ID, CO_ID, EMP_ID, GRANT_YR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IX_TB_LEAVE_GRANT_TENANT_ID ON TB_LEAVE_GRANT (TENANT_ID);
CREATE INDEX IX_TB_LEAVE_GRANT_CO_ID     ON TB_LEAVE_GRANT (CO_ID);
CREATE INDEX IX_TB_LEAVE_GRANT_EMP_ID    ON TB_LEAVE_GRANT (EMP_ID);
CREATE INDEX IX_TB_LEAVE_GRANT_GRANT_YR  ON TB_LEAVE_GRANT (GRANT_YR);

CREATE TABLE TB_LEAVE_GRANT_HIST (
    HIST_ID         BIGINT       NOT NULL AUTO_INCREMENT,
    HIST_TP         CHAR(1)      NOT NULL,
    HIST_BY         VARCHAR(100) NOT NULL,
    HIST_DTM        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID              BIGINT       NOT NULL,
    TENANT_ID       VARCHAR(20)  NOT NULL,
    CO_ID           VARCHAR(20)  NOT NULL,
    EMP_ID          VARCHAR(20)  NOT NULL,
    GRANT_YR        SMALLINT     NOT NULL,
    GRANT_DAYS      DECIMAL(4,1) NOT NULL,
    CARRYOVER_DAYS  DECIMAL(4,1) NOT NULL,
    USED_DAYS       DECIMAL(4,1) NOT NULL,
    EXPIRED_DAYS    DECIMAL(4,1) NOT NULL,
    REMARK          VARCHAR(500) NULL,
    DEL_YN          CHAR(1)      NOT NULL,
    CRT_BY          VARCHAR(100) NOT NULL,
    CRT_DTM         TIMESTAMP    NOT NULL,
    UPD_BY          VARCHAR(100) NOT NULL,
    UPD_DTM         TIMESTAMP    NOT NULL,
    CONSTRAINT PK_TB_LEAVE_GRANT_HIST PRIMARY KEY (HIST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IX_TB_LEAVE_GRANT_HIST_ID ON TB_LEAVE_GRANT_HIST (ID);

-- ── 3. DEFAULT 시드 ─────────────────────────────────────────
-- Sinwoo 회사 기본 정책 (FLAT 20일 / 이월 전부 / 3월 31일 만료 / AUTO_ZERO)
INSERT INTO TB_LEAVE_CO_POLICY (
    TENANT_ID, CO_ID,
    GRANT_TIMING_CD, FISCAL_START_MM,
    GRANT_TYPE_CD, FLAT_DAYS,
    CARRYOVER_ENABLED_YN, CARRYOVER_MAX_DAYS, CARRYOVER_EXPIRE_MM, CARRYOVER_EXPIRE_DD,
    EXPIRE_ACTION_CD,
    CRT_BY, UPD_BY
) VALUES (
    'SINWOO', 'SINWOO',
    'FIXED_YEARLY', 1,
    'FLAT', 20.0,
    'Y', NULL, 3, 31,
    'AUTO_ZERO',
    'SYSTEM', 'SYSTEM'
);

-- ggamgang (EMP001) 2026년 휴가 부여 — 20일 + 전년도 이월 5일
INSERT INTO TB_LEAVE_GRANT (
    TENANT_ID, CO_ID, EMP_ID, GRANT_YR,
    GRANT_DAYS, CARRYOVER_DAYS, USED_DAYS, EXPIRED_DAYS,
    REMARK,
    CRT_BY, UPD_BY
) VALUES (
    'SINWOO', 'SINWOO', 'EMP001', 2026,
    20.0, 5.0, 0, 0,
    'Initial seed grant for 2026',
    'SYSTEM', 'SYSTEM'
);

-- ── 4. 변경 이력 트리거 ──────────────────────────────────────
DELIMITER //

CREATE TRIGGER TR_TB_LEAVE_CO_POLICY_AI
AFTER INSERT ON TB_LEAVE_CO_POLICY
FOR EACH ROW
BEGIN
    INSERT INTO TB_LEAVE_CO_POLICY_HIST (
        HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID,
        GRANT_TIMING_CD, FISCAL_START_MM, GRANT_TYPE_CD, FLAT_DAYS,
        CARRYOVER_ENABLED_YN, CARRYOVER_MAX_DAYS, CARRYOVER_EXPIRE_MM, CARRYOVER_EXPIRE_DD,
        EXPIRE_ACTION_CD, DEL_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
    ) VALUES (
        'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID,
        NEW.GRANT_TIMING_CD, NEW.FISCAL_START_MM, NEW.GRANT_TYPE_CD, NEW.FLAT_DAYS,
        NEW.CARRYOVER_ENABLED_YN, NEW.CARRYOVER_MAX_DAYS, NEW.CARRYOVER_EXPIRE_MM, NEW.CARRYOVER_EXPIRE_DD,
        NEW.EXPIRE_ACTION_CD, NEW.DEL_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
    );
END //

CREATE TRIGGER TR_TB_LEAVE_CO_POLICY_AU
AFTER UPDATE ON TB_LEAVE_CO_POLICY
FOR EACH ROW
BEGIN
    INSERT INTO TB_LEAVE_CO_POLICY_HIST (
        HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID,
        GRANT_TIMING_CD, FISCAL_START_MM, GRANT_TYPE_CD, FLAT_DAYS,
        CARRYOVER_ENABLED_YN, CARRYOVER_MAX_DAYS, CARRYOVER_EXPIRE_MM, CARRYOVER_EXPIRE_DD,
        EXPIRE_ACTION_CD, DEL_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
    ) VALUES (
        'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID,
        NEW.GRANT_TIMING_CD, NEW.FISCAL_START_MM, NEW.GRANT_TYPE_CD, NEW.FLAT_DAYS,
        NEW.CARRYOVER_ENABLED_YN, NEW.CARRYOVER_MAX_DAYS, NEW.CARRYOVER_EXPIRE_MM, NEW.CARRYOVER_EXPIRE_DD,
        NEW.EXPIRE_ACTION_CD, NEW.DEL_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
    );
END //

CREATE TRIGGER TR_TB_LEAVE_GRANT_AI
AFTER INSERT ON TB_LEAVE_GRANT
FOR EACH ROW
BEGIN
    INSERT INTO TB_LEAVE_GRANT_HIST (
        HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, EMP_ID, GRANT_YR,
        GRANT_DAYS, CARRYOVER_DAYS, USED_DAYS, EXPIRED_DAYS, REMARK,
        DEL_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
    ) VALUES (
        'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.EMP_ID, NEW.GRANT_YR,
        NEW.GRANT_DAYS, NEW.CARRYOVER_DAYS, NEW.USED_DAYS, NEW.EXPIRED_DAYS, NEW.REMARK,
        NEW.DEL_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
    );
END //

CREATE TRIGGER TR_TB_LEAVE_GRANT_AU
AFTER UPDATE ON TB_LEAVE_GRANT
FOR EACH ROW
BEGIN
    INSERT INTO TB_LEAVE_GRANT_HIST (
        HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, EMP_ID, GRANT_YR,
        GRANT_DAYS, CARRYOVER_DAYS, USED_DAYS, EXPIRED_DAYS, REMARK,
        DEL_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
    ) VALUES (
        'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.EMP_ID, NEW.GRANT_YR,
        NEW.GRANT_DAYS, NEW.CARRYOVER_DAYS, NEW.USED_DAYS, NEW.EXPIRED_DAYS, NEW.REMARK,
        NEW.DEL_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
    );
END //

DELIMITER ;
