-- Extends the TO-BE access log so AS-IS tb_log_history can be imported
-- without keeping a separate legacy log table.

ALTER TABLE TB_ACCESS_LOG
    ADD COLUMN LEGACY_LOG_SEQ BIGINT NULL COMMENT 'Legacy tb_log_history sequence' AFTER ERR_MSG,
    ADD COLUMN LEGACY_CO_ID VARCHAR(20) NULL COMMENT 'Legacy company id from tb_log_history' AFTER LEGACY_LOG_SEQ,
    ADD COLUMN LEGACY_USER_AUTH VARCHAR(20) NULL COMMENT 'Legacy user auth from tb_log_history' AFTER LEGACY_CO_ID,
    ADD COLUMN LEGACY_END_POINT VARCHAR(500) NULL COMMENT 'Legacy endpoint bean string from tb_log_history' AFTER LEGACY_USER_AUTH,
    ADD COLUMN LEGACY_REASON_CNTS LONGTEXT NULL COMMENT 'Legacy reason contents from tb_log_history' AFTER LEGACY_END_POINT;

CREATE UNIQUE INDEX UK_TB_ACCESS_LOG_LEGACY_LOG_SEQ ON TB_ACCESS_LOG (LEGACY_LOG_SEQ);
CREATE INDEX IX_TB_ACCESS_LOG_LEGACY_CO_ID ON TB_ACCESS_LOG (LEGACY_CO_ID);
CREATE INDEX IX_TB_ACCESS_LOG_LEGACY_USER_AUTH ON TB_ACCESS_LOG (LEGACY_USER_AUTH);
