-- Adds TO-BE business workflow surface based on the AS-IS 업무 메뉴와 업무 테이블.
--
-- Scope note:
-- - Do not change SaaS core/common structures.
-- - Add only business-facing structures/menu entries needed to expose the AS-IS 업무단.
-- - Keep AS-IS duplicate menu codes out of TO-BE by using explicit business menu codes.

CREATE TABLE TB_WORK_TIME_ENTRY (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Work time entry primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NOT NULL COMMENT 'Company primary key reference',
    DEPT_ID BIGINT NULL COMMENT 'Department primary key reference',
    EMP_ID BIGINT NULL COMMENT 'Employee primary key reference',
    USR_ID BIGINT NULL COMMENT 'User primary key reference',
    LEGACY_START_DW_SEQ BIGINT NULL COMMENT 'Legacy start tb_daily_work_time sequence',
    LEGACY_END_DW_SEQ BIGINT NULL COMMENT 'Legacy end tb_daily_work_time sequence',
    LEGACY_DEPT_ID VARCHAR(20) NULL COMMENT 'Legacy department id',
    LEGACY_EMP_ID VARCHAR(50) NULL COMMENT 'Legacy employee id',
    WORK_DT DATE NOT NULL COMMENT 'Work date',
    START_TM TIME NULL COMMENT 'Work start time',
    END_TM TIME NULL COMMENT 'Work end time',
    SRC_CD VARCHAR(20) NOT NULL DEFAULT 'MANUAL' COMMENT 'Source code',
    APRV_STS_CD VARCHAR(20) NOT NULL DEFAULT 'CF' COMMENT 'Approval status code',
    NOTE LONGTEXT NULL COMMENT 'Note',
    STS_CD VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_WORK_TIME_ENTRY PRIMARY KEY (ID),
    CONSTRAINT UK_TB_WORK_TIME_ENTRY_01 UNIQUE (TENANT_ID, CO_ID, EMP_ID, WORK_DT),
    CONSTRAINT UK_TB_WORK_TIME_ENTRY_LEGACY_START UNIQUE (TENANT_ID, LEGACY_START_DW_SEQ),
    CONSTRAINT UK_TB_WORK_TIME_ENTRY_LEGACY_END UNIQUE (TENANT_ID, LEGACY_END_DW_SEQ),
    CONSTRAINT FK_TB_WORK_TIME_ENTRY_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_WORK_TIME_ENTRY_02 FOREIGN KEY (CO_ID) REFERENCES TB_CO (ID),
    CONSTRAINT FK_TB_WORK_TIME_ENTRY_03 FOREIGN KEY (DEPT_ID) REFERENCES TB_DEPT (ID),
    CONSTRAINT FK_TB_WORK_TIME_ENTRY_04 FOREIGN KEY (EMP_ID) REFERENCES TB_EMP (ID),
    CONSTRAINT FK_TB_WORK_TIME_ENTRY_05 FOREIGN KEY (USR_ID) REFERENCES TB_USR (ID)
) COMMENT='Work time entry normalized from AS-IS tb_daily_work_time start/end rows';

CREATE INDEX IX_TB_WORK_TIME_ENTRY_PERIOD ON TB_WORK_TIME_ENTRY (TENANT_ID, CO_ID, WORK_DT);
CREATE INDEX IX_TB_WORK_TIME_ENTRY_EMP ON TB_WORK_TIME_ENTRY (TENANT_ID, EMP_ID, WORK_DT);
CREATE INDEX IX_TB_WORK_TIME_ENTRY_STS ON TB_WORK_TIME_ENTRY (TENANT_ID, CO_ID, APRV_STS_CD);

SET @MNU_GRP_ID = (SELECT ID FROM TB_CD_GRP WHERE GRP_CD = 'MNU_NM' LIMIT 1);
SET @CUSTOMER_FIN_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_FIN' LIMIT 1);

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_REQUESTS', 'MNU_BIZ_REQUESTS', 'Requests', 'CUSTOMER', NULL, '/business/requests', 'clipboard-list', 21, NULL, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_REQUESTS');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MY_CLAIMS', 'MNU_BIZ_MY_CLAIMS', 'My Claims', 'CUSTOMER', NULL, '/business/my-claims', 'receipt-text', 22, NULL, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MY_CLAIMS');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_REPORTS', 'MNU_BIZ_REPORTS', 'Reports', 'CUSTOMER', NULL, '/business/reports', 'bar-chart-3', 23, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_REPORTS');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MASTER', 'MNU_BIZ_MASTER', 'Business Setup', 'CUSTOMER', NULL, '/business/setup', 'settings', 60, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MASTER');

SET @BIZ_REQUESTS_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_REQUESTS' LIMIT 1);
SET @BIZ_CLAIMS_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MY_CLAIMS' LIMIT 1);
SET @BIZ_REPORTS_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_REPORTS' LIMIT 1);
SET @BIZ_MASTER_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MASTER' LIMIT 1);

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_REQ_WORK_TIME', 'MNU_BIZ_REQ_WORK_TIME', 'Work Time', 'CUSTOMER', @BIZ_REQUESTS_ID, '/business/requests/work-time', NULL, 10, NULL, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_REQ_WORK_TIME');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_REQ_EXPENSE', 'MNU_BIZ_REQ_EXPENSE', 'Expense', 'CUSTOMER', @BIZ_REQUESTS_ID, '/business/requests/expense', NULL, 20, NULL, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_REQ_EXPENSE');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_REQ_TRIP', 'MNU_BIZ_REQ_TRIP', 'Business Trip', 'CUSTOMER', @BIZ_REQUESTS_ID, '/business/requests/business-trip', NULL, 30, NULL, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_REQ_TRIP');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_REQ_LEAVE', 'MNU_BIZ_REQ_LEAVE', 'Vacation', 'CUSTOMER', @BIZ_REQUESTS_ID, '/business/requests/vacation', NULL, 40, NULL, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_REQ_LEAVE');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_CLAIM_EXPENSE', 'MNU_BIZ_CLAIM_EXPENSE', 'Expense Claims', 'CUSTOMER', @BIZ_CLAIMS_ID, '/business/my-claims/expense', NULL, 10, NULL, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_CLAIM_EXPENSE');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_CLAIM_TRAVEL_EXP', 'MNU_BIZ_CLAIM_TRAVEL_EXP', 'Travel Expense', 'CUSTOMER', @BIZ_CLAIMS_ID, '/business/my-claims/travel-expense', NULL, 20, NULL, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_CLAIM_TRAVEL_EXP');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_RPT_WORK_TIME', 'MNU_BIZ_RPT_WORK_TIME', 'Work Time', 'CUSTOMER', @BIZ_REPORTS_ID, '/business/reports/work-time', NULL, 10, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_RPT_WORK_TIME');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_RPT_MONTHLY_EXP', 'MNU_BIZ_RPT_MONTHLY_EXP', 'Monthly Expenses', 'CUSTOMER', @BIZ_REPORTS_ID, '/business/reports/monthly-expenses', NULL, 20, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_RPT_MONTHLY_EXP');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_TXN', 'MNU_BIZ_FIN_TXN', 'Transactions', 'CUSTOMER', @CUSTOMER_FIN_ID, '/business/finance/transactions', NULL, 40, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_TXN');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_MGT', 'MNU_BIZ_FIN_MGT', 'Finance Management', 'CUSTOMER', @CUSTOMER_FIN_ID, '/business/finance/management', NULL, 50, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_MGT');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_RPT', 'MNU_BIZ_FIN_RPT', 'Finance Reports', 'CUSTOMER', @CUSTOMER_FIN_ID, '/business/finance/reports', NULL, 60, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_RPT');

SET @BIZ_FIN_TXN_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_TXN' LIMIT 1);
SET @BIZ_FIN_MGT_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_MGT' LIMIT 1);
SET @BIZ_FIN_RPT_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_RPT' LIMIT 1);

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_TXN_PURCHASE', 'MNU_BIZ_FIN_TXN_PURCHASE', 'Purchase', 'CUSTOMER', @BIZ_FIN_TXN_ID, '/business/finance/transactions/purchase', NULL, 10, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_TXN_PURCHASE');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_TXN_SALES', 'MNU_BIZ_FIN_TXN_SALES', 'Sales', 'CUSTOMER', @BIZ_FIN_TXN_ID, '/business/finance/transactions/sales', NULL, 20, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_TXN_SALES');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_TXN_OPEX', 'MNU_BIZ_FIN_TXN_OPEX', 'OpEx', 'CUSTOMER', @BIZ_FIN_TXN_ID, '/business/finance/transactions/opex', NULL, 30, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_TXN_OPEX');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_TXN_CORP_ACC', 'MNU_BIZ_FIN_TXN_CORP_ACC', 'Corporate Account', 'CUSTOMER', @BIZ_FIN_TXN_ID, '/business/finance/transactions/corporate-account', NULL, 40, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_TXN_CORP_ACC');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_TXN_PAYROLL', 'MNU_BIZ_FIN_TXN_PAYROLL', 'Payroll', 'CUSTOMER', @BIZ_FIN_TXN_ID, '/business/finance/transactions/payroll', NULL, 50, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_TXN_PAYROLL');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_MGT_EXPENSE', 'MNU_BIZ_FIN_MGT_EXPENSE', 'Expense', 'CUSTOMER', @BIZ_FIN_MGT_ID, '/business/finance/management/expense', NULL, 10, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_MGT_EXPENSE');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_MGT_BALANCE', 'MNU_BIZ_FIN_MGT_BALANCE', 'Balance', 'CUSTOMER', @BIZ_FIN_MGT_ID, '/business/finance/management/balance', NULL, 20, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_MGT_BALANCE');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_MGT_CLOSING', 'MNU_BIZ_FIN_MGT_CLOSING', 'Closing', 'CUSTOMER', @BIZ_FIN_MGT_ID, '/business/finance/management/closing', NULL, 30, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_MGT_CLOSING');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_MGT_ASSET', 'MNU_BIZ_FIN_MGT_ASSET', 'Asset', 'CUSTOMER', @BIZ_FIN_MGT_ID, '/business/finance/management/asset', NULL, 40, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_MGT_ASSET');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_MGT_FIXED_OPEX', 'MNU_BIZ_FIN_MGT_FIXED_OPEX', 'Fixed OpEx', 'CUSTOMER', @BIZ_FIN_MGT_ID, '/business/finance/management/fixed-opex', NULL, 50, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_MGT_FIXED_OPEX');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_MGT_FIXED_SALES', 'MNU_BIZ_FIN_MGT_FIXED_SALES', 'Fixed Sales', 'CUSTOMER', @BIZ_FIN_MGT_ID, '/business/finance/management/fixed-sales', NULL, 60, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_MGT_FIXED_SALES');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_RPT_LEDGER', 'MNU_BIZ_FIN_RPT_LEDGER', 'Account Ledger', 'CUSTOMER', @BIZ_FIN_RPT_ID, '/business/finance/reports/account-ledger', NULL, 10, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_RPT_LEDGER');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_RPT_ASSET', 'MNU_BIZ_FIN_RPT_ASSET', 'Asset List', 'CUSTOMER', @BIZ_FIN_RPT_ID, '/business/finance/reports/assets', NULL, 20, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_RPT_ASSET');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_FIN_RPT_ANNUAL', 'MNU_BIZ_FIN_RPT_ANNUAL', 'Annual Reports', 'CUSTOMER', @BIZ_FIN_RPT_ID, '/business/finance/reports/annual', NULL, 30, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_RPT_ANNUAL');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MST_EMP', 'MNU_BIZ_MST_EMP', 'Employees', 'CUSTOMER', @BIZ_MASTER_ID, '/business/setup/employees', NULL, 10, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MST_EMP');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MST_DEPT', 'MNU_BIZ_MST_DEPT', 'Departments', 'CUSTOMER', @BIZ_MASTER_ID, '/business/setup/departments', NULL, 20, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MST_DEPT');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MST_ACC', 'MNU_BIZ_MST_ACC', 'Account Codes', 'CUSTOMER', @BIZ_MASTER_ID, '/business/setup/account-codes', NULL, 30, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MST_ACC');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MST_CORP_ACC', 'MNU_BIZ_MST_CORP_ACC', 'Corporate Accounts', 'CUSTOMER', @BIZ_MASTER_ID, '/business/setup/corporate-accounts', NULL, 40, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MST_CORP_ACC');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MST_DAILY_ALLOWANCE', 'MNU_BIZ_MST_DAILY_ALLOWANCE', 'Daily Allowance', 'CUSTOMER', @BIZ_MASTER_ID, '/business/setup/daily-allowance', NULL, 50, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MST_DAILY_ALLOWANCE');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MST_CORP_CAL', 'MNU_BIZ_MST_CORP_CAL', 'Corporate Calendar', 'CUSTOMER', @BIZ_MASTER_ID, '/business/setup/corporate-calendar', NULL, 60, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MST_CORP_CAL');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MST_ACC_MAPPING', 'MNU_BIZ_MST_ACC_MAPPING', 'Account Mapping', 'CUSTOMER', @BIZ_MASTER_ID, '/business/setup/account-mapping', NULL, 70, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MST_ACC_MAPPING');

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, BILL_GATE_CD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_BIZ_MST_FI_STMT', 'MNU_BIZ_MST_FI_STMT', 'Financial Statements', 'CUSTOMER', @BIZ_MASTER_ID, '/business/setup/financial-statements', NULL, 80, 'PAID_CUSTOMER_ADMIN', 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_MST_FI_STMT');

INSERT INTO TB_CD (GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, USE_YN, DSP_ORD, CRT_BY, UPD_BY) VALUES
    (@MNU_GRP_ID, 'MNU_BIZ_REQUESTS', '신청', 'Requests', 'Anfragen', 'Y', 210, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_REQ_WORK_TIME', '근무시간', 'Work Time', 'Arbeitszeit', 'Y', 211, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_REQ_EXPENSE', '비용', 'Expense', 'Ausgabe', 'Y', 212, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_REQ_TRIP', '출장', 'Business Trip', 'Geschaeftsreise', 'Y', 213, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_REQ_LEAVE', '휴가', 'Vacation', 'Urlaub', 'Y', 214, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MY_CLAIMS', '내 청구', 'My Claims', 'Meine Abrechnungen', 'Y', 220, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_CLAIM_EXPENSE', '비용 청구', 'Expense Claims', 'Ausgaben', 'Y', 221, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_CLAIM_TRAVEL_EXP', '출장비 청구', 'Travel Expense', 'Reisekosten', 'Y', 222, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_REPORTS', '리포트', 'Reports', 'Berichte', 'Y', 230, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_RPT_WORK_TIME', '근무시간 리포트', 'Work Time', 'Arbeitszeit', 'Y', 231, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_RPT_MONTHLY_EXP', '월 비용 리포트', 'Monthly Expenses', 'Monatliche Ausgaben', 'Y', 232, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_TXN', '거래', 'Transactions', 'Transaktionen', 'Y', 401, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_TXN_PURCHASE', '매입', 'Purchase', 'Einkauf', 'Y', 402, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_TXN_SALES', '매출', 'Sales', 'Verkauf', 'Y', 403, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_TXN_OPEX', '운영비', 'OpEx', 'Betriebsausgaben', 'Y', 404, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_TXN_CORP_ACC', '법인계좌', 'Corporate Account', 'Firmenkonto', 'Y', 405, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_TXN_PAYROLL', '급여', 'Payroll', 'Gehaltsabrechnung', 'Y', 406, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_MGT', '재무 관리', 'Finance Management', 'Finanzverwaltung', 'Y', 410, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_MGT_EXPENSE', '비용 관리', 'Expense', 'Ausgaben', 'Y', 411, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_MGT_BALANCE', '잔액 관리', 'Balance', 'Kontostand', 'Y', 412, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_MGT_CLOSING', '마감', 'Closing', 'Abschluss', 'Y', 413, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_MGT_ASSET', '자산', 'Asset', 'Anlage', 'Y', 414, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_MGT_FIXED_OPEX', '고정 운영비', 'Fixed OpEx', 'Fixe Kosten', 'Y', 415, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_MGT_FIXED_SALES', '고정 매출', 'Fixed Sales', 'Fixumsatz', 'Y', 416, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_RPT', '재무 리포트', 'Finance Reports', 'Finanzberichte', 'Y', 420, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_RPT_LEDGER', '계정 원장', 'Account Ledger', 'Sachkontenblatt', 'Y', 421, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_RPT_ASSET', '자산 목록', 'Asset List', 'Anlagenliste', 'Y', 422, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_FIN_RPT_ANNUAL', '연간 리포트', 'Annual Reports', 'Jahresberichte', 'Y', 423, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MASTER', '업무 설정', 'Business Setup', 'Fachliche Einrichtung', 'Y', 600, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MST_EMP', '직원', 'Employees', 'Mitarbeiter', 'Y', 601, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MST_DEPT', '부서', 'Departments', 'Abteilungen', 'Y', 602, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MST_ACC', '계정 코드', 'Account Codes', 'Kontencodes', 'Y', 603, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MST_CORP_ACC', '법인 계좌', 'Corporate Accounts', 'Firmenkonten', 'Y', 604, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MST_DAILY_ALLOWANCE', '일비', 'Daily Allowance', 'Tagegeld', 'Y', 605, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MST_CORP_CAL', '회사 달력', 'Corporate Calendar', 'Firmenkalender', 'Y', 606, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MST_ACC_MAPPING', '계정 매핑', 'Account Mapping', 'Kontenzuordnung', 'Y', 607, 'SYSTEM', 'SYSTEM'),
    (@MNU_GRP_ID, 'MNU_BIZ_MST_FI_STMT', '재무제표', 'Financial Statements', 'Finanzberichte', 'Y', 608, 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE
    CD_NM_KO = VALUES(CD_NM_KO),
    CD_NM_EN = VALUES(CD_NM_EN),
    CD_NM_DE = VALUES(CD_NM_DE),
    USE_YN = VALUES(USE_YN),
    DSP_ORD = VALUES(DSP_ORD),
    UPD_BY = 'SYSTEM';

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID,
       m.ID,
       'Y',
       CASE
           WHEN m.MNU_CD LIKE 'MNU_BIZ_REQ_%' OR m.MNU_CD LIKE 'MNU_BIZ_CLAIM_%' THEN 'Y'
           WHEN r.ROLE_CD IN ('ROLE_CUSTOMER_ADMIN_MEMBER','ROLE_CUSTOMER_ADMIN_LEADER','ROLE_CUSTOMER_FINANCE_ADMIN_MEMBER','ROLE_CUSTOMER_FINANCE_ADMIN_LEADER','ROLE_PLATFORM_SUPER_ADMIN') THEN 'Y'
           ELSE 'N'
       END,
       CASE
           WHEN m.MNU_CD LIKE 'MNU_BIZ_REQ_%' OR m.MNU_CD LIKE 'MNU_BIZ_CLAIM_%' THEN 'Y'
           WHEN r.ROLE_CD IN ('ROLE_CUSTOMER_ADMIN_MEMBER','ROLE_CUSTOMER_ADMIN_LEADER','ROLE_CUSTOMER_FINANCE_ADMIN_MEMBER','ROLE_CUSTOMER_FINANCE_ADMIN_LEADER','ROLE_PLATFORM_SUPER_ADMIN') THEN 'Y'
           ELSE 'N'
       END,
       CASE WHEN r.ROLE_CD = 'ROLE_PLATFORM_SUPER_ADMIN' THEN 'Y' ELSE 'N' END,
       CASE WHEN r.ROLE_CD LIKE '%LEADER' OR r.ROLE_CD IN ('ROLE_CUSTOMER_ADMIN_MEMBER','ROLE_CUSTOMER_ADMIN_LEADER','ROLE_CUSTOMER_FINANCE_ADMIN_MEMBER','ROLE_CUSTOMER_FINANCE_ADMIN_LEADER','ROLE_PLATFORM_SUPER_ADMIN') THEN 'Y' ELSE 'N' END,
       CASE WHEN m.MNU_CD LIKE 'MNU_BIZ_RPT_%' OR m.MNU_CD LIKE 'MNU_BIZ_FIN_RPT_%' OR r.ROLE_CD LIKE '%ADMIN%' THEN 'Y' ELSE 'N' END,
       'SYSTEM',
       'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_CD LIKE 'MNU_BIZ_%'
WHERE r.ROLE_CD IN (
    'ROLE_CUSTOMER_USER_MEMBER',
    'ROLE_CUSTOMER_USER_LEADER',
    'ROLE_CUSTOMER_HR_ADMIN_MEMBER',
    'ROLE_CUSTOMER_HR_ADMIN_LEADER',
    'ROLE_CUSTOMER_FINANCE_ADMIN_MEMBER',
    'ROLE_CUSTOMER_FINANCE_ADMIN_LEADER',
    'ROLE_CUSTOMER_ADMIN_MEMBER',
    'ROLE_CUSTOMER_ADMIN_LEADER',
    'ROLE_PLATFORM_SUPER_ADMIN'
)
  AND (
      m.BILL_GATE_CD IS NULL
      OR r.ROLE_CD IN (
          'ROLE_CUSTOMER_HR_ADMIN_MEMBER',
          'ROLE_CUSTOMER_HR_ADMIN_LEADER',
          'ROLE_CUSTOMER_FINANCE_ADMIN_MEMBER',
          'ROLE_CUSTOMER_FINANCE_ADMIN_LEADER',
          'ROLE_CUSTOMER_ADMIN_MEMBER',
          'ROLE_CUSTOMER_ADMIN_LEADER',
          'ROLE_PLATFORM_SUPER_ADMIN'
      )
  )
  AND NOT EXISTS (
      SELECT 1
      FROM TB_ROLE_MNU_AUTH a
      WHERE a.ROLE_ID = r.ID
        AND a.MNU_ID = m.ID
  );
