-- Rehomes AS-IS business menus into the existing TO-BE customer menu tree.
-- V21 exposed the 업무 surface as standalone business roots; the SaaS shell already
-- has Team, HR, and Finance roots, so business leaves must live under those roots.

SET @CUSTOMER_TEAM_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_TEAM' LIMIT 1);
SET @CUSTOMER_HR_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_HR' LIMIT 1);
SET @CUSTOMER_FIN_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_FIN' LIMIT 1);
SET @BIZ_FIN_MGT_ID = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'MNU_BIZ_FIN_MGT' LIMIT 1);

UPDATE TB_MNU
SET USE_YN = 'N',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD IN (
    'MNU_BIZ_REQUESTS',
    'MNU_BIZ_MY_CLAIMS',
    'MNU_BIZ_REPORTS',
    'MNU_BIZ_MASTER',
    'MNU_BIZ_REQ_WORK_TIME',
    'MNU_BIZ_REQ_LEAVE',
    'MNU_BIZ_MST_EMP',
    'MNU_BIZ_MST_DEPT',
    'MNU_BIZ_FIN_MGT_EXPENSE'
);

UPDATE TB_ROLE_MNU_AUTH a
JOIN TB_MNU m ON m.ID = a.MNU_ID
SET a.VIEW_YN = 'N',
    a.CRT_YN = 'N',
    a.UPD_YN = 'N',
    a.DEL_YN = 'N',
    a.APRV_YN = 'N',
    a.EXPRT_YN = 'N',
    a.UPD_BY = 'SYSTEM',
    a.UPD_DTM = CURRENT_TIMESTAMP
WHERE m.MNU_CD IN (
    'MNU_BIZ_REQUESTS',
    'MNU_BIZ_MY_CLAIMS',
    'MNU_BIZ_REPORTS',
    'MNU_BIZ_MASTER',
    'MNU_BIZ_REQ_WORK_TIME',
    'MNU_BIZ_REQ_LEAVE',
    'MNU_BIZ_MST_EMP',
    'MNU_BIZ_MST_DEPT',
    'MNU_BIZ_FIN_MGT_EXPENSE'
);

UPDATE TB_MNU
SET UP_MNU_ID = @CUSTOMER_TEAM_ID,
    PATH_URI = '/customer/team/business-trip',
    DSP_ORD = 40,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_REQ_TRIP';

UPDATE TB_MNU
SET UP_MNU_ID = @CUSTOMER_TEAM_ID,
    PATH_URI = '/customer/team/work-time-report',
    DSP_ORD = 50,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_RPT_WORK_TIME';

UPDATE TB_MNU
SET UP_MNU_ID = @CUSTOMER_HR_ID,
    PATH_URI = '/customer/hr/corporate-calendar',
    DSP_ORD = 35,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_MST_CORP_CAL';

UPDATE TB_MNU
SET UP_MNU_ID = @CUSTOMER_FIN_ID,
    PATH_URI = '/customer/finance/expense-request',
    DSP_ORD = 22,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_REQ_EXPENSE';

UPDATE TB_MNU
SET UP_MNU_ID = @CUSTOMER_FIN_ID,
    PATH_URI = '/customer/finance/expense-claims',
    DSP_ORD = 23,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_CLAIM_EXPENSE';

UPDATE TB_MNU
SET UP_MNU_ID = @CUSTOMER_FIN_ID,
    PATH_URI = '/customer/finance/travel-expense-claims',
    DSP_ORD = 24,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_CLAIM_TRAVEL_EXP';

UPDATE TB_MNU
SET UP_MNU_ID = @CUSTOMER_FIN_ID,
    PATH_URI = '/customer/finance/monthly-expense-report',
    DSP_ORD = 25,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_RPT_MONTHLY_EXP';

UPDATE TB_MNU
SET PATH_URI = '/customer/finance/transactions',
    DSP_ORD = 40,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_FIN_TXN';

UPDATE TB_MNU
SET PATH_URI = '/customer/finance/management',
    DSP_ORD = 50,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_FIN_MGT';

UPDATE TB_MNU
SET PATH_URI = '/customer/finance/reports',
    DSP_ORD = 60,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD = 'MNU_BIZ_FIN_RPT';

UPDATE TB_MNU
SET PATH_URI = CONCAT('/customer/finance/transactions/', CASE MNU_CD
        WHEN 'MNU_BIZ_FIN_TXN_PURCHASE' THEN 'purchase'
        WHEN 'MNU_BIZ_FIN_TXN_SALES' THEN 'sales'
        WHEN 'MNU_BIZ_FIN_TXN_OPEX' THEN 'opex'
        WHEN 'MNU_BIZ_FIN_TXN_CORP_ACC' THEN 'corporate-account'
        WHEN 'MNU_BIZ_FIN_TXN_PAYROLL' THEN 'payroll'
    END),
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD IN (
    'MNU_BIZ_FIN_TXN_PURCHASE',
    'MNU_BIZ_FIN_TXN_SALES',
    'MNU_BIZ_FIN_TXN_OPEX',
    'MNU_BIZ_FIN_TXN_CORP_ACC',
    'MNU_BIZ_FIN_TXN_PAYROLL'
);

UPDATE TB_MNU
SET PATH_URI = CONCAT('/customer/finance/management/', CASE MNU_CD
        WHEN 'MNU_BIZ_FIN_MGT_BALANCE' THEN 'balance'
        WHEN 'MNU_BIZ_FIN_MGT_CLOSING' THEN 'closing'
        WHEN 'MNU_BIZ_FIN_MGT_ASSET' THEN 'asset'
        WHEN 'MNU_BIZ_FIN_MGT_FIXED_OPEX' THEN 'fixed-opex'
        WHEN 'MNU_BIZ_FIN_MGT_FIXED_SALES' THEN 'fixed-sales'
    END),
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD IN (
    'MNU_BIZ_FIN_MGT_BALANCE',
    'MNU_BIZ_FIN_MGT_CLOSING',
    'MNU_BIZ_FIN_MGT_ASSET',
    'MNU_BIZ_FIN_MGT_FIXED_OPEX',
    'MNU_BIZ_FIN_MGT_FIXED_SALES'
);

UPDATE TB_MNU
SET PATH_URI = CONCAT('/customer/finance/reports/', CASE MNU_CD
        WHEN 'MNU_BIZ_FIN_RPT_LEDGER' THEN 'account-ledger'
        WHEN 'MNU_BIZ_FIN_RPT_ASSET' THEN 'assets'
        WHEN 'MNU_BIZ_FIN_RPT_ANNUAL' THEN 'annual'
    END),
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD IN (
    'MNU_BIZ_FIN_RPT_LEDGER',
    'MNU_BIZ_FIN_RPT_ASSET',
    'MNU_BIZ_FIN_RPT_ANNUAL'
);

UPDATE TB_MNU
SET UP_MNU_ID = @BIZ_FIN_MGT_ID,
    PATH_URI = CONCAT('/customer/finance/management/', CASE MNU_CD
        WHEN 'MNU_BIZ_MST_ACC' THEN 'account-codes'
        WHEN 'MNU_BIZ_MST_CORP_ACC' THEN 'corporate-accounts'
        WHEN 'MNU_BIZ_MST_DAILY_ALLOWANCE' THEN 'daily-allowance'
        WHEN 'MNU_BIZ_MST_ACC_MAPPING' THEN 'account-mapping'
        WHEN 'MNU_BIZ_MST_FI_STMT' THEN 'financial-statements'
    END),
    DSP_ORD = CASE MNU_CD
        WHEN 'MNU_BIZ_MST_ACC' THEN 70
        WHEN 'MNU_BIZ_MST_CORP_ACC' THEN 80
        WHEN 'MNU_BIZ_MST_DAILY_ALLOWANCE' THEN 90
        WHEN 'MNU_BIZ_MST_ACC_MAPPING' THEN 100
        WHEN 'MNU_BIZ_MST_FI_STMT' THEN 110
        ELSE DSP_ORD
    END,
    BILL_GATE_CD = 'PAID_CUSTOMER_ADMIN',
    USE_YN = 'Y',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE MNU_CD IN (
    'MNU_BIZ_MST_ACC',
    'MNU_BIZ_MST_CORP_ACC',
    'MNU_BIZ_MST_DAILY_ALLOWANCE',
    'MNU_BIZ_MST_ACC_MAPPING',
    'MNU_BIZ_MST_FI_STMT'
);
