-- ============================================================
-- V25: 마스터 테이블 확장 + 경비 계정과목(TB_EXP_ACC) 신규
-- ============================================================
-- Idempotent: IF NOT EXISTS / IF EXISTS / OR REPLACE 사용
-- ============================================================

-- ── 1. TB_CO ALTER ─────────────────────────────────────────

ALTER TABLE TB_CO
    ADD COLUMN IF NOT EXISTS EXP_ACC_CD INT NULL COMMENT 'Company Personenkonto (FK → TB_EXP_ACC)' AFTER REG_NO,
    ADD COLUMN IF NOT EXISTS COUNTRY VARCHAR(5) NULL COMMENT 'Country/State code (HE, BY, BE...)' AFTER EXP_ACC_CD,
    ADD COLUMN IF NOT EXISTS ADDRESS VARCHAR(500) NULL COMMENT 'Company address' AFTER COUNTRY;

ALTER TABLE TB_CO_HIST
    ADD COLUMN IF NOT EXISTS EXP_ACC_CD INT NULL COMMENT 'Company Personenkonto' AFTER REG_NO,
    ADD COLUMN IF NOT EXISTS COUNTRY VARCHAR(5) NULL COMMENT 'Country/State code' AFTER EXP_ACC_CD,
    ADD COLUMN IF NOT EXISTS ADDRESS VARCHAR(500) NULL COMMENT 'Company address' AFTER COUNTRY;

CREATE OR REPLACE TRIGGER TR_TB_CO_AI
AFTER INSERT ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_CD, CO_NM, REG_NO, EXP_ACC_CD, COUNTRY, ADDRESS, STS_CD, LUNCH_STR_TM, LUNCH_END_TM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_CD, NEW.CO_NM, NEW.REG_NO, NEW.EXP_ACC_CD, NEW.COUNTRY, NEW.ADDRESS, NEW.STS_CD, NEW.LUNCH_STR_TM, NEW.LUNCH_END_TM, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE OR REPLACE TRIGGER TR_TB_CO_AU
AFTER UPDATE ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_CD, CO_NM, REG_NO, EXP_ACC_CD, COUNTRY, ADDRESS, STS_CD, LUNCH_STR_TM, LUNCH_END_TM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_CD, NEW.CO_NM, NEW.REG_NO, NEW.EXP_ACC_CD, NEW.COUNTRY, NEW.ADDRESS, NEW.STS_CD, NEW.LUNCH_STR_TM, NEW.LUNCH_END_TM, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE OR REPLACE TRIGGER TR_TB_CO_BD
BEFORE DELETE ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_CD, CO_NM, REG_NO, EXP_ACC_CD, COUNTRY, ADDRESS, STS_CD, LUNCH_STR_TM, LUNCH_END_TM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_CD, OLD.CO_NM, OLD.REG_NO, OLD.EXP_ACC_CD, OLD.COUNTRY, OLD.ADDRESS, OLD.STS_CD, OLD.LUNCH_STR_TM, OLD.LUNCH_END_TM, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

-- ── 2. TB_DEPT ALTER ───────────────────────────────────────

ALTER TABLE TB_DEPT
    ADD COLUMN IF NOT EXISTS VAC_CNT DECIMAL(5,1) NULL COMMENT 'Dept base annual leave days (overrides company policy if set)' AFTER REGION_CD,
    ADD COLUMN IF NOT EXISTS VAC_INC DECIMAL(5,1) NULL COMMENT 'Dept tenure increment days/year (overrides company policy if set)' AFTER VAC_CNT,
    ADD COLUMN IF NOT EXISTS DSP_ORD INT NOT NULL DEFAULT 0 COMMENT 'Display order' AFTER VAC_INC;

ALTER TABLE TB_DEPT_HIST
    ADD COLUMN IF NOT EXISTS VAC_CNT DECIMAL(5,1) NULL COMMENT 'Dept base annual leave days' AFTER REGION_CD,
    ADD COLUMN IF NOT EXISTS VAC_INC DECIMAL(5,1) NULL COMMENT 'Dept tenure increment days/year' AFTER VAC_CNT,
    ADD COLUMN IF NOT EXISTS DSP_ORD INT NOT NULL DEFAULT 0 COMMENT 'Display order' AFTER VAC_INC;

CREATE OR REPLACE TRIGGER TR_TB_DEPT_AI
AFTER INSERT ON TB_DEPT
FOR EACH ROW
INSERT INTO TB_DEPT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, DEPT_CD, DEPT_NM, UP_DEPT_ID, DEPT_LVL_NO, STS_CD, REGION_CD, VAC_CNT, VAC_INC, DSP_ORD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.DEPT_CD, NEW.DEPT_NM, NEW.UP_DEPT_ID, NEW.DEPT_LVL_NO, NEW.STS_CD, NEW.REGION_CD, NEW.VAC_CNT, NEW.VAC_INC, NEW.DSP_ORD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE OR REPLACE TRIGGER TR_TB_DEPT_AU
AFTER UPDATE ON TB_DEPT
FOR EACH ROW
INSERT INTO TB_DEPT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, DEPT_CD, DEPT_NM, UP_DEPT_ID, DEPT_LVL_NO, STS_CD, REGION_CD, VAC_CNT, VAC_INC, DSP_ORD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.DEPT_CD, NEW.DEPT_NM, NEW.UP_DEPT_ID, NEW.DEPT_LVL_NO, NEW.STS_CD, NEW.REGION_CD, NEW.VAC_CNT, NEW.VAC_INC, NEW.DSP_ORD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE OR REPLACE TRIGGER TR_TB_DEPT_BD
BEFORE DELETE ON TB_DEPT
FOR EACH ROW
INSERT INTO TB_DEPT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, DEPT_CD, DEPT_NM, UP_DEPT_ID, DEPT_LVL_NO, STS_CD, REGION_CD, VAC_CNT, VAC_INC, DSP_ORD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.DEPT_CD, OLD.DEPT_NM, OLD.UP_DEPT_ID, OLD.DEPT_LVL_NO, OLD.STS_CD, OLD.REGION_CD, OLD.VAC_CNT, OLD.VAC_INC, OLD.DSP_ORD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

-- ── 3. TB_EMP ALTER ────────────────────────────────────────

ALTER TABLE TB_EMP
    CHANGE COLUMN IF EXISTS JOB_TTL_NM JOB_TTL_CD VARCHAR(20) NULL COMMENT 'Job title code (TB_CD JOB_TTL grp)';

ALTER TABLE TB_EMP
    ADD COLUMN IF NOT EXISTS EML VARCHAR(255) NULL COMMENT 'Employee email' AFTER JOB_TTL_CD,
    ADD COLUMN IF NOT EXISTS EXP_ACC_CD INT NULL COMMENT 'Employee Personenkonto (FK → TB_EXP_ACC)' AFTER EML,
    ADD COLUMN IF NOT EXISTS SEX_CD CHAR(1) NULL COMMENT 'M/F' AFTER EXP_ACC_CD,
    ADD COLUMN IF NOT EXISTS TEL_NO VARCHAR(20) NULL COMMENT 'Phone number' AFTER SEX_CD,
    ADD COLUMN IF NOT EXISTS BIRTH_DT DATE NULL COMMENT 'Birth date' AFTER TEL_NO;

ALTER TABLE TB_EMP_HIST
    CHANGE COLUMN IF EXISTS JOB_TTL_NM JOB_TTL_CD VARCHAR(20) NULL COMMENT 'Job title code';

ALTER TABLE TB_EMP_HIST
    ADD COLUMN IF NOT EXISTS EML VARCHAR(255) NULL COMMENT 'Employee email' AFTER JOB_TTL_CD,
    ADD COLUMN IF NOT EXISTS EXP_ACC_CD INT NULL COMMENT 'Employee Personenkonto' AFTER EML,
    ADD COLUMN IF NOT EXISTS SEX_CD CHAR(1) NULL COMMENT 'M/F' AFTER EXP_ACC_CD,
    ADD COLUMN IF NOT EXISTS TEL_NO VARCHAR(20) NULL COMMENT 'Phone number' AFTER SEX_CD,
    ADD COLUMN IF NOT EXISTS BIRTH_DT DATE NULL COMMENT 'Birth date' AFTER TEL_NO;

CREATE OR REPLACE TRIGGER TR_TB_EMP_AI
AFTER INSERT ON TB_EMP
FOR EACH ROW
INSERT INTO TB_EMP_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, DEPT_ID, MGR_EMP_ID, EMP_NO, EMP_NM, TEAM_ROLE_CD, JOB_TTL_CD, EML, EXP_ACC_CD, SEX_CD, TEL_NO, BIRTH_DT, HIRE_DT, RETR_DT, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.USR_ID, NEW.DEPT_ID, NEW.MGR_EMP_ID, NEW.EMP_NO, NEW.EMP_NM, NEW.TEAM_ROLE_CD, NEW.JOB_TTL_CD, NEW.EML, NEW.EXP_ACC_CD, NEW.SEX_CD, NEW.TEL_NO, NEW.BIRTH_DT, NEW.HIRE_DT, NEW.RETR_DT, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE OR REPLACE TRIGGER TR_TB_EMP_AU
AFTER UPDATE ON TB_EMP
FOR EACH ROW
INSERT INTO TB_EMP_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, DEPT_ID, MGR_EMP_ID, EMP_NO, EMP_NM, TEAM_ROLE_CD, JOB_TTL_CD, EML, EXP_ACC_CD, SEX_CD, TEL_NO, BIRTH_DT, HIRE_DT, RETR_DT, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.USR_ID, NEW.DEPT_ID, NEW.MGR_EMP_ID, NEW.EMP_NO, NEW.EMP_NM, NEW.TEAM_ROLE_CD, NEW.JOB_TTL_CD, NEW.EML, NEW.EXP_ACC_CD, NEW.SEX_CD, NEW.TEL_NO, NEW.BIRTH_DT, NEW.HIRE_DT, NEW.RETR_DT, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE OR REPLACE TRIGGER TR_TB_EMP_BD
BEFORE DELETE ON TB_EMP
FOR EACH ROW
INSERT INTO TB_EMP_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, DEPT_ID, MGR_EMP_ID, EMP_NO, EMP_NM, TEAM_ROLE_CD, JOB_TTL_CD, EML, EXP_ACC_CD, SEX_CD, TEL_NO, BIRTH_DT, HIRE_DT, RETR_DT, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.USR_ID, OLD.DEPT_ID, OLD.MGR_EMP_ID, OLD.EMP_NO, OLD.EMP_NM, OLD.TEAM_ROLE_CD, OLD.JOB_TTL_CD, OLD.EML, OLD.EXP_ACC_CD, OLD.SEX_CD, OLD.TEL_NO, OLD.BIRTH_DT, OLD.HIRE_DT, OLD.RETR_DT, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

-- ── 4. TB_LEAVE_CO_POLICY ALTER ────────────────────────────

ALTER TABLE TB_LEAVE_CO_POLICY
    ADD COLUMN IF NOT EXISTS VAC_INC_DAYS DECIMAL(4,1) NOT NULL DEFAULT 0.0 COMMENT 'Tenure increment days per year' AFTER FLAT_DAYS,
    ADD COLUMN IF NOT EXISTS VAC_INC_MAX_DAYS DECIMAL(4,1) NULL COMMENT 'Max total grant days incl. increment. NULL=unlimited' AFTER VAC_INC_DAYS;

ALTER TABLE TB_LEAVE_CO_POLICY_HIST
    ADD COLUMN IF NOT EXISTS VAC_INC_DAYS DECIMAL(4,1) NOT NULL DEFAULT 0.0 COMMENT 'Tenure increment days per year' AFTER FLAT_DAYS,
    ADD COLUMN IF NOT EXISTS VAC_INC_MAX_DAYS DECIMAL(4,1) NULL COMMENT 'Max total grant days incl. increment' AFTER VAC_INC_DAYS;

CREATE OR REPLACE TRIGGER TR_TB_LEAVE_CO_POLICY_AI
AFTER INSERT ON TB_LEAVE_CO_POLICY
FOR EACH ROW
INSERT INTO TB_LEAVE_CO_POLICY_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID,
    GRANT_TIMING_CD, FISCAL_START_MM, GRANT_TYPE_CD, FLAT_DAYS, VAC_INC_DAYS, VAC_INC_MAX_DAYS,
    CARRYOVER_ENABLED_YN, CARRYOVER_MAX_DAYS, CARRYOVER_EXPIRE_MM, CARRYOVER_EXPIRE_DD,
    EXPIRE_ACTION_CD, DEL_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID,
    NEW.GRANT_TIMING_CD, NEW.FISCAL_START_MM, NEW.GRANT_TYPE_CD, NEW.FLAT_DAYS, NEW.VAC_INC_DAYS, NEW.VAC_INC_MAX_DAYS,
    NEW.CARRYOVER_ENABLED_YN, NEW.CARRYOVER_MAX_DAYS, NEW.CARRYOVER_EXPIRE_MM, NEW.CARRYOVER_EXPIRE_DD,
    NEW.EXPIRE_ACTION_CD, NEW.DEL_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE OR REPLACE TRIGGER TR_TB_LEAVE_CO_POLICY_AU
AFTER UPDATE ON TB_LEAVE_CO_POLICY
FOR EACH ROW
INSERT INTO TB_LEAVE_CO_POLICY_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID,
    GRANT_TIMING_CD, FISCAL_START_MM, GRANT_TYPE_CD, FLAT_DAYS, VAC_INC_DAYS, VAC_INC_MAX_DAYS,
    CARRYOVER_ENABLED_YN, CARRYOVER_MAX_DAYS, CARRYOVER_EXPIRE_MM, CARRYOVER_EXPIRE_DD,
    EXPIRE_ACTION_CD, DEL_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID,
    NEW.GRANT_TIMING_CD, NEW.FISCAL_START_MM, NEW.GRANT_TYPE_CD, NEW.FLAT_DAYS, NEW.VAC_INC_DAYS, NEW.VAC_INC_MAX_DAYS,
    NEW.CARRYOVER_ENABLED_YN, NEW.CARRYOVER_MAX_DAYS, NEW.CARRYOVER_EXPIRE_MM, NEW.CARRYOVER_EXPIRE_DD,
    NEW.EXPIRE_ACTION_CD, NEW.DEL_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

-- ── 5. TB_EXP_ACC 신규 (경비 계정과목 마스터) ──────────────

CREATE TABLE IF NOT EXISTS TB_EXP_ACC (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    TENANT_ID       BIGINT       NOT NULL COMMENT 'FK → TB_TENANT',
    CO_ID           BIGINT       NOT NULL COMMENT 'FK → TB_CO',
    EXP_ACC_CD      INT          NOT NULL COMMENT 'SKR03 account number (300, 1200, 80000...)',
    EXP_ACC_DESC    VARCHAR(200) NOT NULL COMMENT 'Account name (German)',
    EXP_ACC_DESC_KO VARCHAR(200) NULL     COMMENT 'Account name (Korean)',
    EXP_ACC_DESC_EN VARCHAR(200) NULL     COMMENT 'Account name (English)',
    PURCHASE_YN     CHAR(1)      NOT NULL DEFAULT 'N',
    SALES_YN        CHAR(1)      NOT NULL DEFAULT 'N',
    EXPENSE_YN      CHAR(1)      NOT NULL DEFAULT 'N',
    FIXED_EXP_YN    CHAR(1)      NOT NULL DEFAULT 'N',
    DRCR_CD         CHAR(1)      NOT NULL DEFAULT 'C' COMMENT 'D=Debit, C=Credit',
    CARRYOVER_CD    CHAR(1)      NOT NULL DEFAULT 'N' COMMENT 'G/D/C/N',
    FI_STMT_CD      VARCHAR(5)   NOT NULL DEFAULT 'N' COMMENT 'BS/IS/AR/AP/N',
    EXP_CATG_CD     VARCHAR(10)  NULL     COMMENT 'TRFC/MEAL/ENTM/OTHR/NONE',
    REMARK          VARCHAR(500) NULL,
    DSP_ORD         INT          NOT NULL DEFAULT 0,
    DEL_YN          CHAR(1)      NOT NULL DEFAULT 'N',
    CRT_BY          VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    CRT_DTM         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY          VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    UPD_DTM         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_EXP_ACC PRIMARY KEY (ID),
    CONSTRAINT UK_TB_EXP_ACC_TENANT_CO_CD UNIQUE (TENANT_ID, CO_ID, EXP_ACC_CD),
    CONSTRAINT FK_TB_EXP_ACC_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_EXP_ACC_CO FOREIGN KEY (CO_ID) REFERENCES TB_CO (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS IX_TB_EXP_ACC_TENANT_ID ON TB_EXP_ACC (TENANT_ID);
CREATE INDEX IF NOT EXISTS IX_TB_EXP_ACC_CO_ID     ON TB_EXP_ACC (CO_ID);
CREATE INDEX IF NOT EXISTS IX_TB_EXP_ACC_CD        ON TB_EXP_ACC (EXP_ACC_CD);

CREATE TABLE IF NOT EXISTS TB_EXP_ACC_HIST (
    HIST_ID         BIGINT       NOT NULL AUTO_INCREMENT,
    HIST_TP         CHAR(1)      NOT NULL COMMENT 'I/U/D',
    HIST_BY         VARCHAR(100) NOT NULL,
    HIST_DTM        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID              BIGINT       NOT NULL,
    TENANT_ID       BIGINT       NOT NULL,
    CO_ID           BIGINT       NOT NULL,
    EXP_ACC_CD      INT          NOT NULL,
    EXP_ACC_DESC    VARCHAR(200) NOT NULL,
    EXP_ACC_DESC_KO VARCHAR(200) NULL,
    EXP_ACC_DESC_EN VARCHAR(200) NULL,
    PURCHASE_YN     CHAR(1)      NOT NULL,
    SALES_YN        CHAR(1)      NOT NULL,
    EXPENSE_YN      CHAR(1)      NOT NULL,
    FIXED_EXP_YN    CHAR(1)      NOT NULL,
    DRCR_CD         CHAR(1)      NOT NULL,
    CARRYOVER_CD    CHAR(1)      NOT NULL,
    FI_STMT_CD      VARCHAR(5)   NOT NULL,
    EXP_CATG_CD     VARCHAR(10)  NULL,
    REMARK          VARCHAR(500) NULL,
    DSP_ORD         INT          NOT NULL,
    DEL_YN          CHAR(1)      NOT NULL,
    CRT_BY          VARCHAR(100) NOT NULL,
    CRT_DTM         TIMESTAMP    NOT NULL,
    UPD_BY          VARCHAR(100) NOT NULL,
    UPD_DTM         TIMESTAMP    NOT NULL,
    CONSTRAINT PK_TB_EXP_ACC_HIST PRIMARY KEY (HIST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS IX_TB_EXP_ACC_HIST_ID ON TB_EXP_ACC_HIST (ID);

CREATE OR REPLACE TRIGGER TR_TB_EXP_ACC_AI
AFTER INSERT ON TB_EXP_ACC
FOR EACH ROW
INSERT INTO TB_EXP_ACC_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, EXP_ACC_CD, EXP_ACC_DESC, EXP_ACC_DESC_KO, EXP_ACC_DESC_EN,
    PURCHASE_YN, SALES_YN, EXPENSE_YN, FIXED_EXP_YN, DRCR_CD, CARRYOVER_CD, FI_STMT_CD, EXP_CATG_CD,
    REMARK, DSP_ORD, DEL_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.EXP_ACC_CD, NEW.EXP_ACC_DESC, NEW.EXP_ACC_DESC_KO, NEW.EXP_ACC_DESC_EN,
    NEW.PURCHASE_YN, NEW.SALES_YN, NEW.EXPENSE_YN, NEW.FIXED_EXP_YN, NEW.DRCR_CD, NEW.CARRYOVER_CD, NEW.FI_STMT_CD, NEW.EXP_CATG_CD,
    NEW.REMARK, NEW.DSP_ORD, NEW.DEL_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE OR REPLACE TRIGGER TR_TB_EXP_ACC_AU
AFTER UPDATE ON TB_EXP_ACC
FOR EACH ROW
INSERT INTO TB_EXP_ACC_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, EXP_ACC_CD, EXP_ACC_DESC, EXP_ACC_DESC_KO, EXP_ACC_DESC_EN,
    PURCHASE_YN, SALES_YN, EXPENSE_YN, FIXED_EXP_YN, DRCR_CD, CARRYOVER_CD, FI_STMT_CD, EXP_CATG_CD,
    REMARK, DSP_ORD, DEL_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.EXP_ACC_CD, NEW.EXP_ACC_DESC, NEW.EXP_ACC_DESC_KO, NEW.EXP_ACC_DESC_EN,
    NEW.PURCHASE_YN, NEW.SALES_YN, NEW.EXPENSE_YN, NEW.FIXED_EXP_YN, NEW.DRCR_CD, NEW.CARRYOVER_CD, NEW.FI_STMT_CD, NEW.EXP_CATG_CD,
    NEW.REMARK, NEW.DSP_ORD, NEW.DEL_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE OR REPLACE TRIGGER TR_TB_EXP_ACC_BD
BEFORE DELETE ON TB_EXP_ACC
FOR EACH ROW
INSERT INTO TB_EXP_ACC_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, EXP_ACC_CD, EXP_ACC_DESC, EXP_ACC_DESC_KO, EXP_ACC_DESC_EN,
    PURCHASE_YN, SALES_YN, EXPENSE_YN, FIXED_EXP_YN, DRCR_CD, CARRYOVER_CD, FI_STMT_CD, EXP_CATG_CD,
    REMARK, DSP_ORD, DEL_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.EXP_ACC_CD, OLD.EXP_ACC_DESC, OLD.EXP_ACC_DESC_KO, OLD.EXP_ACC_DESC_EN,
    OLD.PURCHASE_YN, OLD.SALES_YN, OLD.EXPENSE_YN, OLD.FIXED_EXP_YN, OLD.DRCR_CD, OLD.CARRYOVER_CD, OLD.FI_STMT_CD, OLD.EXP_CATG_CD,
    OLD.REMARK, OLD.DSP_ORD, OLD.DEL_YN, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

-- ── 6. 공통코드 시드 ───────────────────────────────────────

-- JOB_TTL (직급)
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM_KO, GRP_NM_EN, GRP_NM_DE, USE_YN, CRT_BY, UPD_BY)
VALUES ('JOB_TTL', '직급', 'Job Title', 'Berufsbezeichnung', 'Y', 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE GRP_NM_KO = VALUES(GRP_NM_KO), GRP_NM_EN = VALUES(GRP_NM_EN), GRP_NM_DE = VALUES(GRP_NM_DE);

SET @grp_job_ttl = (SELECT ID FROM TB_CD_GRP WHERE GRP_CD = 'JOB_TTL');

INSERT INTO TB_CD (GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, DSP_ORD, USE_YN, CRT_BY, UPD_BY) VALUES
(@grp_job_ttl, 'CE', '대표',   'CEO',      'Geschäftsführer',  1, 'Y', 'SYSTEM', 'SYSTEM'),
(@grp_job_ttl, 'DR', '이사',   'Director', 'Direktor',         2, 'Y', 'SYSTEM', 'SYSTEM'),
(@grp_job_ttl, 'MG', '과장',   'Manager',  'Abteilungsleiter', 3, 'Y', 'SYSTEM', 'SYSTEM'),
(@grp_job_ttl, 'IN', '인턴',   'Intern',   'Praktikant',       4, 'Y', 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE CD_NM_KO = VALUES(CD_NM_KO), CD_NM_EN = VALUES(CD_NM_EN), CD_NM_DE = VALUES(CD_NM_DE), DSP_ORD = VALUES(DSP_ORD);

-- EXP_CATG (경비 카테고리)
INSERT INTO TB_CD_GRP (GRP_CD, GRP_NM_KO, GRP_NM_EN, GRP_NM_DE, USE_YN, CRT_BY, UPD_BY)
VALUES ('EXP_CATG', '경비 카테고리', 'Expense Category', 'Ausgabenkategorie', 'Y', 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE GRP_NM_KO = VALUES(GRP_NM_KO), GRP_NM_EN = VALUES(GRP_NM_EN), GRP_NM_DE = VALUES(GRP_NM_DE);

SET @grp_exp_catg = (SELECT ID FROM TB_CD_GRP WHERE GRP_CD = 'EXP_CATG');

INSERT INTO TB_CD (GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, DSP_ORD, USE_YN, CRT_BY, UPD_BY) VALUES
(@grp_exp_catg, 'TRFC', '교통비', 'Transportation', 'Fahrtkosten',     1, 'Y', 'SYSTEM', 'SYSTEM'),
(@grp_exp_catg, 'MEAL', '식대',   'Meal',           'Verpflegung',     2, 'Y', 'SYSTEM', 'SYSTEM'),
(@grp_exp_catg, 'ENTM', '접대비', 'Entertainment',  'Bewirtung',       3, 'Y', 'SYSTEM', 'SYSTEM'),
(@grp_exp_catg, 'OTHR', '기타',   'Other',          'Sonstiges',       4, 'Y', 'SYSTEM', 'SYSTEM'),
(@grp_exp_catg, 'NONE', '해당없음', 'N/A',          'Nicht zutreffend', 5, 'Y', 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE CD_NM_KO = VALUES(CD_NM_KO), CD_NM_EN = VALUES(CD_NM_EN), CD_NM_DE = VALUES(CD_NM_DE), DSP_ORD = VALUES(DSP_ORD);

-- ── 7. 시드 데이터 교체 (WHERE 조건이 이미 변경된 값이면 0 rows affected — 멱등) ──

UPDATE TB_CO
SET CO_CD = 'SW', EXP_ACC_CD = 80000, COUNTRY = 'HE', ADDRESS = 'Oberusel'
WHERE CO_CD = 'SINWOO';

UPDATE TB_DEPT
SET DEPT_CD = 'SWH', REGION_CD = 'HE', VAC_CNT = 24.0, VAC_INC = 0.5, DSP_ORD = 1
WHERE DEPT_CD = 'HQ';

UPDATE TB_EMP
SET EMP_NO = 'SW0004', JOB_TTL_CD = 'DR', EML = 'ggamgang@sinwoo-itc.com', EXP_ACC_CD = 80008, SEX_CD = 'M',
    TEL_NO = '017647991276', BIRTH_DT = '1977-05-22'
WHERE EMP_NO = 'EMP001';

UPDATE TB_LEAVE_CO_POLICY
SET FLAT_DAYS = 24.0, VAC_INC_DAYS = 0.5, VAC_INC_MAX_DAYS = 30.0
WHERE TENANT_ID = 'SINWOO' AND CO_ID = 'SINWOO';

UPDATE TB_LEAVE_GRANT
SET EMP_ID = 'SW0004'
WHERE TENANT_ID = 'SINWOO' AND CO_ID = 'SINWOO' AND EMP_ID = 'EMP001';

UPDATE TB_LEAVE_REQ
SET EMP_ID = 'SW0004'
WHERE TENANT_ID = 'SINWOO' AND CO_ID = 'SINWOO' AND EMP_ID = 'EMP001';

UPDATE TB_APRV_LINE
SET EMP_ID = 'SW0004'
WHERE TENANT_ID = 'SINWOO' AND CO_ID = 'SINWOO' AND EMP_ID = 'EMP001';
