SET @SINWOO_INTERNAL_TENANT_ID = (
    SELECT ID
    FROM TB_TENANT
    WHERE TENANT_CD = 'SINWOO_INTERNAL'
    LIMIT 1
);

SET @SINWOO_INTERNAL_CO_ID = (
    SELECT ID
    FROM TB_CO
    WHERE TENANT_ID = @SINWOO_INTERNAL_TENANT_ID
    ORDER BY ID
    LIMIT 1
);

SET @GGAMGANG_USR_ID = (
    SELECT ID
    FROM TB_USR
    WHERE TENANT_ID = @SINWOO_INTERNAL_TENANT_ID
      AND EML = 'ggamgang@sinwoo-itc.com'
    LIMIT 1
);

UPDATE TB_CO
SET CO_CD = CASE WHEN CO_CD = 'DEFAULT' THEN 'SINWOO' ELSE CO_CD END,
    HQ_CTRY_CD = COALESCE(HQ_CTRY_CD, 'DE'),
    HQ_REGION_CD = COALESCE(HQ_REGION_CD, 'HE'),
    HQ_CITY_NM = COALESCE(HQ_CITY_NM, 'Schwalbach'),
    HQ_ADDR_1 = COALESCE(HQ_ADDR_1, 'Berliner Str. 8'),
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE ID = @SINWOO_INTERNAL_CO_ID;

INSERT INTO TB_DEPT (
    TENANT_ID,
    CO_ID,
    DEPT_CD,
    DEPT_NM,
    UP_DEPT_ID,
    DEPT_LVL_NO,
    STS_CD,
    CRT_BY,
    UPD_BY
)
SELECT
    @SINWOO_INTERNAL_TENANT_ID,
    @SINWOO_INTERNAL_CO_ID,
    'SWH',
    'Head Office',
    NULL,
    1,
    'ACTIVE',
    'SYSTEM',
    'SYSTEM'
WHERE @SINWOO_INTERNAL_TENANT_ID IS NOT NULL
  AND @SINWOO_INTERNAL_CO_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM TB_DEPT
      WHERE TENANT_ID = @SINWOO_INTERNAL_TENANT_ID
        AND CO_ID = @SINWOO_INTERNAL_CO_ID
        AND DEPT_CD = 'SWH'
  );

SET @SINWOO_INTERNAL_DEPT_ID = (
    SELECT ID
    FROM TB_DEPT
    WHERE TENANT_ID = @SINWOO_INTERNAL_TENANT_ID
      AND CO_ID = @SINWOO_INTERNAL_CO_ID
      AND DEPT_CD = 'SWH'
    LIMIT 1
);

INSERT INTO TB_EMP (
    TENANT_ID,
    CO_ID,
    USR_ID,
    DEPT_ID,
    MGR_EMP_ID,
    EMP_NO,
    EMP_NM,
    TEAM_ROLE_CD,
    JOB_TTL_NM,
    HIRE_DT,
    RETR_DT,
    STS_CD,
    CRT_BY,
    UPD_BY
)
SELECT
    @SINWOO_INTERNAL_TENANT_ID,
    @SINWOO_INTERNAL_CO_ID,
    NULL,
    @SINWOO_INTERNAL_DEPT_ID,
    NULL,
    'SW0004',
    'Juyong Lee',
    'TM',
    'Director',
    '2020-02-01',
    NULL,
    'ACTIVE',
    'SYSTEM',
    'SYSTEM'
WHERE @SINWOO_INTERNAL_TENANT_ID IS NOT NULL
  AND @SINWOO_INTERNAL_CO_ID IS NOT NULL
  AND @SINWOO_INTERNAL_DEPT_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM TB_EMP
      WHERE TENANT_ID = @SINWOO_INTERNAL_TENANT_ID
        AND CO_ID = @SINWOO_INTERNAL_CO_ID
        AND EMP_NO = 'SW0004'
  );

UPDATE TB_EMP
SET DEPT_ID = @SINWOO_INTERNAL_DEPT_ID,
    EMP_NM = 'Juyong Lee',
    TEAM_ROLE_CD = 'TM',
    JOB_TTL_NM = 'Director',
    HIRE_DT = COALESCE(HIRE_DT, '2020-02-01'),
    RETR_DT = NULL,
    STS_CD = 'ACTIVE',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE TENANT_ID = @SINWOO_INTERNAL_TENANT_ID
  AND CO_ID = @SINWOO_INTERNAL_CO_ID
  AND EMP_NO = 'SW0004';

SET @GGAMGANG_EMP_ID = (
    SELECT ID
    FROM TB_EMP
    WHERE TENANT_ID = @SINWOO_INTERNAL_TENANT_ID
      AND CO_ID = @SINWOO_INTERNAL_CO_ID
      AND EMP_NO = 'SW0004'
    LIMIT 1
);

INSERT INTO TB_EMP_HR_PROFILE (
    TENANT_ID,
    CO_ID,
    EMP_ID,
    LEGACY_EMP_ID,
    WORK_STR_TM,
    WORK_END_TM,
    STD_VAC_CNT,
    INC_VAC_CNT,
    CURR_VAC_CNT,
    PRE_VAC_CNT,
    LEGACY_RESIGN_YN,
    STS_CD,
    CRT_BY,
    UPD_BY
)
SELECT
    @SINWOO_INTERNAL_TENANT_ID,
    @SINWOO_INTERNAL_CO_ID,
    @GGAMGANG_EMP_ID,
    'SW0004',
    '08:00:00',
    '17:00:00',
    24.0,
    2.0,
    26.0,
    0.0,
    'N',
    'ACTIVE',
    'SYSTEM',
    'SYSTEM'
WHERE @GGAMGANG_EMP_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM TB_EMP_HR_PROFILE
      WHERE EMP_ID = @GGAMGANG_EMP_ID
  );

UPDATE TB_EMP_HR_PROFILE
SET LEGACY_EMP_ID = 'SW0004',
    WORK_STR_TM = '08:00:00',
    WORK_END_TM = '17:00:00',
    STD_VAC_CNT = 24.0,
    INC_VAC_CNT = 2.0,
    CURR_VAC_CNT = CASE WHEN CURR_VAC_CNT <= 0 THEN 26.0 ELSE CURR_VAC_CNT END,
    LEGACY_RESIGN_YN = 'N',
    STS_CD = 'ACTIVE',
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE EMP_ID = @GGAMGANG_EMP_ID;

SET @GGAMGANG_LINKED_EMP_ID = (
    SELECT ID
    FROM TB_EMP
    WHERE USR_ID = @GGAMGANG_USR_ID
    LIMIT 1
);

UPDATE TB_USR
SET CO_ID = @SINWOO_INTERNAL_CO_ID,
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE ID = @GGAMGANG_USR_ID
  AND @GGAMGANG_EMP_ID IS NOT NULL
  AND (CO_ID IS NULL OR CO_ID = @SINWOO_INTERNAL_CO_ID);

UPDATE TB_EMP
SET USR_ID = @GGAMGANG_USR_ID,
    UPD_BY = 'SYSTEM',
    UPD_DTM = CURRENT_TIMESTAMP
WHERE ID = @GGAMGANG_EMP_ID
  AND @GGAMGANG_USR_ID IS NOT NULL
  AND (@GGAMGANG_LINKED_EMP_ID IS NULL OR @GGAMGANG_LINKED_EMP_ID = @GGAMGANG_EMP_ID)
  AND (USR_ID IS NULL OR USR_ID = @GGAMGANG_USR_ID);
