-- ============================================================
-- V26: as-is 경비 계정과목 데이터 마이그레이션 (TB_EXP_ACC)
-- ============================================================
-- Source: as-is tb_expense_account_master (~110 rows)
-- Mapping: REF_DESC_1 → EXP_ACC_DESC_KO, FI_STATEMENTS → FI_STMT_CD
-- All accounts assigned to TENANT_ID=1, CO_ID=1 (Sinwoo)
-- ============================================================

INSERT INTO TB_EXP_ACC (TENANT_ID, CO_ID, EXP_ACC_CD, EXP_ACC_DESC, EXP_ACC_DESC_KO, EXP_ACC_DESC_EN,
    PURCHASE_YN, SALES_YN, EXPENSE_YN, FIXED_EXP_YN, DRCR_CD, CARRYOVER_CD, FI_STMT_CD, EXP_CATG_CD, REMARK, DSP_ORD, DEL_YN, CRT_BY, UPD_BY)
VALUES
-- ── SKR03 일반 계정 ──
(1,1, 300,  'Betriebs- und Geschäftsausstattung',         '사무집기',           NULL, 'Y','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 320,  'Pkw',                                        '자동차',             NULL, 'Y','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 480,  'Geringwertige Wirtschaftsgüter',              '소액자산',           NULL, 'N','N','N','N','C','G','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 800,  'Gezeichnetes Kapital',                        '자본금',             NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 860,  'Gewinnvortrag vor Verwendung',                '이월 이익 잉여금',    NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 868,  'Verlustvortrag vor Verwendung',               '이월 결손금',        NULL, 'N','N','N','N','D','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 970,  'Sonstige Rückstellungen',                     '기타 충당금',        NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 977,  'Rückstellungen für Abschluss u. Prüfung',    '결산 및 회계감사 충당금', NULL, 'Y','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1200, 'Commerzbank',                                 '법인계좌',           NULL, 'N','N','N','N','D','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1400, 'Forderungen aus Lieferungen u. Leistung',    '매출',               NULL, 'N','Y','N','N','D','D','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1520, 'Forderungen ggb. Krankenkasse aus AAG',      '의료보험 환급',       NULL, 'N','N','N','N','C','G','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1525, 'Kautionen',                                   '보증금',             NULL, 'N','N','N','N','D','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1540, 'Forderung aus Gewerbesteuerüberzahlung',     '과지급영업세',        NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1549, 'Körperschaftsteuerrückforderung',             '법인세 환급',        NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1571, 'Abziehbare Vorsteuer 7%',                    '7% 선납세금',        NULL, 'N','N','N','N','D','N','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1575, 'Abziehbare Vorsteuer 16%',                   '16% 선납세금',       NULL, 'N','N','N','N','D','N','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1576, 'Abziehbare Vorsteuer 19%',                   '19% 선납세금',       NULL, 'N','N','N','N','D','N','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1600, 'Verbindlichkeiten aus Lieferungen+Leist',    '매입 채무',          NULL, 'Y','N','Y','N','C','C','N', 'OTHR', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1740, 'Verbindlichkeiten aus Lohn und Gehalt',      '급여 채무',          NULL, 'N','N','N','N','C','G','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1741, 'Verbindlichk. Lohn- und Kirchensteuer',      '소득세 및 종교세 채무', NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1742, 'Verbindlichkeiten soziale Sicherheit',       '사회보장세 채무',     NULL, 'N','N','N','Y','C','G','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1755, 'Lohn- und Gehaltsverrechnungen',             '급여공제내역',        NULL, 'N','N','N','N','C','G','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1771, 'Umsatzsteuer 7%',                            '7% 부가세',          NULL, 'N','N','N','N','C','N','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1776, 'Umsatzsteuer 19%',                           '19% 부가세',         NULL, 'N','N','N','N','C','N','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1780, 'Umsatzsteuer-Vorauszahlungen',               '부가세 선납',        NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1781, 'Umsatzsteuer-Vorauszahlungen 1/11',          '1/11 부가세 선납',   NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1790, 'Umsatzsteuer Vorjahr',                       '전년도 부가세',       NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 1791, 'Umsatzsteuer frühere Jahre',                  '이전 년도들 부가세',  NULL, 'N','N','N','N','C','G','BS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 2150, 'Aufwendungen aus Währungsumrechnungen',       '통화 변경 지불',     NULL, 'Y','N','N','N','C','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 2200, 'Körperschaftsteuer',                          '법인세',             NULL, 'N','N','N','N','C','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 2208, 'Solidaritätszuschlag',                        '통독세',             NULL, 'N','N','N','N','C','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 2700, 'Sonstige Erträge betriebs/periodenfremd',    '잡수익',             NULL, 'N','N','N','N','C','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 3100, 'Fremdleistungen',                             '해외 용역비',        NULL, 'Y','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4120, 'Gehälter',                                    '급여',               NULL, 'N','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4130, 'Gesetzliche Sozialaufwendungen',              '사회보장세',          NULL, 'Y','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4138, 'Beiträge zur Berufsgenossenschaft',          '산재보험료',          NULL, 'Y','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4210, 'Miete, unbewegliche Wirtschaftsgüter',       '임대료 및 부동산',    NULL, 'Y','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4320, 'Gewerbesteuer',                               '영업세',             NULL, 'N','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4380, 'Beiträge',                                    '수수료',             NULL, 'Y','N','N','Y','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4510, 'Kfz-Steuern',                                '자동차세',           NULL, 'N','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4520, 'Kfz-Versicherungen',                         '자동차 보험료',      NULL, 'Y','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4530, 'Laufende Kfz-Betriebskosten',                '자동차 유지비',      NULL, 'Y','N','Y','N','D','N','IS','TRFC', '주유, 주차, 세차, 타이어 교체, 인스펙션, TÜV', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4540, 'Kfz-Reparaturen',                            '자동차 수리비',      NULL, 'Y','N','Y','N','D','N','IS','TRFC', '수리비', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4580, 'Sonstige Kfz-Kosten',                        '기타 자동차 비용',   NULL, 'Y','N','Y','N','D','N','IS','TRFC', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4595, 'Fremdfahrzeugkosten',                         '렌터카',             NULL, 'Y','N','Y','N','D','N','IS','TRFC', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4600, 'Werbekosten',                                 '광고비',             NULL, 'Y','N','Y','N','D','N','IS','OTHR', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4640, 'Repräsentationskosten',                       '사내행사 및 복리후생비', NULL, 'Y','N','Y','N','D','N','IS','OTHR', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4650, 'Bewirtungskosten',                            '접대비',             NULL, 'N','N','Y','N','D','N','IS','ENTM', '접대비(식당 영수증)', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4653, 'Aufmerksamkeiten',                            '소급액 현물',        NULL, 'Y','N','Y','N','D','N','IS','OTHR', '사무용 음료 구매', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4663, 'Reisekosten Arbeitnehmer, Fahrtkosten',      '출장비-교통비',      NULL, 'Y','N','Y','N','D','N','IS','TRFC', '주차, 택시, 우버, 볼트, 대중교통비, 항공비, 기차', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4664, 'Reisekosten AN Verpfleg.mehraufwand',        '출장비-식대 및 기타', NULL, 'Y','N','Y','N','D','N','IS','MEAL', '출장가서 사용한 식대, 점심식대(예. 죠이푸드), 일비', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4666, 'Reisekosten AN Übernachtungsaufwand',        '출장비-숙박비',      NULL, 'Y','N','Y','N','D','N','IS','OTHR', '호텔비', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4832, 'Abschreibungen auf Kfz',                     '자동차 감가상각',     NULL, 'Y','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4855, 'Sofortabschreibung GWG',                     '사무용품 감가상각',   NULL, 'Y','N','Y','N','D','N','IS','OTHR', '사무용품', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4910, 'Porto',                                       '우편 수수료',        NULL, 'Y','N','Y','N','D','N','IS','OTHR', '우편물(Deutsche Post)', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4920, 'Telefon',                                     '통신비',             NULL, 'Y','N','Y','N','D','N','IS','OTHR', '사무실 인터넷, 핸드폰 계약', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4930, 'Bürobedarf',                                  '사무용품',           NULL, 'Y','N','Y','N','D','N','IS','OTHR', '사무용품', 0,'N','SYSTEM','SYSTEM'),
(1,1, 4946, 'Freiwillige Sozialleistungen',               '자발적 사회복지보조금', NULL, 'Y','N','Y','N','D','N','IS','OTHR', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4950, 'Rechts- und Beratungskosten',                '법률 자문 수수료',    NULL, 'Y','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4955, 'Buchführungskosten',                          '기장 수수료',        NULL, 'Y','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4957, 'Abschluss- und Prüfungskosten',              '결산 및 회계감사 수수료', NULL, 'Y','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 4970, 'Nebenkosten des Geldverkehrs',               '은행 송금 수수료',    NULL, 'N','N','N','N','D','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 8338, 'Nicht steuerbare Umsätze Drittland',         '제3국 비과세 거래',   NULL, 'N','Y','N','N','C','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 8400, 'Erlöse 19% Ust',                             '매출 19% 부가세',    NULL, 'N','N','N','N','C','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 8611, 'Verrech. sonstige Sachbezüge Kfz 19% Ust',  '자동차 19% 현물급여', NULL, 'N','N','N','N','C','N','IS','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 9000, 'Saldenvorträge Sachkonten',                   '총계정 이월잔액',    NULL, 'N','N','N','N','D','N','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 9008, 'Saldenvorträge Debitoren',                    '미수금',             NULL, 'N','Y','N','N','D','N','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 9009, 'Saldenvorträge Kreditoren',                   '미지급',             NULL, 'Y','N','N','N','C','N','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),

-- ── 매출처 Debitoren (AR) ──
(1,1, 10001, 'ATNS Europe GmbH',                          NULL, NULL, 'N','Y','N','N','D','D','AR','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 10690, 'Hanwha Systems Co., Ltd.',                   NULL, NULL, 'N','Y','N','N','D','D','AR','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 10700, 'Hanwha Q CELLS GmbH',                       NULL, NULL, 'N','Y','N','N','D','D','AR','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 10701, 'Hyundai Motorsport GmbH',                   NULL, NULL, 'N','Y','N','N','D','D','AR','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 11803, 'Samsung SDS Europe Ltd German Branch',      NULL, NULL, 'N','Y','N','N','D','D','AR','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),

-- ── 매입처 Kreditoren (AP) ──
(1,1, 70002, 'Apple Retail Germany B.V. & Co. KG',        NULL, NULL, 'Y','N','N','N','D','C','N', 'NONE', NULL, 4,'N','SYSTEM','SYSTEM'),
(1,1, 70020, 'ARD ZDF Deutschlandradio',                   NULL, NULL, 'Y','N','N','Y','D','C','AP','NONE', NULL, 5,'N','SYSTEM','SYSTEM'),
(1,1, 70090, 'Bundesamt für Justiz',                       NULL, NULL, 'Y','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 70100, 'Bundesanzeiger Verlag GmbH',                NULL, NULL, 'Y','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 70101, 'BGHW',                                      NULL, NULL, 'Y','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 70401, 'EUKO Consulting',                            NULL, NULL, 'Y','N','N','N','D','C','AP','NONE', NULL, 3,'N','SYSTEM','SYSTEM'),
(1,1, 70650, 'Gerichtskasse Frankfurt',                    NULL, NULL, 'Y','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 70700, 'Hotel',                                      NULL, NULL, 'Y','N','N','N','D','C','AP','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 70850, 'IHK Frankfurt',                              NULL, NULL, 'Y','N','N','N','D','C','AP','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 70902, 'Jooy Food',                                  NULL, NULL, 'Y','N','N','N','D','C','AP','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 71105, 'Haufe Service Center GmbH',                 NULL, NULL, 'Y','N','N','Y','D','C','AP','NONE', NULL, 6,'N','SYSTEM','SYSTEM'),
(1,1, 71801, 'Suh-Wang Reise GmbH',                       NULL, NULL, 'Y','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 71805, 'Sinwoo International ITC.',                  NULL, NULL, 'Y','N','N','N','D','C','AP','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 71807, 'Senger GmbH & Co. KG',                      NULL, NULL, 'Y','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 71901, 'Telekom Deutschland GmbH',                  NULL, NULL, 'Y','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 72001, 'Vodafone GmbH',                              NULL, NULL, 'Y','N','N','N','D','C','AP','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),

-- ── Personenkonto: 회사 ──
(1,1, 80000, 'Sinwoo',                                     NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),

-- ── Personenkonto: 직원 (SW 본사) ──
(1,1, 80001, 'Seung Ho Choi',                              NULL, NULL, 'N','N','N','N','D','C','AP','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80002, 'Sang Kwang Nam',                             NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80003, 'Jieun Lee',                                  NULL, NULL, 'N','N','N','N','D','C','AP','NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80007, 'Junserk Park',                               NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80008, 'Juyong Lee',                                 NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80010, 'Chiho Yun',                                  NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80011, 'Jung Woo Choi',                              NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80013, 'Changyong Jung',                             NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80014, 'Wonjun Choi',                                NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80015, 'Serae Kim',                                  NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80016, 'Sungwon Bang',                               NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80017, 'Byungjin Choi',                              NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 80018, 's.son',                                      NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 1,'N','SYSTEM','SYSTEM'),
(1,1, 80019, 'FI_Admin',                                   NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 2,'N','SYSTEM','SYSTEM'),

-- ── Personenkonto: 직원 (파견/외부) ──
(1,1, 81007, 'Sijin Lee',                                  NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 81013, 'Sang Soo Kim',                               NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 81014, 'Sungmin Park',                               NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 81017, 'Il Hyun Lee',                                NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 81019, 'So Young Jeon',                              NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM'),
(1,1, 81020, 'Sung Young Oh',                              NULL, NULL, 'N','N','N','N','D','C','N', 'NONE', NULL, 0,'N','SYSTEM','SYSTEM')

ON DUPLICATE KEY UPDATE
    EXP_ACC_DESC    = VALUES(EXP_ACC_DESC),
    EXP_ACC_DESC_KO = VALUES(EXP_ACC_DESC_KO),
    PURCHASE_YN     = VALUES(PURCHASE_YN),
    SALES_YN        = VALUES(SALES_YN),
    EXPENSE_YN      = VALUES(EXPENSE_YN),
    FIXED_EXP_YN    = VALUES(FIXED_EXP_YN),
    DRCR_CD         = VALUES(DRCR_CD),
    CARRYOVER_CD    = VALUES(CARRYOVER_CD),
    FI_STMT_CD      = VALUES(FI_STMT_CD),
    EXP_CATG_CD     = VALUES(EXP_CATG_CD),
    DSP_ORD         = VALUES(DSP_ORD);
