-- V28: Customer Admin 하위에 부서관리/직원관리 메뉴 추가
-- 기존 ADMIN 메뉴(V23에서 INSERT) 하위에 DEPT, EMPL 추가

-- 1. ADMIN 부모 메뉴 ID 조회
SET @admin_id = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'ADMIN' AND MNU_SCOPE_CD = 'CST');

-- 2. 메뉴 INSERT (TB_MNU: MNU_NM=NOT NULL, PATH_URI 사용)
INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, BILL_GATE_CD, DSP_ORD, USE_YN)
VALUES ('DEPT', 'MNU.CST.ADM.DEPT', 'Departments', 'CST', @admin_id, '/customer/admin/departments', 'PCST', 40, 'Y')
ON DUPLICATE KEY UPDATE MNU_NM_CD = VALUES(MNU_NM_CD), DSP_ORD = VALUES(DSP_ORD);

INSERT INTO TB_MNU (MNU_CD, MNU_NM_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, BILL_GATE_CD, DSP_ORD, USE_YN)
VALUES ('EMPL', 'MNU.CST.ADM.EMPL', 'Employees', 'CST', @admin_id, '/customer/admin/employees', 'PCST', 50, 'Y')
ON DUPLICATE KEY UPDATE MNU_NM_CD = VALUES(MNU_NM_CD), DSP_ORD = VALUES(DSP_ORD);

-- 3. 번역 시드 (TB_CD: 한 레코드에 3개국어 컬럼 CD_NM_KO/CD_NM_EN/CD_NM_DE)
INSERT INTO TB_CD (GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, CD_DESC_KO, CD_DESC_EN, CD_DESC_DE, DSP_ORD, USE_YN)
VALUES (
  (SELECT ID FROM TB_CD_GRP WHERE GRP_CD = 'MNU_NM'),
  'MNU.CST.ADM.DEPT',
  '부서관리', 'Departments', 'Abteilungen',
  '부서관리', 'Departments', 'Abteilungen',
  0, 'Y'
)
ON DUPLICATE KEY UPDATE CD_NM_KO = VALUES(CD_NM_KO), CD_NM_EN = VALUES(CD_NM_EN), CD_NM_DE = VALUES(CD_NM_DE);

INSERT INTO TB_CD (GRP_ID, CD, CD_NM_KO, CD_NM_EN, CD_NM_DE, CD_DESC_KO, CD_DESC_EN, CD_DESC_DE, DSP_ORD, USE_YN)
VALUES (
  (SELECT ID FROM TB_CD_GRP WHERE GRP_CD = 'MNU_NM'),
  'MNU.CST.ADM.EMPL',
  '직원관리', 'Employees', 'Mitarbeiter',
  '직원관리', 'Employees', 'Mitarbeiter',
  0, 'Y'
)
ON DUPLICATE KEY UPDATE CD_NM_KO = VALUES(CD_NM_KO), CD_NM_EN = VALUES(CD_NM_EN), CD_NM_DE = VALUES(CD_NM_DE);

-- 4. 권한 매핑 (PADM, CADM, HR에 CRUD 부여)
SET @dept_mnu_id = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'DEPT' AND MNU_SCOPE_CD = 'CST');
SET @empl_mnu_id = (SELECT ID FROM TB_MNU WHERE MNU_CD = 'EMPL' AND MNU_SCOPE_CD = 'CST');

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN)
SELECT r.ID, @dept_mnu_id, 'Y', 'Y', 'Y', 'Y', 'N'
FROM TB_ROLE r WHERE r.ROLE_CD IN ('PADM', 'CADM', 'HR')
ON DUPLICATE KEY UPDATE VIEW_YN='Y', CRT_YN='Y', UPD_YN='Y', DEL_YN='Y';

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN)
SELECT r.ID, @empl_mnu_id, 'Y', 'Y', 'Y', 'Y', 'N'
FROM TB_ROLE r WHERE r.ROLE_CD IN ('PADM', 'CADM', 'HR')
ON DUPLICATE KEY UPDATE VIEW_YN='Y', CRT_YN='Y', UPD_YN='Y', DEL_YN='Y';
