CREATE TABLE TB_ACCESS_LOG (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Access log primary key',
    REQ_ID VARCHAR(36) NOT NULL COMMENT 'Request correlation id',
    TENANT_KEY VARCHAR(100) NULL COMMENT 'Tenant request key',
    USR_KEY VARCHAR(255) NULL COMMENT 'User principal key',
    HTTP_MTHD_CD VARCHAR(10) NOT NULL COMMENT 'HTTP method code',
    REQ_URI VARCHAR(500) NOT NULL COMMENT 'Request URI',
    REQ_QS_CNTS LONGTEXT NULL COMMENT 'Request query string contents',
    REQ_BODY_CNTS LONGTEXT NULL COMMENT 'Request body contents',
    REQ_HDR_CNTS LONGTEXT NULL COMMENT 'Request header contents',
    CLNT_IP VARCHAR(100) NULL COMMENT 'Client IP address',
    RESP_STS_CD VARCHAR(3) NOT NULL COMMENT 'Response status code',
    SUCC_YN CHAR(1) NOT NULL COMMENT 'Success yes or no',
    ERR_MSG VARCHAR(2000) NULL COMMENT 'Error message',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_ACCESS_LOG PRIMARY KEY (ID)
) COMMENT='Access log';

CREATE INDEX IX_TB_ACCESS_LOG_REQ_ID ON TB_ACCESS_LOG (REQ_ID);
CREATE INDEX IX_TB_ACCESS_LOG_TENANT_KEY ON TB_ACCESS_LOG (TENANT_KEY);
CREATE INDEX IX_TB_ACCESS_LOG_USR_KEY ON TB_ACCESS_LOG (USR_KEY);
CREATE INDEX IX_TB_ACCESS_LOG_CRT_DTM ON TB_ACCESS_LOG (CRT_DTM);
