ALTER TABLE TB_CO
    ADD COLUMN CO_CD VARCHAR(100) NOT NULL DEFAULT 'DEFAULT' COMMENT 'Company code' AFTER TENANT_ID;

CREATE UNIQUE INDEX UK_TB_CO_TENANT_ID_CO_CD ON TB_CO (TENANT_ID, CO_CD);

ALTER TABLE TB_CO_HIST
    ADD COLUMN CO_CD VARCHAR(100) NOT NULL DEFAULT 'DEFAULT' COMMENT 'Company code' AFTER TENANT_ID;

DROP TRIGGER IF EXISTS TR_TB_CO_AI;
DROP TRIGGER IF EXISTS TR_TB_CO_AU;
DROP TRIGGER IF EXISTS TR_TB_CO_BD;

CREATE TRIGGER TR_TB_CO_AI
AFTER INSERT ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_CD, CO_NM, REG_NO, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_CD, NEW.CO_NM, NEW.REG_NO, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CO_AU
AFTER UPDATE ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_CD, CO_NM, REG_NO, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_CD, NEW.CO_NM, NEW.REG_NO, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_CO_BD
BEFORE DELETE ON TB_CO
FOR EACH ROW
INSERT INTO TB_CO_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_CD, CO_NM, REG_NO, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_CD, OLD.CO_NM, OLD.REG_NO, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

ALTER TABLE TB_USR
    ADD COLUMN LGN_ID VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Login identifier' AFTER CO_ID,
    ADD COLUMN TEL_NO VARCHAR(30) NULL COMMENT 'Telephone number' AFTER LOCL_CD,
    ADD COLUMN AUTH_GRP_CD VARCHAR(20) NULL COMMENT 'Authorization group code' AFTER TEL_NO,
    ADD COLUMN AUTH_LVL_CD VARCHAR(20) NULL COMMENT 'Authorization level code' AFTER AUTH_GRP_CD;

DROP INDEX UK_TB_USR_EML ON TB_USR;
CREATE UNIQUE INDEX UK_TB_USR_TENANT_ID_LGN_ID ON TB_USR (TENANT_ID, LGN_ID);
CREATE UNIQUE INDEX UK_TB_USR_TENANT_ID_EML ON TB_USR (TENANT_ID, EML);

ALTER TABLE TB_USR_HIST
    ADD COLUMN LGN_ID VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Login identifier' AFTER CO_ID,
    ADD COLUMN TEL_NO VARCHAR(30) NULL COMMENT 'Telephone number' AFTER LOCL_CD,
    ADD COLUMN AUTH_GRP_CD VARCHAR(20) NULL COMMENT 'Authorization group code' AFTER TEL_NO,
    ADD COLUMN AUTH_LVL_CD VARCHAR(20) NULL COMMENT 'Authorization level code' AFTER AUTH_GRP_CD;

DROP TRIGGER IF EXISTS TR_TB_USR_AI;
DROP TRIGGER IF EXISTS TR_TB_USR_AU;
DROP TRIGGER IF EXISTS TR_TB_USR_BD;

CREATE TRIGGER TR_TB_USR_AI
AFTER INSERT ON TB_USR
FOR EACH ROW
INSERT INTO TB_USR_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, LGN_ID, EML, PWD_HASH, DSP_NM, LOCL_CD, TEL_NO, AUTH_GRP_CD, AUTH_LVL_CD, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.LGN_ID, NEW.EML, NEW.PWD_HASH, NEW.DSP_NM, NEW.LOCL_CD, NEW.TEL_NO, NEW.AUTH_GRP_CD, NEW.AUTH_LVL_CD, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_AU
AFTER UPDATE ON TB_USR
FOR EACH ROW
INSERT INTO TB_USR_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, LGN_ID, EML, PWD_HASH, DSP_NM, LOCL_CD, TEL_NO, AUTH_GRP_CD, AUTH_LVL_CD, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.LGN_ID, NEW.EML, NEW.PWD_HASH, NEW.DSP_NM, NEW.LOCL_CD, NEW.TEL_NO, NEW.AUTH_GRP_CD, NEW.AUTH_LVL_CD, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_BD
BEFORE DELETE ON TB_USR
FOR EACH ROW
INSERT INTO TB_USR_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, LGN_ID, EML, PWD_HASH, DSP_NM, LOCL_CD, TEL_NO, AUTH_GRP_CD, AUTH_LVL_CD, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.LGN_ID, OLD.EML, OLD.PWD_HASH, OLD.DSP_NM, OLD.LOCL_CD, OLD.TEL_NO, OLD.AUTH_GRP_CD, OLD.AUTH_LVL_CD, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

ALTER TABLE TB_ROLE
    ADD COLUMN ROLE_GRP_CD VARCHAR(20) NULL COMMENT 'Role group code' AFTER ROLE_NM,
    ADD COLUMN ROLE_LVL_CD VARCHAR(20) NULL COMMENT 'Role level code' AFTER ROLE_GRP_CD;

ALTER TABLE TB_ROLE_HIST
    ADD COLUMN ROLE_GRP_CD VARCHAR(20) NULL COMMENT 'Role group code' AFTER ROLE_NM,
    ADD COLUMN ROLE_LVL_CD VARCHAR(20) NULL COMMENT 'Role level code' AFTER ROLE_GRP_CD;

DROP TRIGGER IF EXISTS TR_TB_ROLE_AI;
DROP TRIGGER IF EXISTS TR_TB_ROLE_AU;
DROP TRIGGER IF EXISTS TR_TB_ROLE_BD;

CREATE TRIGGER TR_TB_ROLE_AI
AFTER INSERT ON TB_ROLE
FOR EACH ROW
INSERT INTO TB_ROLE_HIST (
    HIST_TP, HIST_BY, ID, ROLE_CD, ROLE_NM, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.ROLE_CD, NEW.ROLE_NM, NEW.ROLE_GRP_CD, NEW.ROLE_LVL_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ROLE_AU
AFTER UPDATE ON TB_ROLE
FOR EACH ROW
INSERT INTO TB_ROLE_HIST (
    HIST_TP, HIST_BY, ID, ROLE_CD, ROLE_NM, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.ROLE_CD, NEW.ROLE_NM, NEW.ROLE_GRP_CD, NEW.ROLE_LVL_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ROLE_BD
BEFORE DELETE ON TB_ROLE
FOR EACH ROW
INSERT INTO TB_ROLE_HIST (
    HIST_TP, HIST_BY, ID, ROLE_CD, ROLE_NM, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.ROLE_CD, OLD.ROLE_NM, OLD.ROLE_GRP_CD, OLD.ROLE_LVL_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

INSERT INTO TB_ROLE (
    ROLE_CD, ROLE_NM, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY
)
SELECT 'ROLE_ADMIN', 'Administrator', 'A', '9', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (
    SELECT 1
    FROM TB_ROLE
    WHERE ROLE_CD = 'ROLE_ADMIN'
);

INSERT INTO TB_ROLE (
    ROLE_CD, ROLE_NM, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY
)
SELECT 'ROLE_HR', 'Human Resources', 'H', '5', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (
    SELECT 1
    FROM TB_ROLE
    WHERE ROLE_CD = 'ROLE_HR'
);

INSERT INTO TB_ROLE (
    ROLE_CD, ROLE_NM, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY
)
SELECT 'ROLE_FINANCE', 'Finance', 'F', '5', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (
    SELECT 1
    FROM TB_ROLE
    WHERE ROLE_CD = 'ROLE_FINANCE'
);

INSERT INTO TB_ROLE (
    ROLE_CD, ROLE_NM, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY
)
SELECT 'ROLE_USER', 'General User', 'U', '1', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (
    SELECT 1
    FROM TB_ROLE
    WHERE ROLE_CD = 'ROLE_USER'
);
