ALTER TABLE TB_TENANT
    ADD COLUMN TENANT_TP_CD VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER' COMMENT 'Tenant type code' AFTER TENANT_NM,
    ADD COLUMN BILL_FREE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Billing free yes or no' AFTER TENANT_TP_CD;

ALTER TABLE TB_TENANT_HIST
    ADD COLUMN TENANT_TP_CD VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER' COMMENT 'Tenant type code' AFTER TENANT_NM,
    ADD COLUMN BILL_FREE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Billing free yes or no' AFTER TENANT_TP_CD;

DROP TRIGGER IF EXISTS TR_TB_TENANT_AI;
DROP TRIGGER IF EXISTS TR_TB_TENANT_AU;
DROP TRIGGER IF EXISTS TR_TB_TENANT_BD;

CREATE TRIGGER TR_TB_TENANT_AI
AFTER INSERT ON TB_TENANT
FOR EACH ROW
INSERT INTO TB_TENANT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_CD, TENANT_NM, TENANT_TP_CD, BILL_FREE_YN, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_CD, NEW.TENANT_NM, NEW.TENANT_TP_CD, NEW.BILL_FREE_YN, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_TENANT_AU
AFTER UPDATE ON TB_TENANT
FOR EACH ROW
INSERT INTO TB_TENANT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_CD, TENANT_NM, TENANT_TP_CD, BILL_FREE_YN, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_CD, NEW.TENANT_NM, NEW.TENANT_TP_CD, NEW.BILL_FREE_YN, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_TENANT_BD
BEFORE DELETE ON TB_TENANT
FOR EACH ROW
INSERT INTO TB_TENANT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_CD, TENANT_NM, TENANT_TP_CD, BILL_FREE_YN, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_CD, OLD.TENANT_NM, OLD.TENANT_TP_CD, OLD.BILL_FREE_YN, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

ALTER TABLE TB_ROLE
    ADD COLUMN ROLE_SCOPE_CD VARCHAR(20) NULL COMMENT 'Role scope code' AFTER ROLE_NM,
    ADD COLUMN ROLE_D1_CD VARCHAR(30) NULL COMMENT 'Role depth1 code' AFTER ROLE_SCOPE_CD,
    ADD COLUMN ROLE_D2_CD VARCHAR(30) NULL COMMENT 'Role depth2 code' AFTER ROLE_D1_CD,
    ADD COLUMN ROLE_D3_CD VARCHAR(30) NULL COMMENT 'Role depth3 code' AFTER ROLE_D2_CD;

ALTER TABLE TB_ROLE_HIST
    ADD COLUMN ROLE_SCOPE_CD VARCHAR(20) NULL COMMENT 'Role scope code' AFTER ROLE_NM,
    ADD COLUMN ROLE_D1_CD VARCHAR(30) NULL COMMENT 'Role depth1 code' AFTER ROLE_SCOPE_CD,
    ADD COLUMN ROLE_D2_CD VARCHAR(30) NULL COMMENT 'Role depth2 code' AFTER ROLE_D1_CD,
    ADD COLUMN ROLE_D3_CD VARCHAR(30) NULL COMMENT 'Role depth3 code' AFTER ROLE_D2_CD;

DROP TRIGGER IF EXISTS TR_TB_ROLE_AI;
DROP TRIGGER IF EXISTS TR_TB_ROLE_AU;
DROP TRIGGER IF EXISTS TR_TB_ROLE_BD;

CREATE TRIGGER TR_TB_ROLE_AI
AFTER INSERT ON TB_ROLE
FOR EACH ROW
INSERT INTO TB_ROLE_HIST (
    HIST_TP, HIST_BY, ID, ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.ROLE_CD, NEW.ROLE_NM, NEW.ROLE_SCOPE_CD, NEW.ROLE_D1_CD, NEW.ROLE_D2_CD, NEW.ROLE_D3_CD, NEW.ROLE_GRP_CD, NEW.ROLE_LVL_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ROLE_AU
AFTER UPDATE ON TB_ROLE
FOR EACH ROW
INSERT INTO TB_ROLE_HIST (
    HIST_TP, HIST_BY, ID, ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.ROLE_CD, NEW.ROLE_NM, NEW.ROLE_SCOPE_CD, NEW.ROLE_D1_CD, NEW.ROLE_D2_CD, NEW.ROLE_D3_CD, NEW.ROLE_GRP_CD, NEW.ROLE_LVL_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ROLE_BD
BEFORE DELETE ON TB_ROLE
FOR EACH ROW
INSERT INTO TB_ROLE_HIST (
    HIST_TP, HIST_BY, ID, ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.ROLE_CD, OLD.ROLE_NM, OLD.ROLE_SCOPE_CD, OLD.ROLE_D1_CD, OLD.ROLE_D2_CD, OLD.ROLE_D3_CD, OLD.ROLE_GRP_CD, OLD.ROLE_LVL_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

UPDATE TB_ROLE
SET ROLE_SCOPE_CD = 'CUSTOMER',
    ROLE_D1_CD = 'CUSTOMER',
    ROLE_D2_CD = 'USER',
    ROLE_D3_CD = 'TEAM_MEMBER'
WHERE ROLE_CD = 'ROLE_USER';

UPDATE TB_ROLE
SET ROLE_SCOPE_CD = 'CUSTOMER',
    ROLE_D1_CD = 'CUSTOMER',
    ROLE_D2_CD = 'FINANCE_ADMIN',
    ROLE_D3_CD = 'TEAM_LEADER'
WHERE ROLE_CD = 'ROLE_FINANCE';

UPDATE TB_ROLE
SET ROLE_SCOPE_CD = 'CUSTOMER',
    ROLE_D1_CD = 'CUSTOMER',
    ROLE_D2_CD = 'HR_ADMIN',
    ROLE_D3_CD = 'TEAM_LEADER'
WHERE ROLE_CD = 'ROLE_HR';

UPDATE TB_ROLE
SET ROLE_SCOPE_CD = 'CUSTOMER',
    ROLE_D1_CD = 'CUSTOMER',
    ROLE_D2_CD = 'ADMIN',
    ROLE_D3_CD = 'TEAM_LEADER'
WHERE ROLE_CD = 'ROLE_ADMIN';

CREATE TABLE TB_MNU (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Menu primary key',
    MNU_CD VARCHAR(100) NOT NULL COMMENT 'Menu code',
    MNU_NM VARCHAR(255) NOT NULL COMMENT 'Menu name',
    MNU_SCOPE_CD VARCHAR(20) NOT NULL COMMENT 'Menu scope code',
    UP_MNU_ID BIGINT NULL COMMENT 'Upper menu primary key',
    PATH_URI VARCHAR(500) NULL COMMENT 'Path uri',
    ICON_NM VARCHAR(100) NULL COMMENT 'Icon name',
    DSP_ORD INT NOT NULL DEFAULT 0 COMMENT 'Display order',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'Use yes or no',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_MNU PRIMARY KEY (ID),
    CONSTRAINT UK_TB_MNU_MNU_CD UNIQUE (MNU_CD),
    CONSTRAINT FK_TB_MNU_01 FOREIGN KEY (UP_MNU_ID) REFERENCES TB_MNU (ID)
) COMMENT='Menu master';

CREATE TABLE TB_MNU_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Menu primary key',
    MNU_CD VARCHAR(100) NOT NULL COMMENT 'Menu code',
    MNU_NM VARCHAR(255) NOT NULL COMMENT 'Menu name',
    MNU_SCOPE_CD VARCHAR(20) NOT NULL COMMENT 'Menu scope code',
    UP_MNU_ID BIGINT NULL COMMENT 'Upper menu primary key',
    PATH_URI VARCHAR(500) NULL COMMENT 'Path uri',
    ICON_NM VARCHAR(100) NULL COMMENT 'Icon name',
    DSP_ORD INT NOT NULL COMMENT 'Display order',
    USE_YN CHAR(1) NOT NULL COMMENT 'Use yes or no',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_MNU_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Menu history';

CREATE INDEX IX_TB_MNU_UP_MNU_ID ON TB_MNU (UP_MNU_ID);
CREATE INDEX IX_TB_MNU_SCOPE_CD ON TB_MNU (MNU_SCOPE_CD);
CREATE INDEX IX_TB_MNU_HIST_ID ON TB_MNU_HIST (ID);
CREATE INDEX IX_TB_MNU_HIST_HIST_DTM ON TB_MNU_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_MNU_AI
AFTER INSERT ON TB_MNU
FOR EACH ROW
INSERT INTO TB_MNU_HIST (
    HIST_TP, HIST_BY, ID, MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.MNU_CD, NEW.MNU_NM, NEW.MNU_SCOPE_CD, NEW.UP_MNU_ID, NEW.PATH_URI, NEW.ICON_NM, NEW.DSP_ORD, NEW.USE_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_MNU_AU
AFTER UPDATE ON TB_MNU
FOR EACH ROW
INSERT INTO TB_MNU_HIST (
    HIST_TP, HIST_BY, ID, MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.MNU_CD, NEW.MNU_NM, NEW.MNU_SCOPE_CD, NEW.UP_MNU_ID, NEW.PATH_URI, NEW.ICON_NM, NEW.DSP_ORD, NEW.USE_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_MNU_BD
BEFORE DELETE ON TB_MNU
FOR EACH ROW
INSERT INTO TB_MNU_HIST (
    HIST_TP, HIST_BY, ID, MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.MNU_CD, OLD.MNU_NM, OLD.MNU_SCOPE_CD, OLD.UP_MNU_ID, OLD.PATH_URI, OLD.ICON_NM, OLD.DSP_ORD, OLD.USE_YN, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TABLE TB_ROLE_MNU_AUTH (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Role menu auth primary key',
    ROLE_ID BIGINT NOT NULL COMMENT 'Role primary key reference',
    MNU_ID BIGINT NOT NULL COMMENT 'Menu primary key reference',
    VIEW_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'View yes or no',
    CRT_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Create yes or no',
    UPD_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Update yes or no',
    DEL_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Delete yes or no',
    APRV_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Approve yes or no',
    EXPRT_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Export yes or no',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_ROLE_MNU_AUTH PRIMARY KEY (ID),
    CONSTRAINT UK_TB_ROLE_MNU_AUTH_ROLE_ID_MNU_ID UNIQUE (ROLE_ID, MNU_ID),
    CONSTRAINT FK_TB_ROLE_MNU_AUTH_01 FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE (ID),
    CONSTRAINT FK_TB_ROLE_MNU_AUTH_02 FOREIGN KEY (MNU_ID) REFERENCES TB_MNU (ID)
) COMMENT='Role menu auth';

CREATE TABLE TB_ROLE_MNU_AUTH_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Role menu auth primary key',
    ROLE_ID BIGINT NOT NULL COMMENT 'Role primary key reference',
    MNU_ID BIGINT NOT NULL COMMENT 'Menu primary key reference',
    VIEW_YN CHAR(1) NOT NULL COMMENT 'View yes or no',
    CRT_YN CHAR(1) NOT NULL COMMENT 'Create yes or no',
    UPD_YN CHAR(1) NOT NULL COMMENT 'Update yes or no',
    DEL_YN CHAR(1) NOT NULL COMMENT 'Delete yes or no',
    APRV_YN CHAR(1) NOT NULL COMMENT 'Approve yes or no',
    EXPRT_YN CHAR(1) NOT NULL COMMENT 'Export yes or no',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_ROLE_MNU_AUTH_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Role menu auth history';

CREATE INDEX IX_TB_ROLE_MNU_AUTH_ROLE_ID ON TB_ROLE_MNU_AUTH (ROLE_ID);
CREATE INDEX IX_TB_ROLE_MNU_AUTH_MNU_ID ON TB_ROLE_MNU_AUTH (MNU_ID);
CREATE INDEX IX_TB_ROLE_MNU_AUTH_HIST_ID ON TB_ROLE_MNU_AUTH_HIST (ID);
CREATE INDEX IX_TB_ROLE_MNU_AUTH_HIST_HIST_DTM ON TB_ROLE_MNU_AUTH_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_ROLE_MNU_AUTH_AI
AFTER INSERT ON TB_ROLE_MNU_AUTH
FOR EACH ROW
INSERT INTO TB_ROLE_MNU_AUTH_HIST (
    HIST_TP, HIST_BY, ID, ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.ROLE_ID, NEW.MNU_ID, NEW.VIEW_YN, NEW.CRT_YN, NEW.UPD_YN, NEW.DEL_YN, NEW.APRV_YN, NEW.EXPRT_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ROLE_MNU_AUTH_AU
AFTER UPDATE ON TB_ROLE_MNU_AUTH
FOR EACH ROW
INSERT INTO TB_ROLE_MNU_AUTH_HIST (
    HIST_TP, HIST_BY, ID, ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.ROLE_ID, NEW.MNU_ID, NEW.VIEW_YN, NEW.CRT_YN, NEW.UPD_YN, NEW.DEL_YN, NEW.APRV_YN, NEW.EXPRT_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_ROLE_MNU_AUTH_BD
BEFORE DELETE ON TB_ROLE_MNU_AUTH
FOR EACH ROW
INSERT INTO TB_ROLE_MNU_AUTH_HIST (
    HIST_TP, HIST_BY, ID, ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.ROLE_ID, OLD.MNU_ID, OLD.VIEW_YN, OLD.CRT_YN, OLD.UPD_YN, OLD.DEL_YN, OLD.APRV_YN, OLD.EXPRT_YN, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TABLE TB_SUBS_PLAN (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Subscription plan primary key',
    PLAN_CD VARCHAR(100) NOT NULL COMMENT 'Plan code',
    PLAN_NM VARCHAR(255) NOT NULL COMMENT 'Plan name',
    TENANT_TP_CD VARCHAR(20) NOT NULL COMMENT 'Tenant type code',
    BILL_CYCL_CD VARCHAR(20) NOT NULL COMMENT 'Billing cycle code',
    CURR_CD VARCHAR(10) NOT NULL COMMENT 'Currency code',
    BASE_AMT DECIMAL(15,2) NOT NULL DEFAULT 0 COMMENT 'Base amount',
    USR_LMT_CNT INT NULL COMMENT 'User limit count',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'Use yes or no',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_SUBS_PLAN PRIMARY KEY (ID),
    CONSTRAINT UK_TB_SUBS_PLAN_PLAN_CD UNIQUE (PLAN_CD)
) COMMENT='Subscription plan master';

CREATE TABLE TB_SUBS_PLAN_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Subscription plan primary key',
    PLAN_CD VARCHAR(100) NOT NULL COMMENT 'Plan code',
    PLAN_NM VARCHAR(255) NOT NULL COMMENT 'Plan name',
    TENANT_TP_CD VARCHAR(20) NOT NULL COMMENT 'Tenant type code',
    BILL_CYCL_CD VARCHAR(20) NOT NULL COMMENT 'Billing cycle code',
    CURR_CD VARCHAR(10) NOT NULL COMMENT 'Currency code',
    BASE_AMT DECIMAL(15,2) NOT NULL COMMENT 'Base amount',
    USR_LMT_CNT INT NULL COMMENT 'User limit count',
    USE_YN CHAR(1) NOT NULL COMMENT 'Use yes or no',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_SUBS_PLAN_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Subscription plan history';

CREATE INDEX IX_TB_SUBS_PLAN_HIST_ID ON TB_SUBS_PLAN_HIST (ID);
CREATE INDEX IX_TB_SUBS_PLAN_HIST_HIST_DTM ON TB_SUBS_PLAN_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_SUBS_PLAN_AI
AFTER INSERT ON TB_SUBS_PLAN
FOR EACH ROW
INSERT INTO TB_SUBS_PLAN_HIST (
    HIST_TP, HIST_BY, ID, PLAN_CD, PLAN_NM, TENANT_TP_CD, BILL_CYCL_CD, CURR_CD, BASE_AMT, USR_LMT_CNT, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.PLAN_CD, NEW.PLAN_NM, NEW.TENANT_TP_CD, NEW.BILL_CYCL_CD, NEW.CURR_CD, NEW.BASE_AMT, NEW.USR_LMT_CNT, NEW.USE_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_SUBS_PLAN_AU
AFTER UPDATE ON TB_SUBS_PLAN
FOR EACH ROW
INSERT INTO TB_SUBS_PLAN_HIST (
    HIST_TP, HIST_BY, ID, PLAN_CD, PLAN_NM, TENANT_TP_CD, BILL_CYCL_CD, CURR_CD, BASE_AMT, USR_LMT_CNT, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.PLAN_CD, NEW.PLAN_NM, NEW.TENANT_TP_CD, NEW.BILL_CYCL_CD, NEW.CURR_CD, NEW.BASE_AMT, NEW.USR_LMT_CNT, NEW.USE_YN, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_SUBS_PLAN_BD
BEFORE DELETE ON TB_SUBS_PLAN
FOR EACH ROW
INSERT INTO TB_SUBS_PLAN_HIST (
    HIST_TP, HIST_BY, ID, PLAN_CD, PLAN_NM, TENANT_TP_CD, BILL_CYCL_CD, CURR_CD, BASE_AMT, USR_LMT_CNT, USE_YN, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.PLAN_CD, OLD.PLAN_NM, OLD.TENANT_TP_CD, OLD.BILL_CYCL_CD, OLD.CURR_CD, OLD.BASE_AMT, OLD.USR_LMT_CNT, OLD.USE_YN, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TABLE TB_SUBS (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Subscription primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    PLAN_ID BIGINT NOT NULL COMMENT 'Subscription plan primary key reference',
    SUBS_STS_CD VARCHAR(20) NOT NULL COMMENT 'Subscription status code',
    BILL_FREE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Billing free yes or no',
    AUTO_PAY_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'Auto pay yes or no',
    STR_DT DATE NOT NULL COMMENT 'Start date',
    END_DT DATE NULL COMMENT 'End date',
    NEXT_BILL_DT DATE NULL COMMENT 'Next billing date',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_SUBS PRIMARY KEY (ID),
    CONSTRAINT FK_TB_SUBS_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_SUBS_02 FOREIGN KEY (PLAN_ID) REFERENCES TB_SUBS_PLAN (ID)
) COMMENT='Subscription master';

CREATE TABLE TB_SUBS_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Subscription primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    PLAN_ID BIGINT NOT NULL COMMENT 'Subscription plan primary key reference',
    SUBS_STS_CD VARCHAR(20) NOT NULL COMMENT 'Subscription status code',
    BILL_FREE_YN CHAR(1) NOT NULL COMMENT 'Billing free yes or no',
    AUTO_PAY_YN CHAR(1) NOT NULL COMMENT 'Auto pay yes or no',
    STR_DT DATE NOT NULL COMMENT 'Start date',
    END_DT DATE NULL COMMENT 'End date',
    NEXT_BILL_DT DATE NULL COMMENT 'Next billing date',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_SUBS_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Subscription history';

CREATE INDEX IX_TB_SUBS_TENANT_ID ON TB_SUBS (TENANT_ID);
CREATE INDEX IX_TB_SUBS_PLAN_ID ON TB_SUBS (PLAN_ID);
CREATE INDEX IX_TB_SUBS_HIST_ID ON TB_SUBS_HIST (ID);
CREATE INDEX IX_TB_SUBS_HIST_HIST_DTM ON TB_SUBS_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_SUBS_AI
AFTER INSERT ON TB_SUBS
FOR EACH ROW
INSERT INTO TB_SUBS_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, PLAN_ID, SUBS_STS_CD, BILL_FREE_YN, AUTO_PAY_YN, STR_DT, END_DT, NEXT_BILL_DT, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.PLAN_ID, NEW.SUBS_STS_CD, NEW.BILL_FREE_YN, NEW.AUTO_PAY_YN, NEW.STR_DT, NEW.END_DT, NEW.NEXT_BILL_DT, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_SUBS_AU
AFTER UPDATE ON TB_SUBS
FOR EACH ROW
INSERT INTO TB_SUBS_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, PLAN_ID, SUBS_STS_CD, BILL_FREE_YN, AUTO_PAY_YN, STR_DT, END_DT, NEXT_BILL_DT, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.PLAN_ID, NEW.SUBS_STS_CD, NEW.BILL_FREE_YN, NEW.AUTO_PAY_YN, NEW.STR_DT, NEW.END_DT, NEW.NEXT_BILL_DT, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_SUBS_BD
BEFORE DELETE ON TB_SUBS
FOR EACH ROW
INSERT INTO TB_SUBS_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, PLAN_ID, SUBS_STS_CD, BILL_FREE_YN, AUTO_PAY_YN, STR_DT, END_DT, NEXT_BILL_DT, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.PLAN_ID, OLD.SUBS_STS_CD, OLD.BILL_FREE_YN, OLD.AUTO_PAY_YN, OLD.STR_DT, OLD.END_DT, OLD.NEXT_BILL_DT, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TABLE TB_PAY_TXN (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Payment transaction primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    SUBS_ID BIGINT NOT NULL COMMENT 'Subscription primary key reference',
    PAY_TP_CD VARCHAR(20) NOT NULL COMMENT 'Payment type code',
    PAY_STS_CD VARCHAR(20) NOT NULL COMMENT 'Payment status code',
    PAY_AMT DECIMAL(15,2) NOT NULL DEFAULT 0 COMMENT 'Payment amount',
    CURR_CD VARCHAR(10) NOT NULL COMMENT 'Currency code',
    PG_CD VARCHAR(30) NULL COMMENT 'Payment gateway code',
    PG_TXN_NO VARCHAR(100) NULL COMMENT 'Payment gateway transaction number',
    APRV_DTM TIMESTAMP NULL COMMENT 'Approved datetime',
    FAIL_MSG VARCHAR(1000) NULL COMMENT 'Failure message',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_PAY_TXN PRIMARY KEY (ID),
    CONSTRAINT FK_TB_PAY_TXN_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_PAY_TXN_02 FOREIGN KEY (SUBS_ID) REFERENCES TB_SUBS (ID)
) COMMENT='Payment transaction master';

CREATE TABLE TB_PAY_TXN_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Payment transaction primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    SUBS_ID BIGINT NOT NULL COMMENT 'Subscription primary key reference',
    PAY_TP_CD VARCHAR(20) NOT NULL COMMENT 'Payment type code',
    PAY_STS_CD VARCHAR(20) NOT NULL COMMENT 'Payment status code',
    PAY_AMT DECIMAL(15,2) NOT NULL COMMENT 'Payment amount',
    CURR_CD VARCHAR(10) NOT NULL COMMENT 'Currency code',
    PG_CD VARCHAR(30) NULL COMMENT 'Payment gateway code',
    PG_TXN_NO VARCHAR(100) NULL COMMENT 'Payment gateway transaction number',
    APRV_DTM TIMESTAMP NULL COMMENT 'Approved datetime',
    FAIL_MSG VARCHAR(1000) NULL COMMENT 'Failure message',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_PAY_TXN_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Payment transaction history';

CREATE INDEX IX_TB_PAY_TXN_TENANT_ID ON TB_PAY_TXN (TENANT_ID);
CREATE INDEX IX_TB_PAY_TXN_SUBS_ID ON TB_PAY_TXN (SUBS_ID);
CREATE INDEX IX_TB_PAY_TXN_HIST_ID ON TB_PAY_TXN_HIST (ID);
CREATE INDEX IX_TB_PAY_TXN_HIST_HIST_DTM ON TB_PAY_TXN_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_PAY_TXN_AI
AFTER INSERT ON TB_PAY_TXN
FOR EACH ROW
INSERT INTO TB_PAY_TXN_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, SUBS_ID, PAY_TP_CD, PAY_STS_CD, PAY_AMT, CURR_CD, PG_CD, PG_TXN_NO, APRV_DTM, FAIL_MSG, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.SUBS_ID, NEW.PAY_TP_CD, NEW.PAY_STS_CD, NEW.PAY_AMT, NEW.CURR_CD, NEW.PG_CD, NEW.PG_TXN_NO, NEW.APRV_DTM, NEW.FAIL_MSG, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_PAY_TXN_AU
AFTER UPDATE ON TB_PAY_TXN
FOR EACH ROW
INSERT INTO TB_PAY_TXN_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, SUBS_ID, PAY_TP_CD, PAY_STS_CD, PAY_AMT, CURR_CD, PG_CD, PG_TXN_NO, APRV_DTM, FAIL_MSG, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.SUBS_ID, NEW.PAY_TP_CD, NEW.PAY_STS_CD, NEW.PAY_AMT, NEW.CURR_CD, NEW.PG_CD, NEW.PG_TXN_NO, NEW.APRV_DTM, NEW.FAIL_MSG, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_PAY_TXN_BD
BEFORE DELETE ON TB_PAY_TXN
FOR EACH ROW
INSERT INTO TB_PAY_TXN_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, SUBS_ID, PAY_TP_CD, PAY_STS_CD, PAY_AMT, CURR_CD, PG_CD, PG_TXN_NO, APRV_DTM, FAIL_MSG, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.SUBS_ID, OLD.PAY_TP_CD, OLD.PAY_STS_CD, OLD.PAY_AMT, OLD.CURR_CD, OLD.PG_CD, OLD.PG_TXN_NO, OLD.APRV_DTM, OLD.FAIL_MSG, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_PLATFORM_SUPER_ADMIN', 'Platform Super Admin', 'ADMIN', 'ADMIN', 'SUPER_ADMIN', 'ROOT', 'A', '10', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_PLATFORM_SUPER_ADMIN');

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_PLATFORM_ADMIN', 'Platform Admin', 'ADMIN', 'ADMIN', 'NORMAL_ADMIN', 'ROOT', 'A', '7', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_PLATFORM_ADMIN');

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_CUSTOMER_USER_MEMBER', 'Customer User Member', 'CUSTOMER', 'CUSTOMER', 'USER', 'TEAM_MEMBER', 'U', '1', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_CUSTOMER_USER_MEMBER');

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_CUSTOMER_USER_LEADER', 'Customer User Leader', 'CUSTOMER', 'CUSTOMER', 'USER', 'TEAM_LEADER', 'U', '2', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_CUSTOMER_USER_LEADER');

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_CUSTOMER_FINANCE_ADMIN_MEMBER', 'Customer Finance Admin Member', 'CUSTOMER', 'CUSTOMER', 'FINANCE_ADMIN', 'TEAM_MEMBER', 'F', '5', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_CUSTOMER_FINANCE_ADMIN_MEMBER');

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_CUSTOMER_FINANCE_ADMIN_LEADER', 'Customer Finance Admin Leader', 'CUSTOMER', 'CUSTOMER', 'FINANCE_ADMIN', 'TEAM_LEADER', 'F', '6', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_CUSTOMER_FINANCE_ADMIN_LEADER');

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_CUSTOMER_HR_ADMIN_MEMBER', 'Customer HR Admin Member', 'CUSTOMER', 'CUSTOMER', 'HR_ADMIN', 'TEAM_MEMBER', 'H', '5', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_CUSTOMER_HR_ADMIN_MEMBER');

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_CUSTOMER_HR_ADMIN_LEADER', 'Customer HR Admin Leader', 'CUSTOMER', 'CUSTOMER', 'HR_ADMIN', 'TEAM_LEADER', 'H', '6', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_CUSTOMER_HR_ADMIN_LEADER');

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_CUSTOMER_ADMIN_MEMBER', 'Customer Integrated Admin Member', 'CUSTOMER', 'CUSTOMER', 'ADMIN', 'TEAM_MEMBER', 'C', '8', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_CUSTOMER_ADMIN_MEMBER');

INSERT INTO TB_ROLE (ROLE_CD, ROLE_NM, ROLE_SCOPE_CD, ROLE_D1_CD, ROLE_D2_CD, ROLE_D3_CD, ROLE_GRP_CD, ROLE_LVL_CD, CRT_BY, UPD_BY)
SELECT 'ROLE_CUSTOMER_ADMIN_LEADER', 'Customer Integrated Admin Leader', 'CUSTOMER', 'CUSTOMER', 'ADMIN', 'TEAM_LEADER', 'C', '9', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_ROLE WHERE ROLE_CD = 'ROLE_CUSTOMER_ADMIN_LEADER');

INSERT INTO TB_SUBS_PLAN (PLAN_CD, PLAN_NM, TENANT_TP_CD, BILL_CYCL_CD, CURR_CD, BASE_AMT, USR_LMT_CNT, USE_YN, CRT_BY, UPD_BY)
SELECT 'PLAN_INTERNAL_FREE', 'Internal Free Plan', 'INTERNAL', 'MONTHLY', 'EUR', 0.00, NULL, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_SUBS_PLAN WHERE PLAN_CD = 'PLAN_INTERNAL_FREE');

INSERT INTO TB_SUBS_PLAN (PLAN_CD, PLAN_NM, TENANT_TP_CD, BILL_CYCL_CD, CURR_CD, BASE_AMT, USR_LMT_CNT, USE_YN, CRT_BY, UPD_BY)
SELECT 'PLAN_B2B_BASIC', 'B2B Basic Plan', 'CUSTOMER', 'MONTHLY', 'EUR', 99.00, 30, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_SUBS_PLAN WHERE PLAN_CD = 'PLAN_B2B_BASIC');

INSERT INTO TB_SUBS_PLAN (PLAN_CD, PLAN_NM, TENANT_TP_CD, BILL_CYCL_CD, CURR_CD, BASE_AMT, USR_LMT_CNT, USE_YN, CRT_BY, UPD_BY)
SELECT 'PLAN_B2B_PRO', 'B2B Pro Plan', 'CUSTOMER', 'MONTHLY', 'EUR', 299.00, 200, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_SUBS_PLAN WHERE PLAN_CD = 'PLAN_B2B_PRO');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_ADMIN_DASH', 'Admin Dashboard', 'ADMIN', NULL, '/admin/dashboard', 'layout-dashboard', 10, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_ADMIN_DASH');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_ADMIN_TENANT', 'Tenant Management', 'ADMIN', NULL, '/admin/tenants', 'building-2', 20, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_ADMIN_TENANT');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_ADMIN_AUTH', 'Authorization Management', 'ADMIN', NULL, '/admin/authorization', 'shield-check', 30, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_ADMIN_AUTH');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_ADMIN_BILL', 'Billing Management', 'ADMIN', NULL, '/admin/billing', 'credit-card', 40, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_ADMIN_BILL');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_ADMIN_MENU', 'Menu Management', 'ADMIN', NULL, '/admin/menus', 'menu-square', 50, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_ADMIN_MENU');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_CUSTOMER_DASH', 'Customer Dashboard', 'CUSTOMER', NULL, '/customer/dashboard', 'layout-dashboard', 10, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_DASH');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_CUSTOMER_TEAM', 'Team Management', 'CUSTOMER', NULL, '/customer/team', 'users', 20, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_TEAM');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_CUSTOMER_HR', 'HR Management', 'CUSTOMER', NULL, '/customer/hr', 'user-round-check', 30, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_HR');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_CUSTOMER_FIN', 'Finance Management', 'CUSTOMER', NULL, '/customer/finance', 'wallet', 40, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_FIN');

INSERT INTO TB_MNU (MNU_CD, MNU_NM, MNU_SCOPE_CD, UP_MNU_ID, PATH_URI, ICON_NM, DSP_ORD, USE_YN, CRT_BY, UPD_BY)
SELECT 'MNU_CUSTOMER_PAY', 'Payment Center', 'CUSTOMER', NULL, '/customer/payments', 'receipt', 50, 'Y', 'SYSTEM', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM TB_MNU WHERE MNU_CD = 'MNU_CUSTOMER_PAY');

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID, m.ID, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'SYSTEM', 'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_SCOPE_CD = 'ADMIN'
WHERE r.ROLE_CD = 'ROLE_PLATFORM_SUPER_ADMIN'
  AND NOT EXISTS (SELECT 1 FROM TB_ROLE_MNU_AUTH a WHERE a.ROLE_ID = r.ID AND a.MNU_ID = m.ID);

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID, m.ID, 'Y',
       CASE WHEN m.MNU_CD IN ('MNU_ADMIN_TENANT','MNU_ADMIN_AUTH','MNU_ADMIN_BILL','MNU_ADMIN_MENU') THEN 'Y' ELSE 'N' END,
       CASE WHEN m.MNU_CD IN ('MNU_ADMIN_TENANT','MNU_ADMIN_AUTH','MNU_ADMIN_BILL','MNU_ADMIN_MENU') THEN 'Y' ELSE 'N' END,
       'N',
       CASE WHEN m.MNU_CD = 'MNU_ADMIN_BILL' THEN 'Y' ELSE 'N' END,
       CASE WHEN m.MNU_CD IN ('MNU_ADMIN_TENANT','MNU_ADMIN_BILL') THEN 'Y' ELSE 'N' END,
       'SYSTEM', 'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_SCOPE_CD = 'ADMIN'
WHERE r.ROLE_CD = 'ROLE_PLATFORM_ADMIN'
  AND NOT EXISTS (SELECT 1 FROM TB_ROLE_MNU_AUTH a WHERE a.ROLE_ID = r.ID AND a.MNU_ID = m.ID);

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID, m.ID, 'Y',
       CASE WHEN m.MNU_CD = 'MNU_CUSTOMER_TEAM' AND r.ROLE_CD LIKE '%LEADER' THEN 'Y' ELSE 'N' END,
       CASE WHEN m.MNU_CD = 'MNU_CUSTOMER_TEAM' AND r.ROLE_CD LIKE '%LEADER' THEN 'Y' ELSE 'N' END,
       'N',
       CASE WHEN m.MNU_CD = 'MNU_CUSTOMER_TEAM' AND r.ROLE_CD LIKE '%LEADER' THEN 'Y' ELSE 'N' END,
       'N',
       'SYSTEM', 'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_CD IN ('MNU_CUSTOMER_DASH','MNU_CUSTOMER_TEAM')
WHERE r.ROLE_CD IN ('ROLE_CUSTOMER_USER_MEMBER','ROLE_CUSTOMER_USER_LEADER')
  AND NOT EXISTS (SELECT 1 FROM TB_ROLE_MNU_AUTH a WHERE a.ROLE_ID = r.ID AND a.MNU_ID = m.ID);

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID, m.ID, 'Y',
       CASE WHEN m.MNU_CD IN ('MNU_CUSTOMER_FIN','MNU_CUSTOMER_PAY') THEN 'Y' ELSE 'N' END,
       CASE WHEN m.MNU_CD IN ('MNU_CUSTOMER_FIN','MNU_CUSTOMER_PAY') THEN 'Y' ELSE 'N' END,
       'N',
       CASE WHEN m.MNU_CD = 'MNU_CUSTOMER_PAY' OR r.ROLE_CD LIKE '%LEADER' THEN 'Y' ELSE 'N' END,
       CASE WHEN m.MNU_CD IN ('MNU_CUSTOMER_FIN','MNU_CUSTOMER_PAY') THEN 'Y' ELSE 'N' END,
       'SYSTEM', 'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_CD IN ('MNU_CUSTOMER_DASH','MNU_CUSTOMER_FIN','MNU_CUSTOMER_PAY')
WHERE r.ROLE_CD IN ('ROLE_CUSTOMER_FINANCE_ADMIN_MEMBER','ROLE_CUSTOMER_FINANCE_ADMIN_LEADER')
  AND NOT EXISTS (SELECT 1 FROM TB_ROLE_MNU_AUTH a WHERE a.ROLE_ID = r.ID AND a.MNU_ID = m.ID);

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID, m.ID, 'Y',
       CASE WHEN m.MNU_CD IN ('MNU_CUSTOMER_HR','MNU_CUSTOMER_TEAM') THEN 'Y' ELSE 'N' END,
       CASE WHEN m.MNU_CD IN ('MNU_CUSTOMER_HR','MNU_CUSTOMER_TEAM') THEN 'Y' ELSE 'N' END,
       'N',
       CASE WHEN r.ROLE_CD LIKE '%LEADER' THEN 'Y' ELSE 'N' END,
       'N',
       'SYSTEM', 'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_CD IN ('MNU_CUSTOMER_DASH','MNU_CUSTOMER_HR','MNU_CUSTOMER_TEAM')
WHERE r.ROLE_CD IN ('ROLE_CUSTOMER_HR_ADMIN_MEMBER','ROLE_CUSTOMER_HR_ADMIN_LEADER')
  AND NOT EXISTS (SELECT 1 FROM TB_ROLE_MNU_AUTH a WHERE a.ROLE_ID = r.ID AND a.MNU_ID = m.ID);

INSERT INTO TB_ROLE_MNU_AUTH (ROLE_ID, MNU_ID, VIEW_YN, CRT_YN, UPD_YN, DEL_YN, APRV_YN, EXPRT_YN, CRT_BY, UPD_BY)
SELECT r.ID, m.ID, 'Y',
       CASE WHEN m.MNU_CD IN ('MNU_CUSTOMER_TEAM','MNU_CUSTOMER_HR','MNU_CUSTOMER_FIN','MNU_CUSTOMER_PAY') THEN 'Y' ELSE 'N' END,
       CASE WHEN m.MNU_CD IN ('MNU_CUSTOMER_TEAM','MNU_CUSTOMER_HR','MNU_CUSTOMER_FIN','MNU_CUSTOMER_PAY') THEN 'Y' ELSE 'N' END,
       CASE WHEN r.ROLE_CD LIKE '%LEADER' THEN 'Y' ELSE 'N' END,
       CASE WHEN r.ROLE_CD LIKE '%LEADER' THEN 'Y' ELSE 'N' END,
       CASE WHEN m.MNU_CD IN ('MNU_CUSTOMER_FIN','MNU_CUSTOMER_PAY') OR r.ROLE_CD LIKE '%LEADER' THEN 'Y' ELSE 'N' END,
       'SYSTEM', 'SYSTEM'
FROM TB_ROLE r
JOIN TB_MNU m ON m.MNU_SCOPE_CD = 'CUSTOMER'
WHERE r.ROLE_CD IN ('ROLE_CUSTOMER_ADMIN_MEMBER','ROLE_CUSTOMER_ADMIN_LEADER')
  AND NOT EXISTS (SELECT 1 FROM TB_ROLE_MNU_AUTH a WHERE a.ROLE_ID = r.ID AND a.MNU_ID = m.ID);
