CREATE TABLE TB_DEPT (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Department primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NOT NULL COMMENT 'Company primary key reference',
    DEPT_CD VARCHAR(100) NOT NULL COMMENT 'Department code',
    DEPT_NM VARCHAR(255) NOT NULL COMMENT 'Department name',
    UP_DEPT_ID BIGINT NULL COMMENT 'Upper department primary key',
    DEPT_LVL_NO INT NOT NULL DEFAULT 1 COMMENT 'Department level number',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_DEPT PRIMARY KEY (ID),
    CONSTRAINT UK_TB_DEPT_TENANT_ID_CO_ID_DEPT_CD UNIQUE (TENANT_ID, CO_ID, DEPT_CD),
    CONSTRAINT FK_TB_DEPT_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_DEPT_02 FOREIGN KEY (CO_ID) REFERENCES TB_CO (ID),
    CONSTRAINT FK_TB_DEPT_03 FOREIGN KEY (UP_DEPT_ID) REFERENCES TB_DEPT (ID)
) COMMENT='Department master';

CREATE TABLE TB_DEPT_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Department primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NOT NULL COMMENT 'Company primary key reference',
    DEPT_CD VARCHAR(100) NOT NULL COMMENT 'Department code',
    DEPT_NM VARCHAR(255) NOT NULL COMMENT 'Department name',
    UP_DEPT_ID BIGINT NULL COMMENT 'Upper department primary key',
    DEPT_LVL_NO INT NOT NULL COMMENT 'Department level number',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_DEPT_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Department history';

CREATE INDEX IX_TB_DEPT_TENANT_ID ON TB_DEPT (TENANT_ID);
CREATE INDEX IX_TB_DEPT_CO_ID ON TB_DEPT (CO_ID);
CREATE INDEX IX_TB_DEPT_UP_DEPT_ID ON TB_DEPT (UP_DEPT_ID);
CREATE INDEX IX_TB_DEPT_HIST_ID ON TB_DEPT_HIST (ID);
CREATE INDEX IX_TB_DEPT_HIST_HIST_DTM ON TB_DEPT_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_DEPT_AI
AFTER INSERT ON TB_DEPT
FOR EACH ROW
INSERT INTO TB_DEPT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, DEPT_CD, DEPT_NM, UP_DEPT_ID, DEPT_LVL_NO, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.DEPT_CD, NEW.DEPT_NM, NEW.UP_DEPT_ID, NEW.DEPT_LVL_NO, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_DEPT_AU
AFTER UPDATE ON TB_DEPT
FOR EACH ROW
INSERT INTO TB_DEPT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, DEPT_CD, DEPT_NM, UP_DEPT_ID, DEPT_LVL_NO, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.DEPT_CD, NEW.DEPT_NM, NEW.UP_DEPT_ID, NEW.DEPT_LVL_NO, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_DEPT_BD
BEFORE DELETE ON TB_DEPT
FOR EACH ROW
INSERT INTO TB_DEPT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, DEPT_CD, DEPT_NM, UP_DEPT_ID, DEPT_LVL_NO, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.DEPT_CD, OLD.DEPT_NM, OLD.UP_DEPT_ID, OLD.DEPT_LVL_NO, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

CREATE TABLE TB_EMP (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Employee primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NOT NULL COMMENT 'Company primary key reference',
    USR_ID BIGINT NULL COMMENT 'User primary key reference',
    DEPT_ID BIGINT NULL COMMENT 'Department primary key reference',
    MGR_EMP_ID BIGINT NULL COMMENT 'Manager employee primary key reference',
    EMP_NO VARCHAR(100) NOT NULL COMMENT 'Employee number',
    EMP_NM VARCHAR(255) NOT NULL COMMENT 'Employee name',
    TEAM_ROLE_CD VARCHAR(20) NOT NULL DEFAULT 'TEAM_MEMBER' COMMENT 'Team role code',
    JOB_TTL_NM VARCHAR(255) NULL COMMENT 'Job title name',
    HIRE_DT DATE NULL COMMENT 'Hire date',
    RETR_DT DATE NULL COMMENT 'Retire date',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_EMP PRIMARY KEY (ID),
    CONSTRAINT UK_TB_EMP_TENANT_ID_CO_ID_EMP_NO UNIQUE (TENANT_ID, CO_ID, EMP_NO),
    CONSTRAINT UK_TB_EMP_USR_ID UNIQUE (USR_ID),
    CONSTRAINT FK_TB_EMP_01 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID),
    CONSTRAINT FK_TB_EMP_02 FOREIGN KEY (CO_ID) REFERENCES TB_CO (ID),
    CONSTRAINT FK_TB_EMP_03 FOREIGN KEY (USR_ID) REFERENCES TB_USR (ID),
    CONSTRAINT FK_TB_EMP_04 FOREIGN KEY (DEPT_ID) REFERENCES TB_DEPT (ID),
    CONSTRAINT FK_TB_EMP_05 FOREIGN KEY (MGR_EMP_ID) REFERENCES TB_EMP (ID)
) COMMENT='Employee master';

CREATE TABLE TB_EMP_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'Employee primary key',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    CO_ID BIGINT NOT NULL COMMENT 'Company primary key reference',
    USR_ID BIGINT NULL COMMENT 'User primary key reference',
    DEPT_ID BIGINT NULL COMMENT 'Department primary key reference',
    MGR_EMP_ID BIGINT NULL COMMENT 'Manager employee primary key reference',
    EMP_NO VARCHAR(100) NOT NULL COMMENT 'Employee number',
    EMP_NM VARCHAR(255) NOT NULL COMMENT 'Employee name',
    TEAM_ROLE_CD VARCHAR(20) NOT NULL COMMENT 'Team role code',
    JOB_TTL_NM VARCHAR(255) NULL COMMENT 'Job title name',
    HIRE_DT DATE NULL COMMENT 'Hire date',
    RETR_DT DATE NULL COMMENT 'Retire date',
    STS_CD VARCHAR(20) NOT NULL COMMENT 'Status code',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_EMP_HIST PRIMARY KEY (HIST_ID)
) COMMENT='Employee history';

CREATE INDEX IX_TB_EMP_TENANT_ID ON TB_EMP (TENANT_ID);
CREATE INDEX IX_TB_EMP_CO_ID ON TB_EMP (CO_ID);
CREATE INDEX IX_TB_EMP_USR_ID ON TB_EMP (USR_ID);
CREATE INDEX IX_TB_EMP_DEPT_ID ON TB_EMP (DEPT_ID);
CREATE INDEX IX_TB_EMP_MGR_EMP_ID ON TB_EMP (MGR_EMP_ID);
CREATE INDEX IX_TB_EMP_HIST_ID ON TB_EMP_HIST (ID);
CREATE INDEX IX_TB_EMP_HIST_HIST_DTM ON TB_EMP_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_EMP_AI
AFTER INSERT ON TB_EMP
FOR EACH ROW
INSERT INTO TB_EMP_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, DEPT_ID, MGR_EMP_ID, EMP_NO, EMP_NM, TEAM_ROLE_CD, JOB_TTL_NM, HIRE_DT, RETR_DT, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.USR_ID, NEW.DEPT_ID, NEW.MGR_EMP_ID, NEW.EMP_NO, NEW.EMP_NM, NEW.TEAM_ROLE_CD, NEW.JOB_TTL_NM, NEW.HIRE_DT, NEW.RETR_DT, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_EMP_AU
AFTER UPDATE ON TB_EMP
FOR EACH ROW
INSERT INTO TB_EMP_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, DEPT_ID, MGR_EMP_ID, EMP_NO, EMP_NM, TEAM_ROLE_CD, JOB_TTL_NM, HIRE_DT, RETR_DT, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_ID, NEW.CO_ID, NEW.USR_ID, NEW.DEPT_ID, NEW.MGR_EMP_ID, NEW.EMP_NO, NEW.EMP_NM, NEW.TEAM_ROLE_CD, NEW.JOB_TTL_NM, NEW.HIRE_DT, NEW.RETR_DT, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_EMP_BD
BEFORE DELETE ON TB_EMP
FOR EACH ROW
INSERT INTO TB_EMP_HIST (
    HIST_TP, HIST_BY, ID, TENANT_ID, CO_ID, USR_ID, DEPT_ID, MGR_EMP_ID, EMP_NO, EMP_NM, TEAM_ROLE_CD, JOB_TTL_NM, HIRE_DT, RETR_DT, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_ID, OLD.CO_ID, OLD.USR_ID, OLD.DEPT_ID, OLD.MGR_EMP_ID, OLD.EMP_NO, OLD.EMP_NM, OLD.TEAM_ROLE_CD, OLD.JOB_TTL_NM, OLD.HIRE_DT, OLD.RETR_DT, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);
