CREATE TABLE TB_USR_OAUTH (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'User oauth identity primary key',
    USR_ID BIGINT NOT NULL COMMENT 'User primary key reference',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    OAUTH_PROV_CD VARCHAR(30) NOT NULL COMMENT 'OAuth provider code',
    OAUTH_SUB VARCHAR(255) NOT NULL COMMENT 'OAuth subject identifier',
    EML VARCHAR(255) NULL COMMENT 'OAuth email snapshot',
    EML_VRFY_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Email verified yes or no',
    LAST_LGN_DTM TIMESTAMP NULL COMMENT 'Last login datetime',
    CRT_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_USR_OAUTH PRIMARY KEY (ID),
    CONSTRAINT UK_TB_USR_OAUTH_PROV_SUB UNIQUE (OAUTH_PROV_CD, OAUTH_SUB),
    CONSTRAINT FK_TB_USR_OAUTH_01 FOREIGN KEY (USR_ID) REFERENCES TB_USR (ID),
    CONSTRAINT FK_TB_USR_OAUTH_02 FOREIGN KEY (TENANT_ID) REFERENCES TB_TENANT (ID)
) COMMENT='User oauth identity';

CREATE TABLE TB_USR_OAUTH_HIST (
    HIST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'History primary key',
    HIST_TP CHAR(1) NOT NULL COMMENT 'I,U,D',
    HIST_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'History datetime',
    HIST_BY VARCHAR(100) NOT NULL COMMENT 'History actor',
    ID BIGINT NOT NULL COMMENT 'User oauth identity primary key',
    USR_ID BIGINT NOT NULL COMMENT 'User primary key reference',
    TENANT_ID BIGINT NOT NULL COMMENT 'Tenant primary key reference',
    OAUTH_PROV_CD VARCHAR(30) NOT NULL COMMENT 'OAuth provider code',
    OAUTH_SUB VARCHAR(255) NOT NULL COMMENT 'OAuth subject identifier',
    EML VARCHAR(255) NULL COMMENT 'OAuth email snapshot',
    EML_VRFY_YN CHAR(1) NOT NULL COMMENT 'Email verified yes or no',
    LAST_LGN_DTM TIMESTAMP NULL COMMENT 'Last login datetime',
    CRT_BY VARCHAR(100) NOT NULL COMMENT 'Created by',
    CRT_DTM TIMESTAMP NOT NULL COMMENT 'Created datetime',
    UPD_BY VARCHAR(100) NOT NULL COMMENT 'Updated by',
    UPD_DTM TIMESTAMP NOT NULL COMMENT 'Updated datetime',
    CONSTRAINT PK_TB_USR_OAUTH_HIST PRIMARY KEY (HIST_ID)
) COMMENT='User oauth identity history';

CREATE INDEX IX_TB_USR_OAUTH_USR_ID ON TB_USR_OAUTH (USR_ID);
CREATE INDEX IX_TB_USR_OAUTH_TENANT_ID ON TB_USR_OAUTH (TENANT_ID);
CREATE INDEX IX_TB_USR_OAUTH_HIST_ID ON TB_USR_OAUTH_HIST (ID);
CREATE INDEX IX_TB_USR_OAUTH_HIST_HIST_DTM ON TB_USR_OAUTH_HIST (HIST_DTM);

CREATE TRIGGER TR_TB_USR_OAUTH_AI
AFTER INSERT ON TB_USR_OAUTH
FOR EACH ROW
INSERT INTO TB_USR_OAUTH_HIST (
    HIST_TP, HIST_BY, ID, USR_ID, TENANT_ID, OAUTH_PROV_CD, OAUTH_SUB, EML, EML_VRFY_YN, LAST_LGN_DTM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.USR_ID, NEW.TENANT_ID, NEW.OAUTH_PROV_CD, NEW.OAUTH_SUB, NEW.EML, NEW.EML_VRFY_YN, NEW.LAST_LGN_DTM, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_OAUTH_AU
AFTER UPDATE ON TB_USR_OAUTH
FOR EACH ROW
INSERT INTO TB_USR_OAUTH_HIST (
    HIST_TP, HIST_BY, ID, USR_ID, TENANT_ID, OAUTH_PROV_CD, OAUTH_SUB, EML, EML_VRFY_YN, LAST_LGN_DTM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.USR_ID, NEW.TENANT_ID, NEW.OAUTH_PROV_CD, NEW.OAUTH_SUB, NEW.EML, NEW.EML_VRFY_YN, NEW.LAST_LGN_DTM, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_USR_OAUTH_BD
BEFORE DELETE ON TB_USR_OAUTH
FOR EACH ROW
INSERT INTO TB_USR_OAUTH_HIST (
    HIST_TP, HIST_BY, ID, USR_ID, TENANT_ID, OAUTH_PROV_CD, OAUTH_SUB, EML, EML_VRFY_YN, LAST_LGN_DTM, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.USR_ID, OLD.TENANT_ID, OLD.OAUTH_PROV_CD, OLD.OAUTH_SUB, OLD.EML, OLD.EML_VRFY_YN, OLD.LAST_LGN_DTM, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);
