ALTER TABLE TB_TENANT
    ADD COLUMN EML_DOMN VARCHAR(255) NULL COMMENT 'Login email domain' AFTER TENANT_NM;

CREATE UNIQUE INDEX UK_TB_TENANT_EML_DOMN ON TB_TENANT (EML_DOMN);

ALTER TABLE TB_TENANT_HIST
    ADD COLUMN EML_DOMN VARCHAR(255) NULL COMMENT 'Login email domain' AFTER TENANT_NM;

DROP TRIGGER IF EXISTS TR_TB_TENANT_AI;
DROP TRIGGER IF EXISTS TR_TB_TENANT_AU;
DROP TRIGGER IF EXISTS TR_TB_TENANT_BD;

CREATE TRIGGER TR_TB_TENANT_AI
AFTER INSERT ON TB_TENANT
FOR EACH ROW
INSERT INTO TB_TENANT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_CD, TENANT_NM, EML_DOMN, TENANT_TP_CD, BILL_FREE_YN, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'I', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_CD, NEW.TENANT_NM, NEW.EML_DOMN, NEW.TENANT_TP_CD, NEW.BILL_FREE_YN, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_TENANT_AU
AFTER UPDATE ON TB_TENANT
FOR EACH ROW
INSERT INTO TB_TENANT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_CD, TENANT_NM, EML_DOMN, TENANT_TP_CD, BILL_FREE_YN, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'U', COALESCE(NEW.UPD_BY, NEW.CRT_BY, 'SYSTEM'), NEW.ID, NEW.TENANT_CD, NEW.TENANT_NM, NEW.EML_DOMN, NEW.TENANT_TP_CD, NEW.BILL_FREE_YN, NEW.STS_CD, NEW.CRT_BY, NEW.CRT_DTM, NEW.UPD_BY, NEW.UPD_DTM
);

CREATE TRIGGER TR_TB_TENANT_BD
BEFORE DELETE ON TB_TENANT
FOR EACH ROW
INSERT INTO TB_TENANT_HIST (
    HIST_TP, HIST_BY, ID, TENANT_CD, TENANT_NM, EML_DOMN, TENANT_TP_CD, BILL_FREE_YN, STS_CD, CRT_BY, CRT_DTM, UPD_BY, UPD_DTM
) VALUES (
    'D', COALESCE(OLD.UPD_BY, OLD.CRT_BY, 'SYSTEM'), OLD.ID, OLD.TENANT_CD, OLD.TENANT_NM, OLD.EML_DOMN, OLD.TENANT_TP_CD, OLD.BILL_FREE_YN, OLD.STS_CD, OLD.CRT_BY, OLD.CRT_DTM, OLD.UPD_BY, OLD.UPD_DTM
);

UPDATE TB_TENANT
SET EML_DOMN = 'sinwoo.com'
WHERE TENANT_CD = 'SINWOO'
  AND (EML_DOMN IS NULL OR EML_DOMN = '');
